### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by JanSkovhus** [sockless-coding/panasonic_cc#1]
Hi, this looks very nice, just what I was looking for, but I do get an error when trying to login.
Keep up the good work.
Regards Jan

Log Details (ERROR)
Logger: custom_components.panasonic_cc.config_flow
Source: custom_components/panasonic_cc/config_flow.py:42 
Integration: Panasonic Comfort Cloud (documentation) 
First occurred: 8:18:55 PM (2 occurrences) 
Last logged: 8:25:49 PM

Unexpected error creating device
Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/config_flow.py", line 42, in _create_device
    devices = await self.hass.async_add_executor_job(api.get_devices)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/pcomfortcloud/session.py", line 171, in get_devices
    self.login()
  File "/usr/local/lib/python3.7/site-packages/pcomfortcloud/session.py", line 103, in login
    self._get_groups()
  File "/usr/local/lib/python3.7/site-packages/pcomfortcloud/session.py", line 153, in _get_groups
    raise ResponseError(response.status_code, response.text)
pcomfortcloud.session.ResponseError: Invalid response, status code: 401 - Data: {"message":"Please login again and confirm the privacy notice","code":4102}

**Comment by sockless-coding** [comment]
Hi, that error comes when Panasonic updates their eula, you have to login in to their app and approve the changes. It's a bit annoying but I haven't found a way around it yet. But it only happens every now and again.
If HA reports the "Please login again and confirm the privacy notice" error its whats happening.

**Comment by JanSkovhus** [comment]
Hi, I have to login via the App, then I got the eula, I go direct to the web page and login there.
And now I can login in HA. But now I get a new error, see new issue.

**Comment by shyne99** [comment]
@sockless-coding I know this is closed but you seem to active on supporting this repo but also offering pull request to the pypi underlying library. 
I have posted an issue their regarding Privacy notice. I've managed to confirm the eula using Postman, but I lack the python skills to implements it safely and properly.

**Comment by sockless-coding** [comment]
@shyne99 Hi, sure I can take a look at it. Though there is also an issue if you have multiple accounts all seem to have to agree to the eula/privacy or at least the master account.
