### ISSUE TITLE
Error after update Hassio System to version 4.13. Home Assistant version 0.114.4

### ISSUE THREAD

**Issue by wdflorczyk** [sockless-coding/panasonic_cc#10]
Component has stoped working. I got this in logs: 2020-09-17 18:04:48 ERROR (MainThread) [custom_components.panasonic_cc.config_flow] Unexpected error creating device
Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/config_flow.py", line 50, in _create_device
    devices = await self.hass.async_add_executor_job(api.get_devices)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/pcomfortcloud/session.py", line 177, in get_devices
    for device in group['deviceIdList']:
KeyError: 'deviceIdList'

Reinstallation didnt't help.

**Comment by sockless-coding** [comment]
Hello, the error comes from the underlying library. There seems to be some issue when getting the device groups. Have you changed any settings in the Panasonic app?

**Comment by wdflorczyk** [comment]
No. I've updated system. Then i noticed both units weren't available to HA.

Maybe they changed something in panasonic. I saw that Python library You
use in component was updated today.

WF


czw., 17 wrz 2020, 19:41 użytkownik Jimmy Everling <notifications@github.com>
napisał:

**Comment by sockless-coding** [comment]
I've merged the changes and published a new release and it seems to be working. Looked like Panasonic made some changes.

**Comment by wdflorczyk** [comment]
Great! It's working again!
