### ISSUE TITLE
Missing panasonic_cc integration in hassio

### ISSUE THREAD

**Issue by helfm** [sockless-coding/panasonic_cc#100]
Hi Jimmy,

I hope you can help me.

I have installed the panasonic_cc integration via hacs in my hassio, but I can not find the integration in the system.
I have no log entry found!

Any idea whats running wrong?

KR Markus

**Comment by pootle** [comment]
I have just installed and got working, it is a bit messy in that you have to switch between different parts of HA as you set it up (especially if you are new to HA as I am). I used HACS and you need to make sure you have done every step in HACS setup, then the Panasonic integration worked fine.

**Comment by helfm** [comment]
Hi pottle,

I don't understand this answer. I have already installed some integrations via hacs. They have all worked.
What do you mean that every step should be done?
For the installation of hacs, or the Panasonic integration?
It probably won't be because of hacs. What steps should I follow for installing the Panasonic integration?

KR Markus

**Comment by helfm** [comment]
I can't even make it to the specified configuration windows. I can't find the window for the cloud user and its password.

KR Markus

**Comment by pootle** [comment]
I assume this means you have HACS showing up in Integrations tab

Do you have Panasonic comfort cloud showing in integrations? It should prompt for account details when you first use it.

If Panasonic Comfort Cloud is not in HA Integrations, check it is in HACS Integrations, Once it is there it should show up in HA Integrations after you have restarted HA.

Anything other than this and you probably need to check the logs.

**Comment by helfm** [comment]
I find the Panasonic Cloud integration in hacs after installation and restart, but I can't find any integration in ha. Therefore I can't enter any login data for the Panasonic Cloud.
I can't find anything in the logs.

KR Markus

**Comment by Billiegirl** [comment]
I have the same issue like helfm states, installed everything like described, it shows up in hacs but not in HA in general.

**Comment by helfm** [comment]
Hi Billiegirl!

Thank you very much, that was the solution.

KR helfm

**Comment by codyc1515** [comment]
Please close the issue.

**Comment by helfm** [comment]
Thx
