### ISSUE TITLE
Faster updating of 'current_power'

### ISSUE THREAD

**Issue by Ricks88** [sockless-coding/panasonic_cc#101]
Can it be made that we can set the update frequenty manualy? 
It updates now every ?15/30 minutes..

Would like to be able to update every 5 of real time, if possible :)

**Comment by nicx** [comment]
I just was wondering of incorrect values... bit when its only updating every 15minutes than its not wrong, but way to old :) so I admit that wish. Power sensor should update in real time or every minute. Is that possible?

**Comment by runningman84** [comment]
maybe you would like to add some zigbee plug in between which gives you realtime stats...

**Comment by codyc1515** [comment]
If you update the sensor too often, you will get banned by the Panasonic server. Sorry.

**Comment by sockless-coding** [comment]
Panasonic doesn't update the energy values in the API more than every 15min
