### ISSUE TITLE
Quiet mode

### ISSUE THREAD

**Issue by martymoose** [sockless-coding/panasonic_cc#102]
Hi
On there app and my remote there's a quite button
Is that the same as Eco in home assistant integration
My wife complains the Eco is not as quiet as if she turns sleep on with remote

Happy wife happy more integrations
Thanks

**Comment by Ricks88** [comment]
As far as i know and can notice, its the same.

**Comment by martymoose** [comment]
Sweet thanks for the reply
I'll give here the great news
Cheers
