### ISSUE TITLE
Doesn`t work in general

### ISSUE THREAD

**Issue by Trike27** [sockless-coding/panasonic_cc#103]
Hi,
I installed this via HACS with the goal to be able to analyze the energy-consumption of our new Panasonic Aquarea Heatpump. I logged in to Panasonic CC, but get only errors in Homeassistant. Is this still working and maintained?
![image](https://user-images.githubusercontent.com/15910746/223233899-d88c4fca-c19c-44b4-bae6-dd1e3103f5d9.png)
Settings of Energy Dashboard:
![image](https://user-images.githubusercontent.com/15910746/223234042-77fed512-2f21-41e3-854d-95baf1a3de28.png)
![image](https://user-images.githubusercontent.com/15910746/223234502-8fc621ac-aaf3-4a47-8529-fed8f3a202d2.png)
![image](https://user-images.githubusercontent.com/15910746/223234642-9b771c33-7b1f-4d6b-bebf-f6e8a00c9665.png)

Regards
Martin

**Comment by Puebllo** [comment]
Same Issue hear. I've Panasonic Aquera T-Cap Heatpump and after integration setup, all device controls and sensor are wrong and in energy configuration same issue like on @Trike27 screens

![image](https://user-images.githubusercontent.com/22179495/230881347-029e2591-27c1-42e8-926a-4c74f17111ee.png)

![image](https://user-images.githubusercontent.com/22179495/230881382-edfcf637-eeed-45f2-923b-ed8ce646bf11.png)

**Comment by jellewie** [comment]
The "Nanoe" is an extra unit that also has been added for me by the nitergration, while I know for a fact I don't have this option buildin into my AC unit (CS-TZ25WKEW). 
I believe this is an air cleaning add-on. There might be a bug that "adds" this feature by default



Also (At least in the latest updated version for HA en the integration and such) the power feature does seem to work for me
![image](https://github.com/sockless-coding/panasonic_cc/assets/1545223/4a34ce2c-102e-4a7d-b785-4da6cb7ca16f)

**Comment by codyc1515** [comment]
What is the issue here? You would like to use the Energy sensors on the Energy dashboard? Is this still happening for you?

**Comment by sockless-coding** [comment]
This issue has been inactive for a while, so we’re closing it for now. If you believe this issue is still relevant, please feel free to reopen it or create a new one.
