### ISSUE TITLE
Current power sensor usage in energy dashboard

### ISSUE THREAD

**Issue by Trike27** [sockless-coding/panasonic_cc#105]
Hi,
it`s not possible to add this value to the energy dashboard as the entity doesn`t show up in the list. Please see https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics for reference.

Regards

**Comment by cewbdex** [comment]
Can you try again? Works for me.

**Comment by codyc1515** [comment]
How did you get on?

**Comment by sockless-coding** [comment]
This issue has been inactive for a while, so we’re closing it for now. If you believe this issue is still relevant, please feel free to reopen it or create a new one.
