### ISSUE TITLE
CS-MTZ16WKE not reporting correctly due to AirSwingLR value being out of range (6)

### ISSUE THREAD

**Issue by kenchy** [sockless-coding/panasonic_cc#106]
Hello running the latest version through HACS, 3 of my 4 AC units work perfectly. The 4th responds to start and stop requests but does not report data back to HA. I downloaded the underlying python library and tried it from the command line and it reported all 4 fine.

Any ideas what to try?

**Comment by kenchy** [comment]
the version bumped on the application this morning (?), or recently anyway, and while the code that gets the app version from itunes seems to do the job, the token that the application caches, contained the version number and that was refused by panasonic. Anyway that locked the account I was using in HA so that inspired me to mess around. In a nutshell:

- the unit that was not reporting correctly (a CS-MTZ16WKE) was reporting a value of 6 for airSwingHorizontal/AirSwingLR. 
- This is not in constants.py
- my AirSwingLR section in constants.py now looks like:

   class AirSwingLR(Enum):
    Auto = -1
    Left = 1
    LeftMid = 5
    Mid = 2
    RightMid = 4
    Right = 0
    All = 6

- I'm not sure what this means, but I don't think I can control swing at the moment. That '6' doesn't change when changing the swing on the unit. I'll update this ticket when/if I figure out what it means. But it now reports status to HA.

**Comment by kenchy** [comment]
There is no horizintal airswing on that unit, so it looks like they've just picked 6 as a new value of not present. I'll leave this open though as the value of 6 needs to be added to constants.py. (assuming the maintainer ever returns.)

**Comment by kenchy** [comment]
I'm going to try a pull request to get this added. Wish me luck.

**Comment by codyc1515** [comment]
How did you get on?

**Comment by kenchy** [comment]
It didn't get added because it breaks the integration for some users. If you look in the pull request you can see that comment.

**Comment by sockless-coding** [comment]
This has been addressed. If you believe this issue is still relevant, please feel free to reopen it or create a new one.
