### ISSUE TITLE
Integration stopped working today

### ISSUE THREAD

**Issue by raczgy** [sockless-coding/panasonic_cc#107]
Hi, 
i've used this integration for a while with no issue.
unfortunately today the panasonic_cc stopped working.
It has a message in the log like:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/panasonic_cc/__init__.py", line 79, in async_setup_entry
    devices = await hass.async_add_executor_job(api.get_devices)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 201, in get_devices
    self.login()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 105, in login
    self._create_token()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 158, in _create_token
    raise ResponseError(response.status_code, response.text)
custom_components.panasonic_cc.pcomfortcloud.session.ResponseError: Invalid response, status code: 429 - Data: {"message":"Too Many Requests","code":42901}

The comfort cloud is available from the phone and I can manage the airconditioners via the mobil app.
Entities related to CC integration became unavailable in HA.

HA versions I use:
Home Assistant 2023.3.1
Supervisor 2023.04.0
Operating System 9.5
Frontend 20230302.0 - latest

If you have any idea, please share it with me.
Thanks,
György

**Comment by mishomvp** [comment]
It doesn't work for me either. It is possible that Panasonic has made some restrictions on the number of requests to their API.

**Comment by raczgy** [comment]
I don't know. I think if Panasonic would implement limitation than it would limit the mobile app as well.

**Comment by kenchy** [comment]
I had this. The integration will work with the new version. But the app version is hardcoded in the token file, which causes authentication to fail and then the account to lock. There will be a .panasonic-settings file in the homeassistant home directory, you can move this to a new location, and then try again. You will then have to wait for the account to unlock, or create a new account, (I created a new account).

**Comment by raczgy** [comment]
Thanks,  It works now without any further action on my side. Reasons described well on the mentioned thread connected with cached app version number and panasonic supported app versions.
Thanks for the answer and for the fix. HACS not yet notified about he new version, I assume it will come but now its not that urgent as it works as intended.. 
Issue can be closed.

**Comment by raczgy** [comment]
Actually. I close this case:)

**Comment by sikksakk** [comment]
Hi, i have this problem again now - maybe a new app version again?
