### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by juliennnnn** [sockless-coding/panasonic_cc#110]
Hello,
I installed the add-on from HACS and when I try to log in, here is the pop-up that I have: 
<img width="373" alt="Capture d’écran 2023-05-19 à 16 30 57" src="https://github.com/sockless-coding/panasonic_cc/assets/98406454/d6f81d11-e670-4c0f-afbb-bdb40ee31b42">

Could anyone help me?

Thanks :)

**Comment by jellewie** [comment]
I can not seem to replicate your issue, could you maybe describe your steps. and/or attached debug logs and such?

**Comment by matt-shine** [comment]
I have this too, response in browser console is
```
{
    "type": "abort",
    "flow_id": "<someid>",
    "handler": "panasonic_cc",
    "reason": "No devices",
    "description_placeholders": null
}
```

I have devices in my comfort cloud :/

**Comment by codyc1515** [comment]
Please try re-install from HACS.

**Comment by sockless-coding** [comment]
This issue has been inactive for a while, so we’re closing it for now. If you believe this issue is still relevant, please feel free to reopen it or create a new one.
