### ISSUE TITLE
"Depends on the cloud" Tag missing

### ISSUE THREAD

**Issue by jellewie** [sockless-coding/panasonic_cc#112]
So in the integrations menu there is not a "Depens on the cloud" tag. But in the readme of this repo it suggest this connects to the cloud. Furthermore it seems to stop working when I block the internet to my house they seem to not be controllable anymore.

![image](https://github.com/sockless-coding/panasonic_cc/assets/1545223/58a6c1df-78ea-41e8-83eb-b89dcae1f7c5)
![image](https://github.com/sockless-coding/panasonic_cc/assets/1545223/2923973c-9bb0-4bb7-9919-f96ab2cdb398)

Example of this tag (Remeha uses the cloud to control the local device):
![image](https://github.com/sockless-coding/panasonic_cc/assets/1545223/b56364fb-dc28-4a3a-82e3-eaa6f724bc50)

**Comment by progamer562** [comment]
ofc you need internet if its the cloud

**Comment by jellewie** [comment]
So by that, this would be the bug report that the "depends on the cloud" icon is missing in the integrations tab

**Comment by cewbdex** [comment]
This seems to be fixed now.

**Comment by jellewie** [comment]
this issue seems fixed now, and can be closed

![image](https://github.com/sockless-coding/panasonic_cc/assets/1545223/f4304b00-f411-44db-b7dd-07a423a5df4b)
