### ISSUE TITLE
Not an issue but Panasonic must have updated their system today.

### ISSUE THREAD

**Issue by RonnieRocket2** [sockless-coding/panasonic_cc#118]
The annoying 'please try later messages' from the app have dissapeared, so it looks like they have updated their system today 28/08/2023

**Comment by Hengjie** [comment]
I'm also getting a lot of "too many requests" messages. And if you use the main app, they've started to give 

```
E03-0037-5601
Suspicious activity is detected on your account, so your access was temporarily rejected to help avoid security issues.
Please try again after a while.
```
