### ISSUE TITLE
Code":"4000"，"message":"Missing required header parameter or bad request for header"}

### ISSUE THREAD

**Issue by RonnieRocket2** [sockless-coding/panasonic_cc#119]
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/panasonic_cc/pcomfortcloud/session.py:158
Integration: Panasonic Comfort Cloud (documentation, issues)
First occurred: 10:20:21 (3 occurrences)
Last logged: 10:21:28

Error setting up entry for panasonic_cc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/__init__.py", line 79, in async_setup_entry
    devices = await hass.async_add_executor_job(api.get_devices)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 201, in get_devices
    self.login()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 105, in login
    self._create_token()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 158, in _create_token
    raise ResponseError(response.status_code, response.text)
custom_components.panasonic_cc.pcomfortcloud.session.ResponseError: Invalid response, status code: 400 - Data: {"code":"4000"，"message":"Missing required header parameter or bad request for header"}

**Comment by GasparMDQ** [comment]
I was about to post the same error. Happened after a maintenance downtime from Panasonic

**Comment by hirafu** [comment]
Getting the same issue also after the Panasonic maintenance period

**Comment by kongjudas** [comment]
Tibber also lost connection to Panasonic, so it’s an API problem

**Comment by djmaxim1981** [comment]
Same issue here. Mobile app "Comfort Cloud" is now working after the maintenance, but HA still cannot detect it. Integration keeps saying "Failed to Setup". I also upgraded HA to 2023.9.2 today

**Comment by axelthefatcat** [comment]
Same problem here.

Home Assistant 2023.9.2
Supervisor 2023.09.2
Operating System 10.5
Frontend 20230911.0 - latest

custom_components.panasonic_cc.pcomfortcloud.session.ResponseError: Invalid response, status code: 400 - Data: {"code":"4000"，"message":"Missing required header parameter or bad request for header"}

**Comment by nibbo1974** [comment]
Same issue here - I have deleted the integration and tried to add it again and get "Unexpected error creating device."

**Comment by nelsongraca** [comment]
My assumption is that they changed something on the app again, will investigate

**Comment by shadowano** [comment]
The comfort cloud android app works fine after maintenance. The app was updated in April, so it might be that the server now requires headers added back then.

**Comment by nelsongraca** [comment]
most likely something that was either not mandatory or now enabled with a feature flag

**Comment by shadowano** [comment]
I tried running the Comfort Cloud android app through fiddler to see what has changed, like I did before when creating a simple .Net app to read data from the server, but now the app doesn't load when using a proxy. Tried also with fiddler CA installed on phone. I get same 4000 error in my .Net app.

**Comment by togume** [comment]
+1 here.

**Comment by MagnusThome** [comment]
Same here

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/__init__.py", line 79, in async_setup_entry
    devices = await hass.async_add_executor_job(api.get_devices)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 201, in get_devices
    self.login()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 105, in login
    self._create_token()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 158, in _create_token
    raise ResponseError(response.status_code, response.text)
custom_components.panasonic_cc.pcomfortcloud.session.ResponseError: Invalid response, status code: 400 - Data: {"code":"4000"，"message":"Missing required header parameter or bad request for header"}
```

**Comment by nelsongraca** [comment]
Tried to capture some traffic but it's not accepting the HTTP Toolkit certificates, need a rooted phone to try.

**Comment by nelsongraca** [comment]
@sockless-coding Tagging for visibility, maybe you have the means to quickly check what changed

**Comment by sockless-coding** [comment]
Seems like Panasonic changed something, I'll take a look and see if I can figure out what they changed.

**Comment by sockless-coding** [comment]
I've released v1.0.37 that solves this issue

**Comment by MagnusThome** [comment]
Works great 👍👍👍👍

**Comment by djmaxim1981** [comment]
Its working well now. Thank you!

**Comment by nelsongraca** [comment]
@sockless-coding thank you so much for fixing this so quickly.

**Comment by togume** [comment]
Back online!!! Thanks 🙏 🙌

**Comment by lawrencedudley** [comment]
Hey, had this issue today. Just wanted to say thanks so much for sorting it so quickly.

Maintaining open source software is often a thankless task, have donated :)

**Comment by TheDK** [comment]
Great, thanks!

**Comment by codyc1515** [comment]
I believe the issue can be closed now.
