### ISSUE TITLE
Integration doesnt work 

### ISSUE THREAD

**Issue by TomF79** [sockless-coding/panasonic_cc#120]
Panasonic has worked tonight on their cloud services. Since this morning the integration doesnt work. Reinstall doesnt work. Login doesnt work.

„Unexpected error creating device“

BR Tom

**Comment by sikksakk** [comment]
I have a similar issue - ResponseError looks similar to what the app also said this morning, maybe we use API in a different zone?

`Logger: homeassistant.config_entries
Source: custom_components/panasonic_cc/pcomfortcloud/session.py:158
Integration: Panasonic Comfort Cloud ([documentation](https://github.com/sockless-coding/panasonic_cc/), [issues](https://github.com/sockless-coding/panasonic_cc/issues))
First occurred: 09:37:30 (4 occurrences)
Last logged: 12:56:39

Error setting up entry for panasonic_cc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/__init__.py", line 79, in async_setup_entry
    devices = await hass.async_add_executor_job(api.get_devices)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 201, in get_devices
    self.login()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 105, in login
    self._create_token()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 158, in _create_token
    raise ResponseError(response.status_code, response.text)
custom_components.panasonic_cc.pcomfortcloud.session.ResponseError: Invalid response, status code: 503 - Data: {"message":"09/14/2023 01:00 ～ 09/14/2023 08:00 (UTC ± 00)","code":5300}`

**Comment by DhollanderJonas** [comment]
+1

**Comment by scs777** [comment]
+1 Can confirm issue.

**Comment by markvdhijden** [comment]
Same here... The Panasonic Comfort Cloud app itself is working correctly...

**Comment by johanwidell** [comment]
+1

**Comment by Hubro** [comment]
Exact same timing, problem and error message here. Presumably the API has changed in a backwards incompatible way since last night.

**Comment by sikksakk** [comment]
i'm wondering if we have to handle the 503 return code as service window message - i do have a "notification" in the app gui about a maintenance window - however the time isnt the same as in the integration responseerror data.
![Screenshot_20230914_140657_Comfort Cloud](https://github.com/sockless-coding/panasonic_cc/assets/2955755/0bf7acfe-bdb0-45a1-a461-a691d1d9aaa6)

**Comment by kongjudas** [comment]
The Tibber-app (Norway) doesn't connect either, so it's a Panasonic-thing, I guess.

**Comment by bakoscsaba** [comment]
+1 Same issue here.

**Comment by gulli1986** [comment]
Same here with this error log:

`This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/panasonic_cc/pcomfortcloud/session.py:158
Integration: Panasonic Comfort Cloud (documentation, issues)
First occurred: 4:25:43 PM (1 occurrences)
Last logged: 4:25:43 PM

Error setting up entry for panasonic_cc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/__init__.py", line 79, in async_setup_entry
    devices = await hass.async_add_executor_job(api.get_devices)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 201, in get_devices
    self.login()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 105, in login
    self._create_token()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 158, in _create_token
    raise ResponseError(response.status_code, response.text)
custom_components.panasonic_cc.pcomfortcloud.session.ResponseError: Invalid response, status code: 400 - Data: {"code":"4000"，"message":"Missing required header parameter or bad request for header"}
`

**Comment by tinajeroroman** [comment]
It doesn’t work,same problem

**Comment by elninosi** [comment]
+1

Something has changed on the Panasonic side.

**Comment by tinajeroroman** [comment]
I expect someone find a solution soon

**Comment by Remc000tje** [comment]
dito  +1

**Comment by nicx** [comment]
+1

**Comment by lennartdk** [comment]
+1

**Comment by hemaris-8b** [comment]
+1

**Comment by TomF79** [comment]
@sockless-coding 

can you help please?

**Comment by morton027** [comment]
Same here

**Comment by 705Marc** [comment]
same problem

**Comment by sockless-coding** [comment]
I'm looking in to it

**Comment by sockless-coding** [comment]
Looks like they have added some new headers
`X-CFC-API-KEY` and `X-APP-TIMESTAMP`
Unfortunately, they are doing some encoding on the `X-CFC-API-KEY` value `pSecurity.createSecurityKey("Comfort Cloud", timeStampValue)`

**Comment by massitate** [comment]
Anche a me da questa mattina non funziona più, ho provato a disinstallare e reinstallare ma niente

**Comment by massitate** [comment]
> Sembra che abbiano aggiunto alcune nuove intestazioni `X-CFC-API-KEY`e, `X-APP-TIMESTAMP` sfortunatamente, stanno eseguendo alcune codifiche sul `X-CFC-API-KEY`valore`pSecurity.createSecurityKey("Comfort Cloud", timeStampValue)`

Quindi bisogna aspettare Panasonic o un nuovo aggiornamento del componente aggiuntivo?

**Comment by sockless-coding** [comment]
I've released v1.0.37 that solves this issue

**Comment by sikksakk** [comment]
thank you!! you should have a "buy me a beer" button on your project ;-)

**Comment by sockless-coding** [comment]
@sikksakk hehe, guess I have to add a beer button next to the coffee one :)

**Comment by Hubro** [comment]
Works! Thanks for the quick fix @sockless-coding :smile: Bought you a few coffees!

@sikksakk See the "Buy me a coffee" link on the front page https://www.buymeacoffee.com/sockless

**Comment by sikksakk** [comment]
hehe! bought you a coffee atleast - can confirm its working for me 👍

**Comment by massitate** [comment]
Grazie mille funziona bene adesso

**Comment by baty0man** [comment]
Thanks so much!

**Comment by bschjoett** [comment]
Thanks for solving the problem, works fine.

**Comment by DIMtriad** [comment]
Thank You for the super fast fix!

**Comment by TomF79** [comment]
Thanks for the fast response

**Comment by tinajeroroman** [comment]
Great,  thanks a lotEnviado desde mi iPhoneEl 14 sept 2023, a las 22:55, Benny ***@***.***> escribió:﻿
Thanks for solving the problem, works fine.

**Comment by pklitscher** [comment]
> @sikksakk hehe, guess I have to add a beer button next to the coffee one :)

Hey @sockless-coding I have just added this integration to try set it up and I am getting the issue noted above "Unexpected error creating device."

Home Assistant: 2023.9.2
Supervisor: 2023.09.2
Operating System: 10.5
Frontend: 20230911.0 - latest

Panasonic Comfort Cloud: v1.0.37

CC is currently setup and working via app and on the same network as HA. 

So excited if this integration works, love your work.

**Comment by NilsOscar** [comment]
Can't integrate Panasonic Comfort Cloud 
I use:
Home Assistant Core: 2023.11.3
Panasonic Comfort Cloud - HomeAssistant Component v1.0.37

I get:
"Panasonic Comfort Cloud
Unexpected error creating device."

The Panasonic Comfort Cloud app itself is working correctly, i.e. ID an PW are correct

**Comment by codyc1515** [comment]
I believe this issue can be closed now.

**Comment by pklitscher** [comment]
> I believe this issue can be closed now.

I can confirm that v1.0.38 released last month resolved this issue for me. Thank you @sockless-coding 🙏
