### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by 705Marc** [sockless-coding/panasonic_cc#124]
Hello,

Its no Bug its only a quick question.

I have your integration running in my HomeAssistant.

Is it possible to get the userid and the password from the custom component files?
I forgot my login data and i hope its possible.

Thanks you for your work!

**Comment by sockless-coding** [comment]
Hi @705Marc 
Yes, you can get the login information if you have access to the Terminal/storage of Home Assistance.
All device data is stored in `config/.storage/core.config_entries`

**Comment by 705Marc** [comment]
@sockless-coding 
Thank you for your quick response.
