### ISSUE TITLE
No support for TARGET_TEMPERATURE_RANGE

### ISSUE THREAD

**Issue by kmashtt** [sockless-coding/panasonic_cc#125]
Hi,

Question/Request:
From what I've read HA doesn't recommend using target_temperature when HVAC mode is "heat/cool" but that's exactly what this integration does, unless I'm missing something?
Either way it would be nice to be able to set "target_temperature_high/low". 
Is there a specific reason this isn't the case, like a limitation by Panasonic Cloud? 
Looks like all that's needed otherwise is to add a constant to const.py

I'd make a PR myself if that would help.

Thanks, and sorry if my insight into all this is severely lacking!

**Comment by sockless-coding** [comment]
@kmashtt It's not supported by Panasonic. I have no idea what threshold are used when using a target temperature and the "auto" mode. But I tend to avoid it since it can end up fighting with other heating/cooling sources.

**Comment by kmashtt** [comment]
Ah, I was afraid that was the case. Too bad! I've been trying to use Auto and it's been giving me nothing but problems so I was hoping to be able to set a Min and Max allowed temp to stop the unit from fighting with itself (blasting hot, then cold, ad infinitum)
I'll have to look into ways of solving it with automations or templates instead.
Thank you for your work!
Closing this issue.
