### ISSUE TITLE
Adding state_class to temperature sensors

### ISSUE THREAD

**Issue by runningman84** [sockless-coding/panasonic_cc#128]
I would be great to see support for state_class in the temperature sensors. This would allow us to see longterm temperature trends...

https://developers.home-assistant.io/blog/2021/05/25/sensor_attributes/

Right now it looks like this

Klimaanlage Outside Temperature: 17	
unit_of_measurement: °C
icon: mdi:thermometer
friendly_name: Klimaanlage Outside Temperature

**Comment by sockless-coding** [comment]
Already been addressed in newer versions
