### ISSUE TITLE
Outside sensor gone

### ISSUE THREAD

**Issue by Ricks88** [sockless-coding/panasonic_cc#129]
![panasonic](https://github.com/sockless-coding/panasonic_cc/assets/91467918/f1f73d91-d886-47dc-9350-789ea8e25276)

My new panasonic "Panasonic Wandmodel ETHEREA" does not show any outside temp sensor anymore, it was there for a very short. Reinstalling or logging in does bring it back very few times but will be unavailable again soon.

**Comment by cewbdex** [comment]
Do you have the force outside option check?

**Comment by Ricks88** [comment]
> Do you have the force outside option check?

I did try both with and without, does not make a difference. Also i am not sure what exactly that option does?

**Comment by cewbdex** [comment]
#88

**Comment by cewbdex** [comment]
I had some issues myself with the energy sensor and only thing helped me was to remove the integration, restart, add, restart and configure again.

**Comment by codyc1515** [comment]
Is this resolved?

**Comment by sockless-coding** [comment]
This issue has been inactive for a while, so we’re closing it for now. If you believe this issue is still relevant, please feel free to reopen it or create a new one.
