### ISSUE TITLE
Integration support

### ISSUE THREAD

**Issue by codyc1515** [sockless-coding/panasonic_cc#136]
Any update on this @sockless-coding ? I could assist as a maintainer of the integration if you no longer wish to support it. I previously created and supported the Homebridge integration.

**Comment by msadatsafavi** [comment]
Would be great to see this add-on will continue to receive love. Happy to support as a user!

**Comment by codyc1515** [comment]
Bumping this. Again, I am happy to be a contributor and assist with the maintenance.

**Comment by codyc1515** [comment]
Bumping this. Again @sockless-coding, I am happy to be a contributor and assist with the maintenance.
