### ISSUE TITLE
Setting temperature to T15 or 15 using automation

### ISSUE THREAD

**Issue by mstendah** [sockless-coding/panasonic_cc#141]
Hi, I have an automation that turns on the unit using Heat mode, but is there a way to add a tenperature setting as well? Here is the code I currently use:

device_id: xxx
domain: climate
entity_id: climate.kitchen
type: set_hvac_mode
hvac_mode: heat
enabled: true

**Comment by codyc1515** [comment]
I believe this is a HA limitation in that you need to set the mode and then separately set the temperature.

**Comment by sockless-coding** [comment]
Added support for +8/15 in v1.0.49
