### ISSUE TITLE
How to set traget temperatures?

### ISSUE THREAD

**Issue by membersound** [sockless-coding/panasonic_cc#142]
Hi guys,

before buying a panasonic climate: does this integration support setting the target temperature for a Panasonic Etherea Z Series?

**Comment by codyc1515** [comment]
[This sales document](https://www.logicool-ac.com/wp-content/uploads/2014/05/R32-Etherea-VKE-Sales-Leaflet.pdf) suggests it uses the Comfort Cloud app, so yes. Worthwhile asking your salesperson which app it uses. This integration only works with Comfort Cloud.
