### ISSUE TITLE
Failed to set up

### ISSUE THREAD

**Issue by RonnieRocket2** [sockless-coding/panasonic_cc#146]
Stopped working today, perhaps Panasonic changed something?

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/http_websocket.py", line 715, in ping
    await self._send_frame(message, WSMsgType.PING)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/http_websocket.py", line 675, in _send_frame
    self._write(header + mask + message)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/http_websocket.py", line 702, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
2023-12-11 09:28:42.327 WARNING (MainThread) [hass_nabucasa.cloud_api] Fetched https://accounts.nabucasa.com/payments/subscription_info (401)
2023-12-11 09:28:42.327 ERROR (MainThread) [homeassistant.components.cloud.subscription] Failed to fetch subscription information
2023-12-11 09:33:50.572 ERROR (MainThread) [homeassistant.components.automation] Platform automation does not generate unique IDs. ID 1696970363434 already exists - ignoring automation.burglar_alarm_set_home_and_set_outside_lights
2023-12-11 09:34:57.243 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry  for panasonic_cc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/__init__.py", line 79, in async_setup_entry
    devices = await hass.async_add_executor_job(api.get_devices)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 207, in get_devices
    self.login()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 106, in login
    self._create_token()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 164, in _create_token
    raise ResponseError(response.status_code, response.text)
custom_components.panasonic_cc.pcomfortcloud.session.ResponseError: Invalid response, status code: 429 - Data: {"code":42901,"message":"Too Many Requests"}
2023-12-11 09:42:03.883 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry  for panasonic_cc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/__init__.py", line 79, in async_setup_entry
    devices = await hass.async_add_executor_job(api.get_devices)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 207, in get_devices
    self.login()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 106, in login
    self._create_token()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 164, in _create_token
    raise ResponseError(response.status_code, response.text)
custom_components.panasonic_cc.pcomfortcloud.session.ResponseError: Invalid response, status code: 429 - Data: {"code":42901,"message":"Too Many Requests"}

**Comment by pfrock42** [comment]
I have the same issue this morning... It definitely looks like Panasonic have changed something as the Panasonic App is working ok.
Seems to happen every six months or so.

**Comment by bakoscsaba** [comment]
Same issue here, integration failed to set up

**Comment by drseltsamford** [comment]
I'll join the queue, I've had the same problem since this morning.

**Comment by Auka84** [comment]
Same for me :(

**Comment by pfrock42** [comment]
> I have the same "too many requests" error in HA as well, but the comfortcloud app also shows all 3 of my aircons greyed out as well. Can't turn on or change any settings.
> 
> Something down at Panasonic's end maybe ?

I have just checked again and my Panasonic Comfort Cloud App is working and my AirCon systems (also 3) respond correctly. Maybe it could be a regional thing (I am in Europe).

**Comment by Auka84** [comment]
The first time my account was blocked I contacted Panasonic in France ( I’m from Belgium and they haven’t any support here) and they didn’t find any account. After searching they told me my account is linked to Japan. So it’s not linked to the region I think

**Comment by amirandola** [comment]
![image](https://github.com/sockless-coding/panasonic_cc/assets/79716717/5bd718d6-e220-4536-ab1b-b96351322c8a)

File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 164, in _create_token
    raise ResponseError(response.status_code, response.text)
custom_components.panasonic_cc.pcomfortcloud.session.ResponseError: Invalid response, status code: 500 - Data: {"code":5001,"message":"DB system error due to db system"}

**Comment by nelsongraca** [comment]
joining the club, Panasonic changed something again, I think it's time to get hardware to make them fully local.

**Comment by nguyenanh87** [comment]
When the intergrate plug in cannot used, I’ve tried to use on Panasonic comford cloud, it’s still ok. 

After that, i tried log out and log in on Comfort cloud app, it’s show the error:

Error
E03-0029-42901
Suspicious activity was detected on your account, and it has been blocked. Please try again after 24 hours. If the issue persists, we recommend unlinking your Comfort Cloud account from any unauthorized applications.

i think Panasonic has lock this kind of access.

**Comment by Auka84** [comment]
It’s why I didn’t try to log out. I was pretty sure to have this error message

**Comment by pfrock42** [comment]
It's generally better to have 2 emails for the same machines. One for homeassistant and the other for the standard Panasonic CC app. This is how I have mine configured and I have been able to login/logout all day from the Panasonic CC account.

If I remember correctly it was a bit of a PITA to setup but on normal conditions it avoids clashes between HA and the CC app.

**Comment by nelsongraca** [comment]
@pfrock42 I have the same setup, but having HA side not working sucks, not being able to keep the house warm automatically.
Panasonic is just plain dumb that keeps blocking things.

**Comment by sockless-coding** [comment]
Looks like Panasonic has had some issues with some of their servers. 
Some people have reported 500 errors with error messages indicating they had DB issues.
I would recommend running HA in a different account than what you use for the CC app.
Also, the reason the App might work and not HA or wise versa is because `accsmart.panasonic.com` is using DNS based load balancing.
For me it resolves to
```
Non-authoritative answer:
accsmart.panasonic.com  internet address = 13.33.243.13
accsmart.panasonic.com  internet address = 13.33.243.53
accsmart.panasonic.com  internet address = 13.33.243.112
accsmart.panasonic.com  internet address = 13.33.243.101
accsmart.panasonic.com  nameserver = ns-693.awsdns-22.net
accsmart.panasonic.com  nameserver = ns-1325.awsdns-37.org
accsmart.panasonic.com  nameserver = ns-1996.awsdns-57.co.uk
accsmart.panasonic.com  nameserver = ns-23.awsdns-02.com
```

**Comment by amirandola** [comment]
> Looks like Panasonic has had some issues with some of their servers. Some people have reported 500 errors with error messages indicating they had DB issues. I would recommend running HA in a different account than what you use for the CC app. Also, the reason the App might work and not HA or wise versa is because `accsmart.panasonic.com` is using DNS based load balancing. For me it resolves to
> 
> ```
> Non-authoritative answer:
> accsmart.panasonic.com  internet address = 13.33.243.13
> accsmart.panasonic.com  internet address = 13.33.243.53
> accsmart.panasonic.com  internet address = 13.33.243.112
> accsmart.panasonic.com  internet address = 13.33.243.101
> accsmart.panasonic.com  nameserver = ns-693.awsdns-22.net
> accsmart.panasonic.com  nameserver = ns-1325.awsdns-37.org
> accsmart.panasonic.com  nameserver = ns-1996.awsdns-57.co.uk
> accsmart.panasonic.com  nameserver = ns-23.awsdns-02.com
> ```

I have 500 error with DB error ("DB system error due to db system"). It's not a very telling message but if you want I can try to help you in investigating error.
On client side DNS that's no relevant difference between official API and the integration (I trace the query on my DNS server)... it seems strange that's only a load balancing problem, I try many request in both App or HA and App always work but HA never, if it were a load balancing problem, sometimes the app wouldn't work either

**Comment by mstendah** [comment]
> Looks like Panasonic has had some issues with some of their servers. 
> 
> Some people have reported 500 errors with error messages indicating they had DB issues.
> 
> I would recommend running HA in a different account than what you use for the CC app.
> 
> Also, the reason the App might work and not HA or wise versa is because `accsmart.panasonic.com` is using DNS based load balancing.
> 
> For me it resolves to
> 
> ```
> 
> Non-authoritative answer:
> 
> accsmart.panasonic.com  internet address = 13.33.243.13
> 
> accsmart.panasonic.com  internet address = 13.33.243.53
> 
> accsmart.panasonic.com  internet address = 13.33.243.112
> 
> accsmart.panasonic.com  internet address = 13.33.243.101
> 
> accsmart.panasonic.com  nameserver = ns-693.awsdns-22.net
> 
> accsmart.panasonic.com  nameserver = ns-1325.awsdns-37.org
> 
> accsmart.panasonic.com  nameserver = ns-1996.awsdns-57.co.uk
> 
> accsmart.panasonic.com  nameserver = ns-23.awsdns-02.com
> 
> ```

Isn't setting up a 2nf account a bit of a hassel as you need local access to the AC units and perhaps even a 2nd phone when setting it up?

**Comment by mstendah** [comment]
Same issue here. The app works, but not HA, using the same account.

**Comment by nguyenanh87** [comment]
After one day cannot access, ít's working now.
I don't know the issues on server side or client side.
I've tried a few step:
1. Change password
2. Login on Comfort Cloud app on Android device
3. Delete intergrate on HA
4. Reconfig intergrate

It's working now.

**Comment by Auka84** [comment]
> After one day cannot access, ít's working now. I don't know the issues on server side or client side. I've tried a few step:
> 
> 1. Change password
> 2. Login on Comfort Cloud app on Android device
> 3. Delete intergrate on HA
> 4. Reconfig intergrate
> 
> It's working now.

So you advice to delete and reinstall the integration? Right now it's deactivated at my side. I don't know if i just reactivate the integration,if it'll work

![Capture d’écran 2023-12-12 à 07 59 57](https://github.com/sockless-coding/panasonic_cc/assets/86434173/d48bdb76-bb66-4fb3-941c-946ee134262e)

**Comment by mstendah** [comment]
> After one day cannot access, ít's working now. I don't know the issues on server side or client side. I've tried a few step:
> 
> 1. Change password
> 2. Login on Comfort Cloud app on Android device
> 3. Delete intergrate on HA
> 4. Reconfig intergrate
> 
> It's working now.

I tried deleting the integration but now I am unable to add it back
![IMG_0582](https://github.com/sockless-coding/panasonic_cc/assets/19377422/a16a3695-6913-456b-8e7e-399b8488ae36)

**Comment by Auka84** [comment]
I took the risk to reactivate it. And it works for me

**Comment by mkz212** [comment]
@Auka84 Does the plug work or the application for iphone / android?

**Comment by Auka84** [comment]
@mkz212 yep it works on my iPhone and now it’s back on my HA

**Comment by pfrock42** [comment]
My HA has started working again overnight. I didn't change anything or reboot anything

All yesterday the Panasonic CC App (on iOS) worked fine.

The only strange thing is that since mid-yesterday I get a "Failed to Unload" on the HA Integrations page. I guess a reboot might clear that (will try later).

**Comment by mstendah** [comment]
> My HA has started working again overnight. I didn't change anything or reboot anything
> 
> All yesterday the Panasonic CC App (on iOS) worked fine.
> 
> The only strange thing is that since mid-yesterday I get a "Failed to Unload" on the HA Integrations page. I guess a reboot might clear that (will try later).

Odd, mine still not working and as I deleted it, now I cannot even get it installed again.

**Comment by mstendah** [comment]
This is the error I get in the logs when trying to add the integration back and log in using my Panasonic Comfort Cloud account. Any thoughts anyone?

This error originated from a custom integration.

Logger: custom_components.panasonic_cc.config_flow
Source: custom_components/panasonic_cc/config_flow.py:60
Integration: Panasonic Comfort Cloud (documentation, issues)
First occurred: 09:03:51 (7 occurrences)
Last logged: 10:55:16

Unexpected error creating device
Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/config_flow.py", line 60, in _create_device
    devices = await self.hass.async_add_executor_job(api.get_devices)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 207, in get_devices
    self.login()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 106, in login
    self._create_token()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 164, in _create_token
    raise ResponseError(response.status_code, response.text)
custom_components.panasonic_cc.pcomfortcloud.session.ResponseError: Invalid response, status code: 500 - Data: {"code":5001,"message":"DB system error due to db system"}

**Comment by mkz212** [comment]
Maybe give me more details? What version (1.19.0?)? Any logs? What country are you from? You have to find some common point - why does one work and the other does not...

**Comment by mstendah** [comment]
> Maybe give me more details? What version (1.19.0?)? Any logs? What country are you from? You have to find some common point - why does one work and the other does not...

Happy to provide all that is needed. What version so you refer to? It fails when adding the latest version available off the Comfort Cloud integration. The log showing the error was in the message just above this one. All HA components are on the latest version available. I am located in Finland. And the Panasonic iOS app works with the same account that I try to use in HA. This has worked fine until 1 or 2 days ago.

**Comment by mkz212** [comment]
They blocked my account again for 24 hours due to incorrect login attempts. 😓

**Comment by ozreplicator** [comment]
Mine is all up and running again, but rather than remain at the mercy of Panasonic's unreliable cloud service, I've decided to go down the local control path. I've just ordered all the bits to build the espthings.io replacement for the Panasonic wifi module over the holidays. I'll sell the old CZ-TACG1 modules on Gumtree later :-)

**Comment by Auka84** [comment]
Is it easy to change de wifi module ?

i see my 6AC devices on my local network but impossible to reach it without the cloud of Panasonic.

**Comment by ozreplicator** [comment]
I wouldn't say it's easy, but looks straightforward enough if you have reasonable soldering skills.

As far as I'm aware the Panasonic modules will only talk to Panasonic's cloud servers via https, no local control possible.

**Comment by codyc1515** [comment]
Fixed by https://github.com/sockless-coding/panasonic_cc/commit/3570551f68a6aa74e240557b4436045494520af1. Please close the issue.
