### ISSUE TITLE
Spurious spike in Current Power chart

### ISSUE THREAD

**Issue by smoothquark** [sockless-coding/panasonic_cc#148]
I have only recently installed HA and this integration. Thank you for the integration. I have been looking at the power usage chart for the last few days and have attached the latest one. At midnight, there is a large spike, which I think indicates the total for the previous day. Not sure if the integration is causing this or a bug within Home Assistant. I wonder if anyone else has been seeing the same?

![Conservatory-Panasonic-Current-Power-2023-12-11](https://github.com/sockless-coding/panasonic_cc/assets/7754917/c35f0ece-dd1f-406a-b3e2-88f1130101c4)

**Comment by sockless-coding** [comment]
Wrong time zone was used, should be fixed in later version

**Comment by MironJajtic** [comment]
Hi,

I have noticed the same problem in the last 2-3 weeks. A few unusually high 15-minute spikes in "Current Power" while the AC is off (07:30 on - 20:00 off):
![image](https://github.com/user-attachments/assets/a65ae8d1-1f02-44f8-a87e-63df65850748)

And here is the daily power consumption, which measures the consumption for everything in that room (including the air conditioner):
![image](https://github.com/user-attachments/assets/67d5a5fb-ecaf-4f38-b86e-1b35420d4486)

**Comment by smoothquark** [comment]
I have had my unit turned off over summer (we generally use it for heating only) and shall have another look when I turn it back on. The "spike" when I last checked, did seem to correspond to the total consumption of the previous day. I think it is a Home Assistant bug as I occasionally get the same issue with the consumption for my EV charger. I don't think it is in the Panasonic integration / API itself.

**Comment by MironJajtic** [comment]
@sockless-coding energy graph looks fine, no increase after ~20:10 until next day around 8:00

![image](https://github.com/user-attachments/assets/2425abeb-6ab2-4ffc-a38a-37f09c096443)

**Comment by ladislashd** [comment]
I have the same issue :
![image](https://github.com/user-attachments/assets/ca2af935-7510-4263-b36f-81ed31361744)
While the daily energy  doesn't show this trouble.

I have 2 other AC that show the same kind of unrealistic value at random time during the day, form example for the last 3 day :
![image](https://github.com/user-attachments/assets/07384974-4f2b-43aa-a84b-474750cc2ae3)
A 9 000 Btu AC can't consume > 25 kw of power

**Comment by Edmund-Wong-01** [comment]
Hello, I've noticed that i have a similar problem to this

![Image](https://github.com/user-attachments/assets/08169cf9-7ff9-483f-806b-7bb4e78a0c44)
