### ISSUE TITLE
Anti-frost signal

### ISSUE THREAD

**Issue by vdende** [sockless-coding/panasonic_cc#149]
During the winter when the temperature drops to +/- 2 degrees or lower, the AC unit sometimes needs a period (+/- 15 min) to perform some sort of anti-frost process. During the process the AC heating unit is not working (disabled), thus the temperature drops very fast in the room.

During that process the AC its led keeps flashing. Is there a way to capture this process/signal in HA? I would like to know when it's busy with this anti-frost process to automate other climate tasks in the house.

**Comment by sockless-coding** [comment]
@vdende unfortunately, Panasonic does not expose this information in the API.
I'm not even sure they send this info to their servers... they don't even include info about hardware errors in the API. Or if the device is actively heating/cooling.

**Comment by vdende** [comment]
That's a bummer, but thanks for checking @sockless-coding

**Comment by wvergouwenavular** [comment]
That's really a shame, I was wondering the same thing. There is no way to detect if the AC is defrosting or if the power consumption is just high atm...
