### ISSUE TITLE
digits decimals float

### ISSUE THREAD

**Issue by Nordicfastware** [sockless-coding/panasonic_cc#15]
Hi, upon adding the integration and placing the daily energy usage into lovelace, I can see there are lot more digits than necessary (float error).
See below:

![image](https://user-images.githubusercontent.com/58825251/95747901-778a1600-0c99-11eb-80f4-02bc239ebb32.png)

**Comment by sockless-coding** [comment]
This should be fixed in v1.0.19

**Comment by Nordicfastware** [comment]
Confirmed that this was now fixed.
