### ISSUE TITLE
No contact 

### ISSUE THREAD

**Issue by Solsind** [sockless-coding/panasonic_cc#151]
This morning, my unit was not connected to home assistant, with the message "configuration not succeeded" Is there a problem or.? It works perfect on the panasonic app

**Comment by amirandola** [comment]
There's 3 topic about this problem ...

**Comment by Solsind** [comment]
It worked 10 hours ago, so i could not find new topics, but great if there is fokus on the problem. Thanks

**Comment by amirandola** [comment]
It seems that Panasonic has activated a security key that it did not control before ... the author of the post is seeing if he can generate a valid key. See https://github.com/sockless-coding/panasonic_cc/issues/147

**Comment by massitate** [comment]
Anche a me da questa mattina non si riesce più a controllare da Home assistant " configurazione non riuscita " e dall'app funziona benissimo. Se qualcuno riesce a fare qualcosa sarei grato.

**Comment by codyc1515** [comment]
I believe this should be resolved now. Can you please check?
