### ISSUE TITLE
Entities not available

### ISSUE THREAD

**Issue by Teammie73** [sockless-coding/panasonic_cc#153]
Hi,

Since 3 days my air conditioner entitles are not available. 
I tried to reload but without success. I can login and logout in the app.

Log entry attached.

Any advice ?
![IMG_2518](https://github.com/sockless-coding/panasonic_cc/assets/134190368/21662e82-0914-4db8-9390-8716713b2213)
![IMG_2519](https://github.com/sockless-coding/panasonic_cc/assets/134190368/33208509-fd2f-4cd7-b1fd-3800f0d8afef)

**Comment by glazeddonut** [comment]
I have the same issue

**Comment by Teammie73** [comment]
For me today all entities are working again . Strange .

**Comment by codyc1515** [comment]
Were you trying to reload the integration? If you can reproduce the issue, please Enable debug logging.

![image](https://github.com/sockless-coding/panasonic_cc/assets/50791984/48a3321b-39fd-4d54-9ef6-3ff8fac70f48)
