### ISSUE TITLE
Energy Sensor - total

### ISSUE THREAD

**Issue by KennethEgholm** [sockless-coding/panasonic_cc#157]
Is there an option to have the energy sensor counting incrementally - so that it can be used in the Energy dashboard?
If not, could it be an option to have it reset every day / running total - or just have two sensors for it?

Best, Kenneth Egholm

**Comment by codyc1515** [comment]
Sounds like an enhancement. Sorry, I cannot help as my heat pump does not have energy monitoring.

**Comment by sockless-coding** [comment]
@KennethEgholm the "Daily energy" sensor should work.
