### ISSUE TITLE
Panasonic temp sensor not updated

### ISSUE THREAD

**Issue by mstendah** [sockless-coding/panasonic_cc#158]
I get two indoor temp readings from this integration sensor.xxx and climate.xxx. The sensor entity has not updated its reading for 4 days now. The climate reading does get updated, however it is difficult to use as it is not looking listed as an entity, only available as a secondary information in th climate widget.

Why are there two different indoor temperatures? Why does one get updated but not the other? Is there a way to make the climate.xxx as the "primary" entity so that it can be used in automation?

![image](https://github.com/sockless-coding/panasonic_cc/assets/19377422/e8256560-d53c-4ba1-bc66-d8babe7e371f)

**Comment by codyc1515** [comment]
Can you please:

1. Reload your integration, or failing that, restart HA
2. Grab a screenshot from HA of both sensors
3. Grab a screenshot of the Panasonic CC app

Thank you

**Comment by sockless-coding** [comment]
@mstendah seems strange, they are pulling the same sensor data.
From what I can tell from the screenshot, you have the AC set to Summer House mode. It might an issue with the temperature/mode, since I haven't implemented the summer house mode in the integration.

**Comment by Auka84** [comment]
@mstendah  do you still have the issue ? I have the same but with all sensor. I have to reboot HA everyday to have sensors back in live :(

**Comment by mstendah** [comment]
No, I think it was resolved by one of the actions mentioned in this and some other thread, but did not make a note of which one.

However, the indoor temp sensor is not a good sensor to use for measuring. It goes up and down a lot when the unit is one. Impossible to use it for regulating something. Better to use a spearate one located more centrally in the room.
________________________________

**Comment by Auka84** [comment]
@mstendah i use versatile thermostat to have to ability to use another temp sensor

did you change something in the yaml to refresh the sensor so ?
