### ISSUE TITLE
Energy Sensor

### ISSUE THREAD

**Issue by patrikbloemer** [sockless-coding/panasonic_cc#162]
Just added this integration and cannot find the daily energy sensor...
I can see the energy consumption in my IOS app but it does not appear in the entity list.
Have one outside and two inside units. 
/Patrik

**Comment by sockless-coding** [comment]
@patrikbloemer, you need to enable the energy sensors in the device configuration.
If you believe this issue is still relevant, please feel free to reopen it or create a new one.
