### ISSUE TITLE
HA Core 2025.1 Deprecated Constant Changes Required

### ISSUE THREAD

**Issue by craibo** [sockless-coding/panasonic_cc#164]
Logger: homeassistant.components.climate.const
Source: helpers/deprecation.py:205
Integration: Climate (documentation, issues)
First occurred: 11:13:02 (12 occurrences)
Last logged: 11:13:10

HVAC_MODE_OFF was used from panasonic_cc, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.OFF instead, please create a bug report at https://github.com/sockless-coding/panasonic_cc/issues
SUPPORT_TARGET_TEMPERATURE was used from panasonic_cc, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE instead, please create a bug report at https://github.com/sockless-coding/panasonic_cc/issues
SUPPORT_FAN_MODE was used from panasonic_cc, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.FAN_MODE instead, please create a bug report at https://github.com/sockless-coding/panasonic_cc/issues
SUPPORT_SWING_MODE was used from panasonic_cc, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.SWING_MODE instead, please create a bug report at https://github.com/sockless-coding/panasonic_cc/issues
SUPPORT_PRESET_MODE was used from panasonic_cc, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.PRESET_MODE instead, please create a bug report at https://github.com/sockless-coding/panasonic_cc/issues

Logger: homeassistant.components.sensor
Source: helpers/deprecation.py:205
Integration: Sensor (documentation, issues)
First occurred: 11:13:05 (12 occurrences)
Last logged: 11:13:15

DEVICE_CLASS_ENERGY was used from panasonic_cc, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.ENERGY instead, please create a bug report at https://github.com/sockless-coding/panasonic_cc/issues
DEVICE_CLASS_POWER was used from panasonic_cc, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.POWER instead, please create a bug report at https://github.com/sockless-coding/panasonic_cc/issues
STATE_CLASS_TOTAL_INCREASING was used from panasonic_cc, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorStateClass.TOTAL_INCREASING instead, please create a bug report at https://github.com/sockless-coding/panasonic_cc/issues
STATE_CLASS_MEASUREMENT was used from panasonic_cc, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorStateClass.MEASUREMENT instead, please create a bug report at https://github.com/sockless-coding/panasonic_cc/issues

**Comment by aceindy** [comment]
Duplicate https://github.com/sockless-coding/panasonic_cc/issues/154#issue-2068726448
