### ISSUE TITLE
Is this integration abandoned?

### ISSUE THREAD

**Issue by codyc1515** [sockless-coding/panasonic_cc#174]
There appears to have been little to no updates in the past two months, despite a number of outstanding issues. PRs are also not being worked through.

**Comment by codyc1515** [comment]
Looks to be. I messaged the developer directly on the community forums 2 weeks ago and received no response. I will look to make a fork of this integration, with a view to getting it accepted into HA core.

**Comment by Auka84** [comment]
Hello @codyc1515  Do you have some news about this ?

It's really annoying to have no update since a while for this integration :(
I have to reboot my HA everyday to have all sensors back in life :( and got this error everyday in the log for exemple

> Logger: homeassistant.components.switch
> Source: helpers/entity_platform.py:894
> Integration: Commutateur ([documentation](https://www.home-assistant.io/integrations/switch), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+switch%22))
> First occurred: 06:01:33 (191 occurrences)
> Last logged: 07:36:33
> 
> Updating panasonic_cc switch took longer than the scheduled update interval 0:00:30

**Comment by sockless-coding** [comment]
This integration is not abandoned, I work on this integration on my spare time, which I have very little of at the moment.

**Comment by brunsy** [comment]
@sockless-coding Would you consider bringing on another maintainer to help out?

**Comment by codyc1515** [comment]
> @sockless-coding Would you consider bringing on another maintainer to help out?

As above. I already asked that two weeks and got no response.

**Comment by craibo** [comment]
Hey @sockless-coding 

Thank you for your work on this so far. With your time constrains, I'm in the same boat here, would you please consider adding @codyc1515 as a code owner allowing him to review & merge PRs and create releases.

If not, @codyc1515 would you consider forking this project and applying your changes and the bug fixes in a new repo with release and we can switch to use this repo in HACS? 

I am more then happy to help maintain the project as I use this integration fairly extensively.

Thank you both

**Comment by craibo** [comment]
FYI @codyc1515 I would avoid getting this accepted into HA Core. It makes the changes and release process alot slower and more complicated. 
Based on their guidelines you will also need @sockless-coding permission to do this too.

**Comment by danielcherubini** [comment]
@craibo @codyc1515 I see you both have forks that are active. What's the plan here? Should we centralize onto a single fork?

**Comment by brunsy** [comment]
It would be best if @sockless-coding brought on another maintainer, so everything can stay in one spot.

@sockless-coding You mentioned the repo isn't abandoned but there are a lot of issues in it's current state that have fixes pending review/merge. Would you consider bringing on either myself (or I'm sure @craibo or @codyc1515 would volunteer) to help manage/review/test these PRs?

@sockless-coding it's fine not having the time to review/merge any maintenance PRs but what's worse is there has been no response about the future of this going forwards and the community has been left in limbo. Unfortunately it doesn't leave much other choice except to fork.

**Comment by danielcherubini** [comment]
@brunsy This is why I think that having a centralised fork is good, it allows the community to move forward, and when it's ready, it also makes it easier for @sockless-coding to merge and move forward.
