### ISSUE TITLE
Sensors not updated

### ISSUE THREAD

**Issue by Auka84** [sockless-coding/panasonic_cc#175]
Hello

> Core
> 2024.1.5
> Supervisor
> 2024.01.1
> Operating System
> 11.4
> Interface utilisateur
> 20240104.0

I have 6 AC unit but every day, all sensors seems to be blocked

in the log i have this error message

```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:858
Integration: Capteur ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 5 février 2024 à 16:15:46 (2028 occurrences)
Last logged: 09:09:26

Updating panasonic_cc sensor took longer than the scheduled update interval 0:00:30
```

For exemple this one updated 17 hours ago

![Capture d’écran 2024-02-06 à 09 12 01](https://github.com/sockless-coding/panasonic_cc/assets/86434173/228a1dbf-a886-4d34-b69e-aafb29f40383)

If I reboot HA, all sensors are back but only for few time :(

**Comment by sockless-coding** [comment]
This issue has been inactive for a while, so we’re closing it for now. If you believe this issue is still relevant, please feel free to reopen it or create a new one.
