### ISSUE TITLE
class 'custom_components.panasonic_cc.climate.PanasonicClimateDevice'>) does not set ClimateEntityFeature.TURN_OFF but implements the turn_off method

### ISSUE THREAD

**Issue by perbog** [sockless-coding/panasonic_cc#178]
Logginformation (VARNING)
Logger: homeassistant.components.climate
Source: components/climate/__init__.py:354
Integration: Klimat ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 09:46:24 (3 occurrences)
Last logged: 09:46:24

Entity None (<class 'custom_components.panasonic_cc.climate.PanasonicClimateDevice'>) does not set ClimateEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/sockless-coding/panasonic_cc/issues
Entity None (<class 'custom_components.panasonic_cc.climate.PanasonicClimateDevice'>) does not set ClimateEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/sockless-coding/panasonic_cc/issues
Entity None (<class 'custom_components.panasonic_cc.climate.PanasonicClimateDevice'>) implements HVACMode(s): off, heat, cool, heat_cool, dry, fan_only and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/sockless-coding/panasonic_cc/issues

**Comment by craibo** [comment]
Hi @sockless-coding 

I've raised a pull request [186](https://github.com/sockless-coding/panasonic_cc/pull/186) to update the integration and resolve multiple of the bugs raised by HA Core updates.

Would you mind merging this PR and create a release version 2024.5.0?

I have tested these changes and confirmed they are working. I have not come across any issues so far. 

Anyone else is welcome to test them on the [Fork](https://github.com/craibo/panasonic_cc). Any issues please raise them and tag me I'll be happy to take a look.

Thank you
