### ISSUE TITLE
HA - Helper deprecation

### ISSUE THREAD

**Issue by OleBinders** [sockless-coding/panasonic_cc#185]
Home Assistant gave me the following error message today: 

Logger: homeassistant.components.climate.const
Source: helpers/deprecation.py:206
integration: climate (documentation, issues)
First occurred: 17:17:33 (10 occurrences)
Last logged: 17:17:33

HVAC_MODE_OFF was used from panasonic_cc, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.OFF instead, please report it to the author of the 'panasonic_cc' custom integration
SUPPORT_TARGET_TEMPERATURE was used from panasonic_cc, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE instead, please report it to the author of the 'panasonic_cc' custom integration
SUPPORT_FAN_MODE was used from panasonic_cc, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.FAN_MODE instead, please report it to the author of the 'panasonic_cc' custom integration
SUPPORT_SWING_MODE was used from panasonic_cc, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.SWING_MODE instead, please report it to the author of the 'panasonic_cc' custom integration
SUPPORT_PRESET_MODE was used from panasonic_cc, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.PRESET_MODE instead, please report it to the author of the 'panasonic_cc' custom integration

**Comment by stolk88** [comment]
Dear @sockless-coding ,

My (w)life depends on this 😂😊
Could you please look into it before I get absolutely ass-kicked by my household...

**Comment by craibo** [comment]
Hey @stolk88 , @OleBinders 

I've raised a [PR](https://github.com/sockless-coding/panasonic_cc/pull/186)] to resolve these issue. I unfrotunately cannot merge the PR though.

While we wait for @sockless-coding to merge the PR you can use the [fork](https://github.com/craibo/panasonic_cc)
