### ISSUE TITLE
Energy sensor

### ISSUE THREAD

**Issue by svlkent** [sockless-coding/panasonic_cc#19]
Hello! I dont get the energy consumption to show, I have toggled "Enable daily energy sensor" and restarted HA
What am I doing wrong?
In the Panasonic app I can see power consumption per day
It also looks that if I´m logged in with HA i cant login in the app. It loooks like only one user can be logged in at same time?

**Comment by sockless-coding** [comment]
Hi @svlkent ,
Does the sensor show up in HA? There is a delay before it will show a value.
I haven't used the panasonic app in a while, but it used to work if you had two different user account one for HA and one for the app.
