### ISSUE TITLE
Be aware of...

### ISSUE THREAD

**Issue by danielbergholm** [sockless-coding/panasonic_cc#190]
Logger: homeassistant.components.climate.const
Källa: helpers/deprecation.py:197
integration: Klimat (dokumentation, ärenden)
Inträffade först: 21:06:37 (12 händelser)
Senast loggade: 21:06:46

HVAC_MODE_OFF was used from panasonic_cc, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.OFF instead, please report it to the author of the 'panasonic_cc' custom integration
SUPPORT_TARGET_TEMPERATURE was used from panasonic_cc, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE instead, please report it to the author of the 'panasonic_cc' custom integration
SUPPORT_FAN_MODE was used from panasonic_cc, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.FAN_MODE instead, please report it to the author of the 'panasonic_cc' custom integration
SUPPORT_SWING_MODE was used from panasonic_cc, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.SWING_MODE instead, please report it to the author of the 'panasonic_cc' custom integration
SUPPORT_PRESET_MODE was used from panasonic_cc, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.PRESET_MODE instead, please report it to the author of the 'panasonic_cc' custom integration

**Comment by codyc1515** [comment]
I believe this is resolved in the latest update.

**Comment by danielcherubini** [comment]
Yes it was

**Comment by sockless-coding** [comment]
Fixed
