### ISSUE TITLE
Connection failed

### ISSUE THREAD

**Issue by MagnusHass** [sockless-coding/panasonic_cc#193]
Logger: homeassistant.config_entries
Source: config_entries.py:402
First occurred: 20:53:10 (2 occurrences)
Last logged: 21:12:12

Error setting up entry for panasonic_cc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/__init__.py", line 79, in async_setup_entry
    devices = await hass.async_add_executor_job(api.get_devices)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 207, in get_devices
    self.login()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 106, in login
    self._create_token()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 164, in _create_token
    raise ResponseError(response.status_code, response.text)
custom_components.panasonic_cc.pcomfortcloud.session.ResponseError: Invalid response, status code: 403 - Data: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: BcpyzN8oqYvqoHo-2L5sXW49-oRDBtXhjx6etR2sMkCrFlbifoz-tw==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>

**Comment by mkz212** [comment]
See #191

**Comment by connornz** [comment]
Following. I have the same. 
Looks like Panasonic enabled 2FA and could have broken the plugin.

**Comment by marcel-st** [comment]
same here, can't connect anymore. Logged in to the panasonic app and saw they renewed stuff.

**Comment by Pieter1979** [comment]
same here. Can not connect anymore. Changed mailadres/pwd/... always same message: Unexpected error creating device.

**Comment by biffen747** [comment]
Same. Logged into the app and had to set 2FA. Still not working with HA. Worked fine yesterday.

**Comment by benniju** [comment]
I have the same issue..

**Comment by syepes** [comment]
This happen just some months ago :-(
Let's just hope they stop changing the API

**Comment by kellyatkinson** [comment]
For everyone who is only here to say "me too" and hope for a solution - please go subscribe to issue #191 where the magic is happening now. There is no need to comment to say "I have this problem too". You can subscribe to the Github issue and be notified when there are any changes.

@MagnusHass can you please close this issue as it is a duplicate?
