### ISSUE TITLE
Panasonic - Unexpected error creating device.

### ISSUE THREAD

**Issue by GigiTax** [sockless-coding/panasonic_cc#195]
Hi,
I tried to reconnect my AC to homeassistant but iI received this error: Unexpected error creating device.

Does anyone have idea how to solve this problem?

luigi

**Comment by Faceless3882** [comment]
This is a duplicate report see earlier logged issue. It's a known problem and actively being worked on.

**Comment by GigiTax** [comment]
> This is a duplicate report see earlier logged issue. It's a known problem and actively being worked on.

Ok. sorry

thanks

gigi

**Comment by codyc1515** [comment]
Duplicate of #194

**Comment by kellyatkinson** [comment]
@GigiTax can you please mark this issue as closed so the community can focus on fixes? Cheers!

**Comment by sockless-coding** [comment]
Duplicate / fixed
