### ISSUE TITLE
Exposing built-in Summerhouse mode

### ISSUE THREAD

**Issue by gllmlbrt** [sockless-coding/panasonic_cc#20]
Hi, 
Thank you for this great integration.
I have a unit CS-HZ25UKE, which has a "summer house mode". This essentially allows to have low temperature maintained  in summerhouses to avoid mold/frost during the winter.

There are two summer house mode selected under "device list":

"+8-15°C HEAT" allows to choose any target temperature between + 8 and +15°C. Forces fan mode automatically as "HIGH".
"+8 or 10°C HEAT"  allows to choose any target temperature between + 8 or+10°C. Forces fan mode automatically as "HIGH".
I do no know the point of the second one, and the first one is the only one that makes sense.
See Screenshots of the app attached.

_Would it be possible to expose this mode as part of the integration and have it available as an operation mode?_

Note: It is possible to "imitate" this by calling the services "climate.set_temperature" to 8 and "climate.set_hvac_mode" to "heat" and climate.set_fan_mode to "high" which is what I do as part of an automation when temperature inside get too low.

![Screenshot_20201221-092918_Comfort Cloud](https://user-images.githubusercontent.com/58825251/102756281-e9ed3580-436f-11eb-9195-172126bf4707.jpg)
![Screenshot_20201221-092910_Comfort Cloud](https://user-images.githubusercontent.com/58825251/102756283-eb1e6280-436f-11eb-8502-4bd41b8e673c.jpg)
![Screenshot_20201221-093050_Comfort Cloud](https://user-images.githubusercontent.com/58825251/102756285-eb1e6280-436f-11eb-92c3-99f6ce83b055.jpg)

**Comment by sockless-coding** [comment]
@Nordicfastware Hi, the summer house mode does not seem to be a real "mode" instead triggered by setting the temperature below 16C. There was a similar request for this on the library I'm using for the ha-component, https://github.com/lostfields/python-panasonic-comfort-cloud/issues/19

**Comment by Nordicfastware** [comment]
Ok noted thanks. granted that it can be triggered with service calls, but it would have been neat. Nice to have instead of must have indeed.

**Comment by blaatunge** [comment]
I have the same request :) 
Panasonic is located in my summer house.
Even so it's not a need to have it would be nice to have - to save some money.

If the "mode" is triggered by the temperature - could you change the GUI to allow setting the temperature as low as 8C?

**Comment by mstendah** [comment]
Yes, same issue and request. Could it be as easy as allowing temp settings all the way down to 8C?

**Comment by sockless-coding** [comment]
Included in v1.0.49
