### ISSUE TITLE
Cannot set horizontal swing mode and swing mode

### ISSUE THREAD

**Issue by Tiger2205** [sockless-coding/panasonic_cc#200]
Hi. Sice the great approvement on sigging due to the panasonic changes. I cannot change both swingmodes anymore. Can this be an issue on the mode changes? I can change fan mode. 

Error: 

` Logger: homeassistant.helpers.script.websocket_api_script
Source: helpers/script.py:526
First occurred: 19:17:40 (12 occurrences)
Last logged: 19:28:48

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'coroutine' object is not subscriptable `

on the:

` device(
  File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 154, in set_device
    if device and device['parameters']['airSwingHorizontal'].value == -1:
                  ~~~~~~^^^^^^^^^^^^^^
TypeError: 'coroutine' object is not subscriptable `

Does anyone else has this issue instead?

**Comment by Tiger2205** [comment]
Just to inform more I was trying to set them to Auto. And horizontals was Mid and other mode was Up

**Comment by sockless-coding** [comment]
There is a new version that should solve this issue

**Comment by Tiger2205** [comment]
Ticket can be closed

**Comment by Tiger2205** [comment]
Closed
