### ISSUE TITLE
Appbrain Scraping isn't 100% reliable.

### ISSUE THREAD

**Issue by danielcherubini** [sockless-coding/panasonic_cc#209]
https://www.appbrain.com/app/panasonic-comfort-cloud/com.panasonic.ACCsmart
Shows 1.20.0

Where as right now it's 1.21.0 in the app store.  My guess is appbrain refreshes daily, and as such it missed the daily update. It will be fine tomorrow.

This likely isn't something we can fix specifically. But it's good to know, so if anyone has a better idea

**Comment by heldchen** [comment]
the good thing is: keys still work, so only new logins are affected.

**Comment by mkz212** [comment]
> the good thing is: keys still work for now, so only new logins are affected (and possibly refreshing keys)

I changed the version to 1.21.0 and it logs in correctly (get token etc.). It has the same values hardcoded as 1.20.0.

**Comment by danielcherubini** [comment]
> the good thing is: keys still work for now, so only new logins are affected (and possibly refreshing keys)

Correct, which is kind of expected. So worst case right now is some people will be unable to login for <24h, everytime panasonic releases a new app version.

My other solution to this was to publish this version to a gist, and use that. The publishing mechanism can scrape more frequently with some fallbacks, so it's a bit more reliant, and we are also not scraping from everywhere, alerting the webpages we're scraping.

However the reason appbrain was chosen, was it has a meta tag, with the app version in it. So it's assumed that it will be pretty stable to scrape.

**Comment by amirandola** [comment]
https://apkpure.com/it/panasonic-comfort-cloud/com.panasonic.ACCsmart
It already report 1.21.0 and I think that can be parsed

**Comment by sockless-coding** [comment]
Panasonic usually keeps the previous version valid for 3-4weeks, the integrations also have a 3-day refresh interval.
So if it's not polling the latest version instantly, it should be an issue.

**Comment by mkz212** [comment]
> > the good thing is: keys still work for now, so only new logins are affected (and possibly refreshing keys)
> 
> Correct, which is kind of expected. So worst case right now is some people will be unable to login for <24h, everytime panasonic releases a new app version.
> 
> My other solution to this was to publish this version to a gist, and use that. The publishing mechanism can scrape more frequently with some fallbacks, so it's a bit more reliant, and we are also not scraping from everywhere, alerting the webpages we're scraping.
> 
> However the reason appbrain was chosen, was it has a meta tag, with the app version in it. So it's assumed that it will be pretty stable to scrape.

Both 1.20.0 and 1.21.0 work. You don't think Panasonic assumes that everyone updates applications on the first day, do you?

**Comment by danielcherubini** [comment]
> Panasonic usually keeps the previous version valid for 3-4weeks, the integrations also have a 3-day refresh interval. So if it's not polling the latest version instantly, it should be an issue.

Then we're safe here.

**Comment by heldchen** [comment]
> > > the good thing is: keys still work for now, so only new logins are affected (and possibly refreshing keys)
> > 
> > 
> > Correct, which is kind of expected. So worst case right now is some people will be unable to login for <24h, everytime panasonic releases a new app version.
> > My other solution to this was to publish this version to a gist, and use that. The publishing mechanism can scrape more frequently with some fallbacks, so it's a bit more reliant, and we are also not scraping from everywhere, alerting the webpages we're scraping.
> > However the reason appbrain was chosen, was it has a meta tag, with the app version in it. So it's assumed that it will be pretty stable to scrape.
> 
> Both 1.20.0 and 1.21.0 work. You don't think Panasonic assumes that everyone updates applications on the first day, do you?

they actually do force you. when you run an old version a popup is shown that says you need to update to continue.

**Comment by mkz212** [comment]
> > > > the good thing is: keys still work for now, so only new logins are affected (and possibly refreshing keys)
> > > 
> > > 
> > > Correct, which is kind of expected. So worst case right now is some people will be unable to login for <24h, everytime panasonic releases a new app version.
> > > My other solution to this was to publish this version to a gist, and use that. The publishing mechanism can scrape more frequently with some fallbacks, so it's a bit more reliant, and we are also not scraping from everywhere, alerting the webpages we're scraping.
> > > However the reason appbrain was chosen, was it has a meta tag, with the app version in it. So it's assumed that it will be pretty stable to scrape.
> > 
> > 
> > Both 1.20.0 and 1.21.0 work. You don't think Panasonic assumes that everyone updates applications on the first day, do you?
> 
> they actually do force you. when you run an old version a popup is shown that says you need to update to continue.

I've never seen anything like this on iOS. But I guess he doesn't do it right away? Only after a few days?

**Comment by heldchen** [comment]
yes only after some days.

**Comment by danielcherubini** [comment]
> yes only after some days.

if it's more than the number of days that appbrain takes to update (which it is), then we're fine

**Comment by heldchen** [comment]
@danielcherubini you could scrape it from the app store directly:

```
$ curl --silent https://play.google.com/store/apps/details?id=com.panasonic.ACCsmart | grep -oP '\["\d.\d+.\d+"\]'
["1.21.0"]
```

**Comment by sockless-coding** [comment]
I switched to play store version detection and added version info to the device info in HA
![image](https://github.com/sockless-coding/panasonic_cc/assets/25462432/999f4a6d-d565-4cd5-ad22-1701f89a220c)
I also added a button to force refresh the app version

**Comment by heldchen** [comment]
nice!
