### ISSUE TITLE
Wrong value - Fan mode is not Fan mode?

### ISSUE THREAD

**Issue by mkz212** [sockless-coding/panasonic_cc#214]
In custom_components/panasonic_cc/pcomfortcloud/constants.py:

```
class OperationMode(Enum):
    Auto = 0
    Dry = 1
    Cool = 2
    Heat = 3
    Fan = 4
```

But i think that 4 is for Fan OR Nanoe Stand Alone mode ! (And maybe also for iAutoX.)

When parameters.lastSettingMode = 1 -> Fan Mode
When parameters.lastSettingMode = 2 -> Nanoe Stand Alone Mode (mode like heat, cool, etc, not additional function!)

I checked and it really reads it that way. But for some reason server does not take value lastSettingMode.

Maybe someone can check how looks request from app when Nanoe Stand Alone or Fan Mode is setting up?

https://www.panasonic.com/global/hvac/products/comfort-cloud/how-to-use-comfort-cloud/choose-air-conditioner-operation-mode.html

**Comment by mkz212** [comment]
@heldchen If you still have this whole setup to check how the queries from the application look, could you check how Nanoe Stand Alone Mode (mode, not function!) is set And Fan Mode?

**Comment by heldchen** [comment]
this depends on the AC model. one of my ac f.e. has no fan_only mode (in the app, but can still be set to fan_only successfully in HA). so I am not sure what exactly you're looking for.

**Comment by mkz212** [comment]
I dont have button to enable Fan but as you can see it is active when I turn it on from HomeKit. 

![IMG_6220](https://github.com/sockless-coding/panasonic_cc/assets/82271669/f30dd988-0436-40a5-889f-e14e1f378468)

And here is Nanoe Stan Alone Mode:

![IMG_6220](https://github.com/sockless-coding/panasonic_cc/assets/82271669/ce5bcbed-3b26-4fe8-8e21-91892e44d191)

**Comment by heldchen** [comment]
afaik the nanoex mode corresponds to `fan_only` (your 2nd screenshot). I have the same:
![image](https://github.com/sockless-coding/panasonic_cc/assets/299636/8153c942-8b14-444a-9f18-8b441712fa61)

for another model that I have, it looks similar but has no dedicated fan mode buttons: 
![image](https://github.com/sockless-coding/panasonic_cc/assets/299636/71a327d8-0824-452d-b867-e1edc3ec4bb5)

**Comment by mkz212** [comment]
@heldchen 

Responses:

Fan Mode:
params.operationMode = 4
parameters.lastSettingMode = 1

Nanoe Stand Alone Mode:
params.operationMode = 4
parameters.lastSettingMode = 2

But i cannot set value for lastSettingMode. 

See link in my first post. Manual from Panasonic. Fan mode it is not Nanoe Stand Alone mode.

**Comment by heldchen** [comment]
```{
  "deviceGuid": "CZ-RTC6BLW+8C53E60346A2",
  "parameters": {
    "fanSpeed": 5,
    "operationMode": 5
  }
}```

**Comment by mkz212** [comment]
> ```
> {
>   "deviceGuid": "CZ-RTC6BLW+8C5<REDACTED>",
>   "parameters": {
>     "fanSpeed": 5,
>     "operationMode": 5
>   }
> }
> ```

Oh Thaks! 👍 I was just about to try other values for operationMode.

**Comment by heldchen** [comment]
lastSettingMode is not something that these devices seem to support, it's only shown in the get-groups call:
```
{
  "uiFlg": false,
  "groupCount": 1,
  "groupList": [
    {
      "groupId": 1<REDACTED>,
      "groupName": "My House",
      "pairingList": [],
      "deviceList": [
        {
          "deviceGuid": "CS-Z25ZKEW+E06<REDACTED>",
          "deviceType": "3",
          "deviceName": "Schlafzimmer",
          "permission": 3,
          "temperatureUnit": 0,
          "summerHouse": 0,
          "nanoeStandAlone": true,
          "autoMode": true,
          "modeAvlList": {
            "autoMode": 1
          },
          "parameters": {
            "operate": 0,
            "operationMode": 2,
            "temperatureSet": 20,
            "fanSpeed": 0,
            "fanAutoMode": 1,
            "airSwingLR": 0,
            "airSwingUD": 0,
            "ecoFunctionData": 0,
            "ecoMode": 2,
            "ecoNavi": 0,
            "nanoe": 2,
            "iAuto": 0,
            "airDirection": 0,
            "lastSettingMode": 0
          },
          "deviceModuleNumber": "CS-Z25ZKEW",
          "deviceHashGuid": "26e<REDACTED>",
          "modelVersion": 2,
          "coordinableFlg": true,
          "pairedFlg": false
        },
        {
          "deviceGuid": "CZ-RTC6BLW+8C5<REDACTED>",
          "deviceType": "5",
          "deviceName": "Essen",
          "permission": 3,
          "temperatureUnit": 0,
          "summerHouse": 0,
          "nanoeStandAlone": true,
          "autoMode": true,
          "modeAvlList": {
            "autoMode": 1
          },
          "parameters": {
            "operate": 1,
            "operationMode": 2,
            "temperatureSet": 20,
            "fanSpeed": 3,
            "fanAutoMode": 1,
            "airSwingLR": 2,
            "airSwingUD": 0,
            "ecoFunctionData": 0,
            "ecoMode": 0,
            "ecoNavi": 0,
            "nanoe": 2,
            "iAuto": 0,
            "airDirection": 1,
            "lastSettingMode": 0
          },
          "deviceModuleNumber": "S-50PY3E",
          "deviceHashGuid": "fa4<REDACTED>"
        }
      ]
    }
  ]
}
```

**Comment by mkz212** [comment]
To set Fan mode:
operationMode = 4

To read Fan mode:
operationMode = 4 AND lastSettingMode =1

To set Nanoe Stand Alone Mode:
operationMode = 5 
To read Nanoe Stand Alone mode:
operationMode = 4 AND lastSettingMode = 2

Confirmed and working! Thank you!

**Comment by sockless-coding** [comment]
I've added better feature support checks in v1.1.0 so only the relevant modes should be available.
