### ISSUE TITLE
Unexpected error creating device.

### ISSUE THREAD

**Issue by clarencegi** [sockless-coding/panasonic_cc#216]
Hi,

For a few months now, my Panasonic Comfort Cloud integration has stopped working. I have uninstalled and reinstalled it, but it still doesn't work. While registering the device, it gives the "Unexpected error creating device." message.

What could be the problem?

The app on my phone works properly.

Thanks in advance.

Kind regards,

**Comment by heldchen** [comment]
you need to update to the latest version 1.0.45 or higher.

**Comment by clarencegi** [comment]
I'm with 1.0.45 running HA 2024.4.0

**Comment by heldchen** [comment]
did you logout & login in the mobile Panasonic Comfort Cloud app before reporting the error here? if not, do that and recheck. if yes, enable debug log, reload the integration and post logs here.

**Comment by clarencegi** [comment]
Ok, working now after forcing several attemps... Mysterious....

**Comment by clarencegi** [comment]
> e integration and post logs here.

Yes Already Loged in In App.
I have forced login several times and one worked 🤷‍♂️🤷‍♂️

**Comment by clarencegi** [comment]
Thanks for answering and for help Thomas. 👍

**Comment by heldchen** [comment]
@clarencegi please close this issue when your problem is solved.
