### ISSUE TITLE
Login page not shown

### ISSUE THREAD

**Issue by claus-lind** [sockless-coding/panasonic_cc#22]
I Have installed  Panasonic Comfort Cloud integration using HACS. on a Rasp Pi4 running Home Assistant.
I cant find the login to Comfort Cloud.
In the box under HACS with the  Panasonic Comfort Cloud, in the right lower corner there is 3 dots. Is this where the login is ? I only have "Information,update information ...."

Best regards Claus

**Comment by claus-lind** [comment]
![image](https://user-images.githubusercontent.com/55362188/103320364-5681c780-4a35-11eb-92c8-fb3267883693.png)

**Comment by claus-lind** [comment]
Here a screen shot.

**Comment by sockless-coding** [comment]
@claus-lind After you installed the components through HACS you need to go to Home Assistant Configuration - Integrations add/activate it there.

**Comment by claus-lind** [comment]
Super, thanks I found it .. (new to Home assistant)
