### ISSUE TITLE
Inital Setp Failed to renew token

### ISSUE THREAD

**Issue by DonBlock** [sockless-coding/panasonic_cc#220]
Hi everyone,

I'm new to Home Assistant, transitioning from IOBroker, and I'm excited to be here! Most of my devices have integrated smoothly with the panasonic_cc integration. Most of them are of the same type, and except for one device, they are working like a charm.

However, I'm having trouble with one specific device out of the group of same devices.

The integration found the device and created everything like the other devices. However, it doesn't display any values except for the firmware version. Within the system log, I keep encountering the following error:

vbnet
Copy code
This error originated from a custom integration.

Logger: custom_components.panasonic_cc.panasonic
Source: custom_components/panasonic_cc/panasonic.py:79
integration: Panasonic Comfort Cloud (documentation, issues)
First occurred: 12:17:12 PM (18 occurrences)
Last logged: 12:34:13 PM

Failed to renew token for device af0ca7acf02190262001f2ec8a8523d779c6d0084788ea207f3ac8526650a6eb, giving up for now

Has anyone experienced a similar issue or can offer some guidance on how to resolve this? Any help would be greatly appreciated!

Thank you in advance!

Best,

Dennis

**Comment by DonBlock** [comment]
Debug logging is enabled, to be honest I'm not sure if it's saved somewhere else. Nothing addition within the log section of HA.

**Comment by heldchen** [comment]
retry the setup after you enabled the debug log, and when you encounter the issue, click on "disable debugging log" - you will get then the detailed log as a download and can upload it here (remove any unrelated entries & redact any sensitive data)

**Comment by DonBlock** [comment]
[Panasonic_cc_debug_log_extract.txt](https://github.com/user-attachments/files/15988103/Panasonic_cc_debug_log_extract.txt)
Attached you'll find the logfile.
The Device MTZ16WKE is the one which does not show any vaules within HA. 
From the Logfile itself, it seems that the integration is capable of receiving data like the temperature.

Any ideas?

Thank you very much for your support.

**Comment by heldchen** [comment]
that is odd - you get successfully data for `/deviceStatus/` but at the same time get a `Failed to renew token for device` error. it looks like the token refresh succeded, but then `self._api.get_device(self.id)` fails with a masked exception when the response is parsed. 

![image](https://github.com/sockless-coding/panasonic_cc/assets/299636/6b77679d-a5d0-4bad-bb47-9e6a3aacf16e)

@sockless-coding I think 2 things need to be done:
- explicitly check for an invalid / expired token on all api calls. panasonic has dedicated response codes for these cases. this way we avoid refreshing the token when any other unrelated exception is happening
- in the case of a non-token based exception in self._api.get_device(), this should be reported in the logger

**Comment by sockless-coding** [comment]
@DonBlock it's the Left/Right swing mode that is causing the issue. What do you have it set to in the App?

**Comment by DonBlock** [comment]
Hi,

I‘m not where to find this Option.
Swing is set Auto in the App.
Can‘t any left right options in the app.

Fan Speed is Auto or Quiet. There are in more additional settings.

**Comment by sockless-coding** [comment]
@DonBlock v1.0.49 should work and only log a warning about invalid horizontal swing mode

**Comment by DonBlock** [comment]
Hi,

Thank so much, it‘s working like a charm.
