### ISSUE TITLE
Inside Temperature wrong since last Update 

### ISSUE THREAD

**Issue by TomF79** [sockless-coding/panasonic_cc#223]
Since the last update i have seen that the inside temperature shows 32 degrees instead of 23 degrees.

Anyone can confirm this?

**Comment by sockless-coding** [comment]
@TomF79 enable debug logging for the integration and then look for the update status request the entry should look something like this:
```
[custom_components.panasonic_cc.pcomfortcloud.panasonicsession] GET url: https://accsmart.panasonic.com/deviceStatus/<device id>, response: {"timestamp":1719514171464,"permission":2,"summerHouse":2,"iAutoX":false,"nanoe":true,"nanoeStandAlone":true,"autoMode":true,"heatMode":true,"fanMode":true,"dryMode":true,"coolMode":true,"ecoNavi":false,"powerfulMode":true,"quietMode":true,"airSwingLR":true,"autoSwingUD":false,"ecoFunction":0,"temperatureUnit":0,"modeAvlList":{"autoMode":1},"nanoeList":{"visualizationShow":0},"clothesDrying":false,"insideCleaning":false,"fireplace":false,"pairedFlg":false,"parameters":{"ecoFunctionData":0,"insideCleaning":0,"fireplace":0,"lastSettingMode":0,"operate":1,"operationMode":2,"temperatureSet":20,"fanSpeed":0,"fanAutoMode":1,"airSwingLR":5,"airSwingUD":3,"ecoMode":0,"ecoNavi":0,"nanoe":1,"iAuto":0,"airDirection":0,"insideTemperature":19,"outTemperature":25,"airQuality":0},"deviceNanoe":1}
```

**Comment by TomF79** [comment]
> @TomF79 enable debug logging for the integration and then look for the update status request the entry should look something like this:
> 
> ```
> [custom_components.panasonic_cc.pcomfortcloud.panasonicsession] GET url: https://accsmart.panasonic.com/deviceStatus/<device id>, response: {"timestamp":1719514171464,"permission":2,"summerHouse":2,"iAutoX":false,"nanoe":true,"nanoeStandAlone":true,"autoMode":true,"heatMode":true,"fanMode":true,"dryMode":true,"coolMode":true,"ecoNavi":false,"powerfulMode":true,"quietMode":true,"airSwingLR":true,"autoSwingUD":false,"ecoFunction":0,"temperatureUnit":0,"modeAvlList":{"autoMode":1},"nanoeList":{"visualizationShow":0},"clothesDrying":false,"insideCleaning":false,"fireplace":false,"pairedFlg":false,"parameters":{"ecoFunctionData":0,"insideCleaning":0,"fireplace":0,"lastSettingMode":0,"operate":1,"operationMode":2,"temperatureSet":20,"fanSpeed":0,"fanAutoMode":1,"airSwingLR":5,"airSwingUD":3,"ecoMode":0,"ecoNavi":0,"nanoe":1,"iAuto":0,"airDirection":0,"insideTemperature":19,"outTemperature":25,"airQuality":0},"deviceNanoe":1}
> ```

Please can you tell me where i can find the update Status request?

**Comment by sockless-coding** [comment]
Go to the integration and enable debug logging:
![image](https://github.com/sockless-coding/panasonic_cc/assets/25462432/258d2e52-136d-40ad-b15f-a263892125b7)

Then go to `<your ha url>/config/logs` and click load full logs

**Comment by TomF79** [comment]
> Go to the integration and enable debug logging: ![image](https://private-user-images.githubusercontent.com/25462432/343921136-258d2e52-136d-40ad-b15f-a263892125b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1MTU5NjcsIm5iZiI6MTcxOTUxNTY2NywicGF0aCI6Ii8yNTQ2MjQzMi8zNDM5MjExMzYtMjU4ZDJlNTItMTM2ZC00MGFkLWIxNWYtYTI2Mzg5MjEyNWI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDE5MTQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyMTY3YTdhMTA0OGRjZWM2YjFjNjZmNzAyYjI1NWZiYmQxZTI1Mzc4ZThjNWQzZDlkNDJhMTIwMDVhZGQ1MmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tTvYZ62ECiHg_0ZbikJ3Ddjw4fhU6SZpfuZBqrWXXKY)
> 
> Then go to `<your ha url>/config/logs` and click load full logs

Here you are
[home-assistant_panasonic_cc_2024-06-27T19-13-55.372Z.log](https://github.com/user-attachments/files/16020133/home-assistant_panasonic_cc_2024-06-27T19-13-55.372Z.log)

**Comment by TomF79** [comment]
[home-assistant_2024-06-27T19-13-05.251Z.log](https://github.com/user-attachments/files/16020144/home-assistant_2024-06-27T19-13-05.251Z.log)

**Comment by sockless-coding** [comment]
Ah, you have one of the devices where there isn't an outside sensor, but the outside sensor is used for the inside temperature.
This will be fixed in the next release

**Comment by TomF79** [comment]
Fine, thanks for your fast support

**Comment by sockless-coding** [comment]
v1.0.49 should fix the issue

**Comment by TomF79** [comment]
> v1.0.49 should fix the issue

I have update to v1.049 and now the outside temperature is not available and the inside temperature shows the actually outdoor temperature.

**Comment by sbuchbauer** [comment]
The integration is really great, thank you for providing it.
I have Nanoe but cant set it, it is always reset to off. 
Also the inside temperature shows the outside and outside is not available

**Comment by TomF79** [comment]
> The integration is really great, thank you for providing it. I have Nanoe but cant set it, it is always reset to off. Also the inside temperature shows the outside and outside is not available 1.049 installed

Same here

**Comment by sockless-coding** [comment]
There is a bug regarding Nanoe, I'll fix that.
Regarding the indoor sensor, it's strange... The log @TomF79 provided the indoor sensor was missing.
Under the Device Info does it say Firmware: 1.21.0 or 1.20.0 ?

**Comment by sbuchbauer** [comment]
I use firmware 1.21

**Comment by TomF79** [comment]
> There is a bug regarding Nanoe, I'll fix that. Regarding the indoor sensor, it's strange... The log @TomF79 provided the indoor sensor was missing. Under the Device Info does it say Firmware: 1.21.0 or 1.20.0 ?

Also Firmware 1.21.0

it is possible that the indoor Sensor is missing on my Modell because the Panasonic App also dont show the indoor temperature

**Comment by sockless-coding** [comment]
If the indoor doesn't show up in the app then it's not there / working

**Comment by TomF79** [comment]
> If the indoor doesn't show up in the app then it's not there / working

I understand but since update to 1.049 the outdoor temperature is shown as indoor temperature sensor and outdoor temperature sensor is not available.

a few Updates before all two Sensors shows differently temperatures

**Comment by TomF79** [comment]
![Uploading Bildschirmfoto 2024-06-28 um 20.36.32.jpeg.png…]()

**Comment by sockless-coding** [comment]
Removed the swapping of sensors in v1.0.50

**Comment by Nerestro21** [comment]
Hey, since the 2024.9 release I have an issue with wrong inside temperatures as well. It either seems to not update the values or jump to strange values occasionally. However, if I open the app and refresh, it seems to show the correct value in the app and then the integration also gets it updated. 

Before, the integration always got the right values on its own.

**Comment by sockless-coding** [comment]
@Nerestro21 this is probably related to the https://github.com/sockless-coding/panasonic_cc/issues/310 issue.
