### ISSUE TITLE
NanoeX not work after last update

### ISSUE THREAD

**Issue by mrgiov** [sockless-coding/panasonic_cc#225]
After last update, the nanoeX switch remain always OFF, also when i force status to ON

https://github.com/sockless-coding/panasonic_cc/assets/22102934/3174a8ad-9257-454e-bbda-d6f6b96e3bc7

**Comment by sbuchbauer** [comment]
Same here with 1.049

**Comment by sockless-coding** [comment]
Should be fixed in v1.0.50
