### ISSUE TITLE
With latest 1.0.49 update, the Eco preset stopped working

### ISSUE THREAD

**Issue by thewan056** [sockless-coding/panasonic_cc#226]
After updating to 1.0.49, the eco preset stopped working. After selecting the Eco preset, it always goes back to None.

Reverting back to 1.0.48 fixes this.
<img width="413" alt="comfortcloud" src="https://github.com/sockless-coding/panasonic_cc/assets/24851051/9f204720-21cd-4ba4-8600-2ef00b97dc57">

Also, as others reported, the Nanoe switch also stopped working for me in this update. Reverting to 1.0.48 also fixes this.

Note: For my AC model, selecting the Eco preset activates "Quiet" mode, not Eco (or Eco Navi) mode. Also the Turbo preset does nothing and goes back to None, which I don't really use. I really like this quiet mode, more so than Eco Navi so I hope this gets fixed.

**Comment by pdm1976** [comment]
You beat me to it. I just posted my own issue #227 . Sorry for the duplicate.

**Comment by thecalstan** [comment]
I’m seeing the same behaviour after updating earlier today

**Comment by sockless-coding** [comment]
Yes, I managed to break the presets when I added the +8/15. It will be fixed shortly

**Comment by sockless-coding** [comment]
Should be fixed in v1.0.50

**Comment by thewan056** [comment]
I can confirmed that Eco (Quiet mode in my case) is fixed. I can't test turbo as it doesn't work on my unit

**Comment by thecalstan** [comment]
Both presets are now working for me on 1.50.

Thanks for sorting @sockless-coding
