### ISSUE TITLE
Unexpected error creating device

### ISSUE THREAD

**Issue by crypet** [sockless-coding/panasonic_cc#235]
Hi!

I had an power outage tonight and when Home Assistant booted back up, the Panasonic CC integration was not working anymore.
I updated the integration to the latest version (1.0.54) but still couldn't get it working. So I deleted it and tried setting it up again, but when logging in I get 'Unexpected error creating device'.

Any idea what the issue may be?

Below are the logs from HA:

This error originated from a custom integration.

Logger: custom_components.panasonic_cc.config_flow
Source: custom_components/panasonic_cc/config_flow.py:59
integration: Panasonic Comfort Cloud (documentation, issues)
First occurred: 20:29:43 (2 occurrences)
Last logged: 20:37:19

Bad logger message: Unexpected error creating device ((ResponseError('(get_groups: Expected status code 200, received: 400: <bound method ClientResponse.text of <ClientResponse(https://accsmart.panasonic.com/device/group) [400 Bad Request]>\n<CIMultiDictProxy(\'Content-Type\': \'application/json\', \'Content-Length\': \'88\', \'Connection\': \'keep-alive\', \'Date\': \'Sat, 29 Jun 2024 18:29:43 GMT\', \'x-amzn-RequestId\': \'908e41d2-0117-499d-a6f3-a931e1743174\', \'x-amzn-ErrorType\': \'BadRequestException\', \'x-amz-apigw-id\': \'aJHXtFmAtjMEZrA=\', \'X-Cache\': \'Error from cloudfront\', \'Via\': \'1.1 bb6a0f1bce11879ae1e2d813e7419fd6.cloudfront.net (CloudFront)\', \'X-Amz-Cf-Pop\': \'HEL51-P4\', \'Alt-Svc\': \'h3=":443"; ma=86400\', \'X-Amz-Cf-Id\': \'aVOgSzMJDEELDOA605CW4YZxvLOALU0fFNAVdDpbT875HgIzjAF0vw==\', \'X-XSS-Protection\': \'1; report=1;mode=block\', \'X-Frame-Options\': \'DENY\', \'Content-Security-Policy\': "script-src \'self\' \'unsafe-inline\'", \'X-Content-Type-Options\': \'nosniff\', \'Strict-Transport-Security\': \'max-age=31536000; includeSubDomains\')>\n>'),))
Bad logger message: Unexpected error creating device ((ResponseError('(get_groups: Expected status code 200, received: 400: <bound method ClientResponse.text of <ClientResponse(https://accsmart.panasonic.com/device/group) [400 Bad Request]>\n<CIMultiDictProxy(\'Content-Type\': \'application/json\', \'Content-Length\': \'88\', \'Connection\': \'keep-alive\', \'Date\': \'Sat, 29 Jun 2024 18:37:19 GMT\', \'x-amzn-RequestId\': \'4c52cd63-d4f9-4ae8-92b5-2ab2a167a3e2\', \'x-amzn-ErrorType\': \'BadRequestException\', \'x-amz-apigw-id\': \'aJIfAH2TNjMEHQQ=\', \'X-Cache\': \'Error from cloudfront\', \'Via\': \'1.1 1ebf52f5e79648444025879af65610d2.cloudfront.net (CloudFront)\', \'X-Amz-Cf-Pop\': \'CPH50-C1\', \'Alt-Svc\': \'h3=":443"; ma=86400\', \'X-Amz-Cf-Id\': \'B7vb7_61kofuFJqF_rOWTYgQ14HICztc3xU1737nL-E2AxiGbeSV5A==\', \'X-XSS-Protection\': \'1; report=1;mode=block\', \'X-Frame-Options\': \'DENY\', \'Content-Security-Policy\': "script-src \'self\' \'unsafe-inline\'", \'X-Content-Type-Options\': \'nosniff\', \'Strict-Transport-Security\': \'max-age=31536000; includeSubDomains\')>\n>'),))

**Comment by sockless-coding** [comment]
Enable debug logging, there might be something with the authentication

**Comment by RKO** [comment]
I think I have the same error. I enabled debug logging before deleting the integration and luckily saved the error log file:
`2024-06-28 21:36:25.129 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry  for panasonic_cc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/__init__.py", line 73, in async_setup_entry
    await api.start_session()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 30, in start_session
    await super().start_session()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/panasonicsession.py", line 52, in start_session
    await self._authentication.authenticate(self._username, self._password)
  File "/config/custom_components/panasonic_cc/pcomfortcloud/panasonicauthentication.py", line 70, in authenticate
    await self._retrieve_client_acc()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/panasonicauthentication.py", line 241, in _retrieve_client_acc
    headers = await PanasonicRequestHeader.get(self._settings, self._app_version, include_client_id= False),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/panasonicrequestheader.py", line 20, in get
    "X-APP-VERSION": await app_version.get(),
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/ccappversion.py", line 16, in get
    await self._update()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/ccappversion.py", line 33, in _update
    _LOGGER.debug(f"Failed to retrive app version using version {self._appVersion}")`

**Comment by sockless-coding** [comment]
@RKO you need to update the integration

**Comment by crypet** [comment]
I tried to enable debug loggning by adding this to configuration.yaml:

`logger:
  default: info
  logs:
    custom_components.panasonic_cc: debug`

But when reviewing the logs I only find these entries after attempting to login to the integration:

`2024-06-29 21:12:25.945 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicsession] Starting Session
2024-06-29 21:12:25.956 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicsettings] Loaded settings from '/root/.panasonic-settings'`

So debug logging should be enabled?

**Comment by sockless-coding** [comment]
@crypet Yes, you have enabled debug logging

**Comment by crypet** [comment]
@sockless-coding Okay, then there is nothing else logged. It works fine when logging in to the Panasonic CC app so my credentials are valid. Any other idea?

@RKO Did you get it working?

**Comment by RKO** [comment]
> @sockless-coding Okay, then there is nothing else logged. It works fine when logging in to the Panasonic CC app so my credentials are valid. Any other idea?
> 
> @RKO Did you get it working?

Yes. I had forgotten that it was through HACKS. I just went in there, selected Update Information, and then all the updates showed up. After updating and restarting, I was able to add the integration again.

**Comment by sockless-coding** [comment]
@crypet try v1.0.55 it has more logging and a bunch of fixes

**Comment by crypet** [comment]
After installing v1.0.55 I can login so it works again. :) Thanks for your help!
