### ISSUE TITLE
New app again

### ISSUE THREAD

**Issue by wdflorczyk** [sockless-coding/panasonic_cc#25]
Hi i think that problem came back. I'm not sure if it's fixed in library.

![Screenshot_20210121-091248_Home Assistant](https://user-images.githubusercontent.com/61596455/105322815-a7ff1b80-5bc9-11eb-8e15-34b813cbb054.jpg)

WF

**Comment by Nordicfastware** [comment]
I have the same issue.

**Comment by martinwahlstrom** [comment]
Temporary workaround is, as proposed by omnix1 in https://github.com/sockless-coding/panasonic_cc/issues/17#issuecomment-721825190, to manually edit manifest.json as a new version of pcomfortcloud is now available. 
Worked for me.

**Comment by weaselchops** [comment]
> Temporary workaround is, as proposed by omnix1 in [#17 (comment)](https://github.com/sockless-coding/panasonic_cc/issues/17#issuecomment-721825190), to manually edit manifest.json as a new version of pcomfortcloud is now available.
> Worked for me.

Yep, increased to to ".20" problem solved..for now 👍 
Thanks

**Comment by wdflorczyk** [comment]
Yes, 0.0.20 works. Great! I hope Panasonic has done recently some changes because of new models and won't change anything for a year at least :).

**Comment by hemaris-8b** [comment]
0.0.20 worked for me as well. Thanks!

**Comment by sockless-coding** [comment]
I've released v1.0.24 to address this issue
