### ISSUE TITLE
Cant add service

### ISSUE THREAD

**Issue by gldrenthe89** [sockless-coding/panasonic_cc#251]
Cant add the service integration. After entering ID and Password it gives an error.

Bad logger message: Unexpected error creating device ((ResponseError('(get_token: Expected status code 200, received: 400: {"error":"invalid_request","error_description":"Missing required parameter: code"}'),))

It looks like the the intregration doesn't support MFA. MFA is forced upon new accounts at Panasonic it seems. I cant create one without one.

**Comment by sockless-coding** [comment]
@gldrenthe89 you need to set up an account that has MFA enabled, but I recommend that you use the SMS version for now.

**Comment by gldrenthe89** [comment]
> @gldrenthe89 you need to set up an account that has MFA enabled, but I recommend that you use the SMS version for now.

I dont get a pop-up in home assistant to put the code in. Hence the error

**Comment by gldrenthe89** [comment]
i have reset MFA completely and only added SMS and i whas able to add it
thank you
