### ISSUE TITLE
Failed to setup again after 2024.7.1 update

### ISSUE THREAD

**Issue by Agent6-6-6** [sockless-coding/panasonic_cc#253]
After update to 2024.7.1 is the integration also not working for anyone. Tried all the usual things from when it failed a few weeks ago (re-downloading, reauthenticating, deleting and re-adding) and there was the big effort to get it working again.

Will try post logs next time I'm on laptop.

**Comment by DIMtriad** [comment]
Same here, update to 2024.7.x seems to break the integration. Reverted back to 2024.6.4 - working again.

**Comment by sockless-coding** [comment]
I never tried 2024.7.1 but 2024.7.2 works but gives a warning (that I will fix)

**Comment by Agent6-6-6** [comment]
I managed to fix it with a complete reboot of the HA VM, rather than just a reload from the UI.
