### ISSUE TITLE
Sleep Mode

### ISSUE THREAD

**Issue by muhlba91** [sockless-coding/panasonic_cc#255]
Hi,

we recently got our aircon and when integrating it with HA, I realized that the aurcon also supports a sleep mode. Sleep mode is different to quiet/eco mode as it‘s increasing the temperature over a set period of time (adjustable to some point) by a few degrees to adjust for the human body‘s temperature change during sleep.

Is it possible to integrate sleep mode in this integration?

**Comment by sockless-coding** [comment]
Hi,
Depends on how it works, I haven't seen anything that resembles sleep mode in the feature list they provide... but Panasonic isn't always using logical names...
I need to know what your device reports as features, and what happens when you activate sleep mode in the app.

**Comment by muhlba91** [comment]
this is the interesting part though. the app itself doesn't offer a setting like that; it's only to be set in through the remote. it works in addition to the mode you have set.
is there any debug logging i can enable and then set the through the remote which might show some useful information if panasonic sends this preset to their backend?

**Comment by sockless-coding** [comment]
@muhlba91 you could enable debug logging, that will log the raw api responses. But if it's only on the remote, it's probably some built in curve, you could probably create an automation in HA that does the same thing.

**Comment by heldchen** [comment]
@muhlba91 unfortunately there are quite a few HVAC modes & options that are not controllable through the API, but exists via IR remotes or bluetooth. it's quite a shame that in 2024 "api first" is not yet the standard way of implementing things for Panasonic.
