### ISSUE TITLE
This will stop working in Home Assistant 2025.1

### ISSUE THREAD

**Issue by Testingfor101** [sockless-coding/panasonic_cc#258]
Hello,

Just noticed this log entry, have not seen this issue registered.

"Detected code that calls async_forward_entry_setup for integration panasonic_cc with title: and entry_id: _removed_, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue."

**Comment by sockless-coding** [comment]
Hello, 
This is handled in the new v1.1.0
