### ISSUE TITLE
Outdoor temperature sensor frequency

### ISSUE THREAD

**Issue by redvipert** [sockless-coding/panasonic_cc#26]
Super happy with this code, works great in Home Assistant with my Panasonic Airconditioning. 

I am using the outdoor sensor, but it seems to check only once per 30 minutes:
<img width="302" alt="30min" src="https://user-images.githubusercontent.com/22964278/107344980-61fbf000-6ac3-11eb-8291-34ccb2af64c2.PNG">

This results in value = unknown most of the time.

I enabled the force option of course. Is there any way to increase frequency?

**Comment by sockless-coding** [comment]
@redvipert glad you like the integration.
There is no way to change the update interval as far as I know it's up to the device to report the information to the Panasonic servers.
I have a HZ25UKE and it updates the outside sensor every minute...
![image](https://user-images.githubusercontent.com/25462432/107417244-a912d100-6b15-11eb-92ed-849cfe7e8c0c.png)
