### ISSUE TITLE
API error since 1.1.0 and 1.1.1

### ISSUE THREAD

**Issue by Moustik2002** [sockless-coding/panasonic_cc#261]
Hello,

Cannot activate integration, i receive this error :

Echec de la configuration, nouvel essai: Invalid response from API: (get_device: Expected status code 200, received: 500: {"code":5005,"message":"Adapter Communication error"}

With Panasonic IOS app :

![image](https://github.com/user-attachments/assets/69f77c07-f711-4b1e-b040-fd9551a3b5e4)

**Comment by sockless-coding** [comment]
Hello,
Sounds like the HVAC lost internet connection, try power cycling it.

**Comment by Moustik2002** [comment]
I've done the power cycling this morning but still no way to connect to it.

**Comment by jack3308** [comment]
> Well, the issue is with your device not being able to connect to the Panasonic servers. Try resetting the wifi settings on the device / switching wifi channel on your router/ap.

I'm experiencing this exact problem and there are no problems reaching the server. The control within the actual Panasonic Comfort-Cloud app work just fine and they always go to the server. The devices are showing as online and functional everywhere except for the integration. Not trying to argue, just trying to emphasize that there doesn't appear to be any problem with server connection.

**Comment by Moustik2002** [comment]
I feel stupid but the root of the issue was my ISP router Freebox Ultra. At some point i've decided to try a reboot and instantely goes back in business. I spent whole afternoon to try through panasonic confort cloud to get my AC working. Speaking of that panasonic Remote control is crap i've killed the Wireless button with my tries (fortunately i've another one and they are not bound to split).
