### ISSUE TITLE
Preset Modes not working, Swing Mode: Auto gives error 400.

### ISSUE THREAD

**Issue by mvanrooijenjr** [sockless-coding/panasonic_cc#267]
Hiya! Since the new update I cannot use preset modes.

In the default thermostat, if I set the preset from none to either eco or boost it just sets it back to none after a few seconds.

Nothing the error logs.

Swing vertical Mode: Auto gives me an error 400.

![image](https://github.com/user-attachments/assets/c0e851ae-b512-4585-89c2-f708b96e90b9)

**Comment by mvanrooijenjr** [comment]
Same goes for Swing Mode horizontal: Auto - also gives an error 400 bad request.

**Comment by mvanrooijenjr** [comment]
Here's my climate state.

Looks like Auto for both Swing should be an accepted form.
Also looks like the preset modes should be called correctly.

Neither seems to work. Preset mode without error. Swing modes (Hori and Verti) give bad request.

`hvac_modes:
  - "off"
  - heat_cool
  - cool
  - dry
  - fan_only
  - heat
min_temp: 16
max_temp: 30
target_temp_step: 0.5
fan_modes:
  - Auto
  - Low
  - LowMid
  - Mid
  - HighMid
  - High
preset_modes:
  - none
  - eco
  - boost
swing_modes:
  - Auto
  - Up
  - UpMid
  - Mid
  - DownMid
  - Down
  - Swing
current_temperature: 20
temperature: 22.5
fan_mode: Auto
hvac_action: idle
preset_mode: none
swing_mode: Up
friendly_name: "Bedroom  Bedroom "
supported_features: 441`

**Comment by sockless-coding** [comment]
Hello, I've fixed the issues in v1.1.5 there were some invalid data included when activating auto swing. 
And the preset didn't call apply :)

**Comment by mvanrooijenjr** [comment]
Awesome! Squashing bugs left and right!

**Comment by mvanrooijenjr** [comment]
Tested and working now, thanks man!
