### ISSUE TITLE
Temperature "hangs"

### ISSUE THREAD

**Issue by jkaberg** [sockless-coding/panasonic_cc#27]
I noticed this more frequently over the last weeks. The temperature just suddenly stops to update, both indoor and outdoor temp. Anyone else noticed that?

From the HASS docker logs I notice this:

`2021-02-14 20:14:07 WARNING (MainThread) [homeassistant.components.switch] Updating panasonic_cc switch took longer than the scheduled update interval 0:00:30`

However I've noticed these when it's working aswell....

The comfort cloud app reports new temperature as it changes, so there must be something else? Restarting HASS fixes it for a while

**Comment by sockless-coding** [comment]
Hi @jkaberg, 
That warning is triggered if HA doesn't get a reply from Panasonic servers in less than 30s. 
The server its contacting is `accsmart.panasonic.com` (Hosted on Amazon AWS) and it's usually quite stable, I haven't noticed any outages myself.
Tho, the temperature system can be a bit iffy if you are using both the app and HA. For some reason Panasonic doesn't like to report the temperature to multiple "devices".

**Comment by jkaberg** [comment]
@sockless-coding I usualy don't use the APP, only this time to check if it's the service or HASS/integration. 

I'll investigate and see if I can pin point this

**Comment by hemaris-8b** [comment]
I have this issue with outdoor temp since yesterday.

**Comment by jkaberg** [comment]
It happend to me aswell again recently. And while I haven't confirmed it yet, I suspect PCC to be rate limiting (or even blocking) API calls

@sockless-coding any easy way to spit out http code when fetching updates?

**Comment by sockless-coding** [comment]
@jkaberg I've been running some test, and it doesn't seem to be any rate limiting the error I've logged when this happened was "502 Bad Gateway". So its more likely a server issue on their side, I've added some better handling of this error in v1.0.25

When it comes to updates, all information except the energy data is fetched from the same call (every 60s).
