### ISSUE TITLE
Entity names are wrong with fresh install

### ISSUE THREAD

**Issue by Ricks88** [sockless-coding/panasonic_cc#271]
Hello,

I decided to do a re-installation of Panasonic integration, but now the names show wrong.
It was "panasonic vloermodel" when i add it now it says "panasonic vloedmodel panasonic vloermodel" changing the name to for example "panasonic vloermodel bijmaker" makes "panasonic vloermodel bijkamer panasonic vloermodel".

**Comment by sockless-coding** [comment]
Hello,
Yes, the thermostat gets "name" "name"... I will change it, so the thermostat doesn't use the name of the device.

**Comment by sockless-coding** [comment]
#274 should fix the issue

**Comment by sockless-coding** [comment]
It's active in v1.1.7
