### ISSUE TITLE
Update interval takes longer then expected

### ISSUE THREAD

**Issue by sygys** [sockless-coding/panasonic_cc#28]
I get this message. In just a few days this message is given 4700 times. im not really sure how big of a deal this is but the integration is requesting to many updates i guess...

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:602
Integration: Sensor (documentation, issues)
First occurred: 9:38:41 (239 occurrences)
Last logged: 11:37:42

Updating panasonic_cc sensor took longer than the scheduled update interval 0:00:30

I would like it fixed if possible. This doesnt seem very good. Could this be the outside temperature sensor btw? That one is most of the time not working. (saying unavailable)

**Comment by sockless-coding** [comment]
@sygys, requesting updates every 30s should be fine. 
What hardware are you running HA on?
But I'll look if I can do something to improve the responsiveness and error handling of the outside temperature sensor.

**Comment by sygys** [comment]
Thank you for the fast reply. I'm not really sure if the outside temp sensor is the problem. But that is the only one failing from time to time. Is there a way to remove this sensor from the code in my instance. I don't really need it. And I'm afraid that my unit is not updating it because the cloud comfort app is also not giving the outside temp most of the time. Is there a way to get deeper log info on what fails?

**Comment by sockless-coding** [comment]
You can enable the debug log for this integration by adding `custom_components.panasonic_cc: debug` to the logger section. 
https://www.home-assistant.io/integrations/logger/
I'm logging some extra debug info in case updates fail.

**Comment by sockless-coding** [comment]
@sygys I've released a new version (v1.0.25) hopefully it will reduce the number of update failures.
