### ISSUE TITLE
Devices dissapeared after v1.1.9 update.

### ISSUE THREAD

**Issue by Filhgd** [sockless-coding/panasonic_cc#280]
Devices dissapeared after v1.1.9 update on HA. Unable to reinstall or find comfort cloud via the Home Assistant integration.

Core
2024.8.1
Supervisor
2024.08.0
Operating System
12.4
Frontend
20240809.0

**Comment by sockless-coding** [comment]
@Filhgd are there any error logs?

**Comment by Filhgd** [comment]
2024-08-12 14:32:51.450 ERROR (SyncWorker_0) [homeassistant.loader] Error parsing manifest.json file at /config/custom_components/panasonic_cc/manifest.json: Input is a zero-length, empty document: line 1 column 1 (char 0)

**Comment by sockless-coding** [comment]
Looks like your files are corrupted, redownload the integration using hacs or manually download the release package from [here](https://github.com/sockless-coding/panasonic_cc/releases/tag/v1.1.9)

**Comment by Filhgd** [comment]
@sockless-coding thank you. I had to do it manually. Automatic download via HA did not work. Now everything back connected 👍
