### ISSUE TITLE
hvac mode "auto" or "heat/cool" missing 

### ISSUE THREAD

**Issue by nickfabruada** [sockless-coding/panasonic_cc#281]
Hi, thanks for your great work with this addon.
after updating to v1.19, it seems the hvac mode heat/cool missing.
AC model CS-XU9XKQ.

**Comment by sockless-coding** [comment]
@nickfabruada does your device support auto mode? If it does the API might report it as missing, can you enable auto in the CFC app?
Enable debug logging and look for the entry that looks like `[custom_components.panasonic_cc.pcomfortcloud.panasonicsession] GET url: https://accsmart.panasonic.com/deviceStatus/...`

**Comment by nickfabruada** [comment]
@sockless-coding thanks for the response. Let me try as per your advice.
Yes, auto mode is supported. Correct me if I'm wrong, my understanding on my device is auto mode is same as iAutoX mode.
To provide more info, each time the device is powered-on either through remote control or mobile app, it always defaults to iAutoX mode, then on your CC app it appears as heat/cool mode.
I have an automation in HA where after 20 mins of heat/cool mode then change to cool mode on 24C.
In addition, I restored my HA backup with CC app 1.0.58. I can see the heat/cool mode. see screenshot.

![Screenshot 2024-08-12 223721](https://github.com/user-attachments/assets/6d543dc1-ee39-468c-8889-aed64ecd08d8)

**Comment by nickfabruada** [comment]
> @nickfabruada does your device support auto mode? If it does the API might report it as missing, can you enable auto in the CFC app? Enable debug logging and look for the entry that looks like `[custom_components.panasonic_cc.pcomfortcloud.panasonicsession] GET url: https://accsmart.panasonic.com/deviceStatus/...`

@sockless-coding here's what I found.
2024-08-12 23:05:00.352 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicsession] GET url: https://accsmart.panasonic.com/deviceStatus/CS-XU9XKQ%2BE102302462, response: {"timestamp":1723493100239,"permission":3,"summerHouse":0,"iAutoX":true,"nanoe":true,"nanoeStandAlone":true,"autoMode":false,"heatMode":false,"fanMode":false,"dryMode":true,"coolMode":true,"ecoNavi":false,"powerfulMode":false,"quietMode":true,"airSwingLR":true,"autoSwingUD":true,"ecoFunction":1,"temperatureUnit":0,"modeAvlList":{"autoMode":1},"nanoeList":{"visualizationShow":0},"clothesDrying":false,"insideCleaning":false,"fireplace":false,"pairedFlg":false,"parameters":{"ecoFunctionData":1,"insideCleaning":0,"fireplace":0,"lastSettingMode":0,"operate":0,"operationMode":0,"temperatureSet":25,"fanSpeed":0,"fanAutoMode":0,"airSwingLR":2,"airSwingUD":2,"ecoMode":0,"ecoNavi":0,"nanoe":1,"iAuto":2,"airDirection":0,"insideTemperature":27,"outTemperature":28,"airQuality":0},"deviceNanoe":2}
2024

**Comment by sockless-coding** [comment]
I see, I'll change so Auto mode is available if iAutoX or autoMode is True

**Comment by sockless-coding** [comment]
@nickfabruada I looked at your device, it doesn't seem to support Auto or Heating mode. And iAutoX seem to be a cooling boost.
I'll expose the iAutoX as a switch instead.

**Comment by nickfabruada** [comment]
> @nickfabruada I looked at your device, it doesn't seem to support Auto or Heating mode. And iAutoX seem to be a cooling boost. I'll expose the iAutoX as a switch instead.

@sockless-coding it is best way to expose the iAutoX.  to match my device feature.

**Comment by sockless-coding** [comment]
The new iAuto-X is available in v1.1.10 I don't have that feature, so I can't test it my self

**Comment by nickfabruada** [comment]
Thanks for the update. let me test and let you know the result.

**Comment by nickfabruada** [comment]
Hi, here's my tests so far.
Thanks again for your great work and effort.
### 1. When device is turned On. iAutoX is the default mode.
**View from mobile app.**
![1723788863784](https://github.com/user-attachments/assets/78d58e84-c792-4131-972b-d8a11d31a43b)

**View from HA and device history.**
![1723788863767](https://github.com/user-attachments/assets/721c330b-3a85-416b-9a6f-4dc61674de6f)
![1723788863772](https://github.com/user-attachments/assets/b4dfba67-63b6-450a-804b-0aa641182c7b)

### 2. When mode changed from iAutoX to Cool.
**View from mobile app.**
![1723788863760](https://github.com/user-attachments/assets/9bb84087-2c1c-4329-8bdc-12967f14d9dc)

**View from HA and device history.**
![1723788863764](https://github.com/user-attachments/assets/4432bc17-e8d8-4ddf-91d3-58904030b686)
![Screenshot_2024-08-16-09-25-32-878_io homeassistant companion android](https://github.com/user-attachments/assets/fb3021b2-7f34-46b5-9055-2592d6d8d721)

### 3. Here is the full debugging log.
[home-assistant_panasonic_cc_2024-08-16T05-55-15.213Z.log](https://github.com/user-attachments/files/16634183/home-assistant_panasonic_cc_2024-08-16T05-55-15.213Z.log)

### 4. How to find the Quiet mode?
My device supports it as you can see in the mobile app screenshot.

**Comment by nickfabruada** [comment]
### iAutoX button test. Switching from Cool to iAutoX.
As per screenshot iAutoX is Off. When I toggled On, I get an error. Then the toggle switch will stay activated and does not do anything on the device.
![1723795973569](https://github.com/user-attachments/assets/3409f94d-58d0-4b91-bfe7-a814eb8d8af0)

![1723795973574](https://github.com/user-attachments/assets/6c6f6343-ecb0-4ffe-9029-32f56f5d2329)

Here's the debug log.
[home-assistant_panasonic_cc_2024-08-16T08-16-23.083Z.log](https://github.com/user-attachments/files/16634872/home-assistant_panasonic_cc_2024-08-16T08-16-23.083Z.log)

**Comment by sockless-coding** [comment]
Ok, looks like iAutoX is a combination of `operationMode` = 0 and `iAuto` = 2, I'll see how I can solve this... there are some limitations on Modes on the climate entity

**Comment by sockless-coding** [comment]
I've done some iAutoX changes in v1.1.11

**Comment by nickfabruada** [comment]
> I've done some iAutoX changes in v1.1.11

@sockless-coding to busy lately to test it out. I can confirm this version has fixed the iAutoX feature. Thank you!
