### ISSUE TITLE
Possibility to add icons for fan modes

### ISSUE THREAD

**Issue by ParalaX002** [sockless-coding/panasonic_cc#282]
Hi,

First of all, thanks a lot for the work on this add-on!

I was wondering if it was possible to add icons on the card for the different fan mode:
<img width="299" alt="image" src="https://github.com/user-attachments/assets/72df6bae-31e3-47ca-830d-c0e3984de763">
We could use fan speeds icons in mdi icons:
<img width="428" alt="image" src="https://github.com/user-attachments/assets/fccb5d40-335e-4f0a-ac03-0b608522b505">

Also, the preset "none" has no icon too:
<img width="143" alt="image" src="https://github.com/user-attachments/assets/cb05c9c1-ecee-4b45-92e8-0cdd5b91e074">
Maybe use something like "air-filter"?
<img width="143" alt="image" src="https://github.com/user-attachments/assets/3ee8973c-87d9-434d-aad2-424491f6ad3e">

**Comment by sockless-coding** [comment]
@ParalaX002 Hi, I've been looking at doing that, but the problem is that Material Design only contain Fan speed up to 3 and there are 5 speeds + Auto... I set it to outline A,1,2,3,4,5, so there is at least something
![image](https://github.com/user-attachments/assets/391c5303-55c7-45d4-9a2d-d01bb1dccbbb)

**Comment by ParalaX002** [comment]
Hi,

That's very nice :) I was thinking to use the fan-minus and fan-plus for low and high, and the number ones for the other level, but your solution is probably more visible :)

**Comment by ParalaX002** [comment]
Hi,

That's very nice :) I was thinking to use the fan-minus and fan-plus for low and high, and the number ones for the other level, but your solution is probably more visible :)
