### ISSUE TITLE
temporarily unavailable

### ISSUE THREAD

**Issue by asatron1** [sockless-coding/panasonic_cc#283]
Hi,

I have the problem that the air conditioning in Home Assistant is sporadically not accessible. where is the problem here?
After reloading the integration it can work again but not always - Restarting home assistant also works from time to time

I have the correct logs?
[log.txt](https://github.com/user-attachments/files/16600270/log.txt)

![image](https://github.com/user-attachments/assets/7627cc1e-417a-4493-960b-bed9242ae435)

![image](https://github.com/user-attachments/assets/49526f33-7509-4697-888a-4f0e43553778)

Regards

**Comment by sockless-coding** [comment]
@asatron1 Hi, you are getting the **5005 Adapter Communication error** that usually indicates that the HVAC has a bad internet/Wi-Fi connection.

**Comment by sugar012** [comment]
> @asatron1 Hi, you are getting the **5005 Adapter Communication error** that usually indicates that the HVAC has a bad internet/Wi-Fi connection.

Hello there. i get this error 200 times a day and using the integration is a hit or miss for 2 of my 3 splits that are connected to a different wifi. the thing is that they worked great for 2 years on and off but now, after recent updates, the are acting weird. for sure the wifi has not been touched .. what it could be?
PS sorry for reopening a closed thread

**Comment by sockless-coding** [comment]
@sugar012 I think this is a new error on Panasonic side, since the last API update I think they send some ping to the device when you request a status update. And if the device has a bad internet connection you get the 5005 error.

**Comment by sugar012** [comment]
here's the block that repeats over and over

`2024-09-09 12:48:01.811 WARNING (MainThread) [custom_components.panasonic_cc] Failed to setup device: letto (Invalid response from API: (get_device: Expected status code 200, received: 500: {"code":5005,"message":"Adapter Communication error"})
Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/coordinator.py", line 77, in _fetch_device_data
    self._device = await self._api_client.get_device(self._panasonic_device_info)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 125, in get_device
    json_response = await self.execute_get(self._get_device_status_url(device_info.guid), "get_device", 200)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/panasonicsession.py", line 144, in execute_get
    await check_response(response, function_description, expected_status_code)
  File "/config/custom_components/panasonic_cc/pcomfortcloud/helpers.py", line 32, in check_response
    raise exceptions.ResponseError(
custom_components.panasonic_cc.pcomfortcloud.exceptions.ResponseError: (get_device: Expected status code 200, received: 500: {"code":5005,"message":"Adapter Communication error"}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 271, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/coordinator.py", line 91, in _fetch_device_data
    raise UpdateFailed(f"Invalid response from API: {e}") from e
homeassistant.helpers.update_coordinator.UpdateFailed: Invalid response from API: (get_device: Expected status code 200, received: 500: {"code":5005,"message":"Adapter Communication error"}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/__init__.py", line 87, in async_setup_entry
    await device_coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 288, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady: Invalid response from API: (get_device: Expected status code 200, received: 500: {"code":5005,"message":"Adapter Communication error"}`

**Comment by mvanrooijenjr** [comment]
I am also getting since today, out of the blue on all my three devices. It seems to happen randomly. Has never happened before. No changes to my network.

**Comment by sockless-coding** [comment]
@mvanrooijenjr the 5005 error?
Unfortunately, that error originates on the Panasonic servers when they are trying to access the devices, the problem of Cloud only control.
Only thing you can do is checking your WiFi, maybe there is something new in the vicinity that is interfering with the channel you are using.
