### ISSUE TITLE
Get Device error and show it in Home Assistant

### ISSUE THREAD

**Issue by svalcken** [sockless-coding/panasonic_cc#288]
I have a situation with Climadevice, after start cooling and few seconds later it was going off.

After few tries, I have seen the timer led blinks. I have not known why, I have no timer set.
I have search for this and I found, this means a device error.
Here it give a list with error codes and this problem.

Here the codes I have found: https://www.vogelsang-klimatechnik.de/Stoerungscodes/RAC-und-Semi-FS-Inverter-Geraete.html

On remote control it is possible to show the code, the remote control will not use since more than one year.

The Panasonic Comfort Cloud has help me. Here the error was not direct visible but on (I) it shows the error code.

So I think via api it must possible to find the error code.

Can you check, if it possible and integrate it as a value.
If it is empty, no error otherwise the error code in value.
This is a way to make an automation event, if the device goes into an error.

Thanks

**Comment by sockless-coding** [comment]
@svalcken I haven't found a way to see the error codes in the app or api... I had some issues with my device a few months back and the only way to see the error was to use the remote. 
Though there is a section in the CFC app if you click the (i) where they have a title for errors but it's always been empty.
