### ISSUE TITLE
iAutoX has stopped working, econavi also stopped working after update to v1.1.10

### ISSUE THREAD

**Issue by thewan056** [sockless-coding/panasonic_cc#289]
Hi, after updating to v1.1.10, I can't use iAutoX anymore. It used to work when the heat/cool option was available. I went on a holiday so I am not sure which version it happened, but my last version was v1.0.58. The new iAutoX switch doesn't do anything. 

Since I already have heat/cool set to automations and smart switches in my room, is it possible to bring it back or give an option for it to be heat/cool instead of a switch so that I do not need to go and modify my automations and smart switch scenes?

**Comment by thewan056** [comment]
Update:
econavi has also stopped working. If I turn it on manually via remote, I can turn on the switch in HA, then turn it off, it will turn off econavi on my unit. But I cannot turn it on if it is off. The switch just reverts back to off after a while.

**Comment by sockless-coding** [comment]
Hi,
It's since v1.1.x, only the features reported by the API are added.

My device doesn't have those features, so I can't debug it my self you need to provide debug logs, primarily the logs that look like:
`[custom_components.panasonic_cc.pcomfortcloud.panasonicsession] GET url: https://accsmart.panasonic.com/deviceStatus/<REDACTED>, response: {"timestamp":1723621145059,"permission":2,"summerHouse":2,"iAutoX":false,"nanoe":true,"nanoeStandAlone":true,"autoMode":true,"heatMode":true,"fanMode":true,"dryMode":true,"coolMode":true,"ecoNavi":false,"powerfulMode":true,"quietMode":true,"airSwingLR":true,"autoSwingUD":false,"ecoFunction":0,"temperatureUnit":0,"modeAvlList":{"autoMode":1},"nanoeList":{"visualizationShow":0},"clothesDrying":false,"insideCleaning":false,"fireplace":false,"pairedFlg":false,"parameters":{"ecoFunctionData":0,"insideCleaning":0,"fireplace":0,"lastSettingMode":0,"operate":0,"operationMode":2,"temperatureSet":20,"fanSpeed":0,"fanAutoMode":1,"airSwingLR":5,"airSwingUD":3,"ecoMode":0,"ecoNavi":0,"nanoe":1,"iAuto":0,"airDirection":0,"insideTemperature":24,"outTemperature":21,"airQuality":0},"deviceNanoe":1}`

I need a log where you have turned iAutoX on using the remote and one where it's off
Same with econavi

**Comment by nickfabruada** [comment]
@thewan056 We have the same concern with iAutoX. see reported  issue https://github.com/sockless-coding/panasonic_cc/issues/281

Please share the debug log to further help @sockless-coding to analyze/debug the issue.

**Comment by thewan056** [comment]
Apologies, I forgot about logs. Thanks for the explanation. Logs are as follows:

all off:

`[custom_components.panasonic_cc.pcomfortcloud.panasonicsession] GET url: https://accsmart.panasonic.com/deviceStatus/<redacted>, response: {"timestamp":1724158278107,"permission":3,"summerHouse":0,"iAutoX":true,"nanoe":true,"nanoeStandAlone":true,"autoMode":false,"heatMode":false,"fanMode":false,"dryMode":true,"coolMode":true,"ecoNavi":true,"powerfulMode":true,"quietMode":true,"airSwingLR":true,"autoSwingUD":false,"ecoFunction":0,"temperatureUnit":0,"modeAvlList":{"autoMode":1},"nanoeList":{"visualizationShow":0},"clothesDrying":false,"insideCleaning":false,"fireplace":false,"parameters":{"ecoFunctionData":0,"insideCleaning":0,"fireplace":0,"lastSettingMode":0,"operate":1,"operationMode":2,"temperatureSet":28.5,"fanSpeed":4,"fanAutoMode":2,"airSwingUD":0,"airSwingLR":4,"airDirection":0,"ecoMode":0,"ecoNavi":1,"nanoe":1,"iAuto":1,"insideTemperature":25,"outTemperature":25,"airQuality":0},"deviceNanoe":1}`

iautox on:

`[custom_components.panasonic_cc.pcomfortcloud.panasonicsession] GET url: https://accsmart.panasonic.com/deviceStatus/<redacted>, response: {"timestamp":1724158307844,"permission":3,"summerHouse":0,"iAutoX":true,"nanoe":true,"nanoeStandAlone":true,"autoMode":false,"heatMode":false,"fanMode":false,"dryMode":true,"coolMode":true,"ecoNavi":true,"powerfulMode":true,"quietMode":true,"airSwingLR":true,"autoSwingUD":false,"ecoFunction":0,"temperatureUnit":0,"modeAvlList":{"autoMode":1},"nanoeList":{"visualizationShow":0},"clothesDrying":false,"insideCleaning":false,"fireplace":false,"parameters":{"ecoFunctionData":0,"insideCleaning":0,"fireplace":0,"lastSettingMode":0,"operate":1,"operationMode":0,"temperatureSet":25,"fanSpeed":0,"fanAutoMode":2,"airSwingUD":0,"airSwingLR":4,"airDirection":0,"ecoMode":0,"ecoNavi":1,"nanoe":1,"iAuto":2,"insideTemperature":25,"outTemperature":25,"airQuality":0},"deviceNanoe":1}`

econavi on:

`[custom_components.panasonic_cc.pcomfortcloud.panasonicsession] GET url: https://accsmart.panasonic.com/deviceStatus/<redacted>, response: {"timestamp":1724158320291,"permission":3,"summerHouse":0,"iAutoX":true,"nanoe":true,"nanoeStandAlone":true,"autoMode":false,"heatMode":false,"fanMode":false,"dryMode":true,"coolMode":true,"ecoNavi":true,"powerfulMode":true,"quietMode":true,"airSwingLR":true,"autoSwingUD":false,"ecoFunction":0,"temperatureUnit":0,"modeAvlList":{"autoMode":1},"nanoeList":{"visualizationShow":0},"clothesDrying":false,"insideCleaning":false,"fireplace":false,"parameters":{"ecoFunctionData":0,"insideCleaning":0,"fireplace":0,"lastSettingMode":0,"operate":1,"operationMode":2,"temperatureSet":30,"fanSpeed":4,"fanAutoMode":2,"airSwingUD":0,"airSwingLR":4,"airDirection":0,"ecoMode":0,"ecoNavi":2,"nanoe":1,"iAuto":1,"insideTemperature":25,"outTemperature":24,"airQuality":0},"deviceNanoe":1}`

I included nanoe because I also recently noticed some inconsistencies with nanoe showing off and on.  I noticed nanoe value sometimes changing to 4 and sometimes changing to 2. Not entirely sure which is what.

nanoe on:

`[custom_components.panasonic_cc.pcomfortcloud.panasonicsession] GET url: https://accsmart.panasonic.com/deviceStatus/<redacted>, response: {"timestamp":1724158332767,"permission":3,"summerHouse":0,"iAutoX":true,"nanoe":true,"nanoeStandAlone":true,"autoMode":false,"heatMode":false,"fanMode":false,"dryMode":true,"coolMode":true,"ecoNavi":true,"powerfulMode":true,"quietMode":true,"airSwingLR":true,"autoSwingUD":false,"ecoFunction":0,"temperatureUnit":0,"modeAvlList":{"autoMode":1},"nanoeList":{"visualizationShow":0},"clothesDrying":false,"insideCleaning":false,"fireplace":false,"parameters":{"ecoFunctionData":0,"insideCleaning":0,"fireplace":0,"lastSettingMode":0,"operate":1,"operationMode":2,"temperatureSet":30,"fanSpeed":4,"fanAutoMode":2,"airSwingUD":0,"airSwingLR":4,"airDirection":0,"ecoMode":0,"ecoNavi":1,"nanoe":4,"iAuto":1,"insideTemperature":25,"outTemperature":24,"airQuality":0},"deviceNanoe":1,"visualizationAvlFlg":true,"simulationShowFlg":false,"simulationSettingFlg":true,"simulationSettings":{"no":4,"shapeId":0,"positionId":1,"widthId":1,"levelGroup":[120,300,840],"devPositionTypeId":0,"nanoeOnTime":0}}`

`[custom_components.panasonic_cc.pcomfortcloud.panasonicsession] GET url: https://accsmart.panasonic.com/deviceStatus/<redacted>, response: {"timestamp":1724160646522,"permission":3,"summerHouse":0,"iAutoX":true,"nanoe":true,"nanoeStandAlone":true,"autoMode":false,"heatMode":false,"fanMode":false,"dryMode":true,"coolMode":true,"ecoNavi":true,"powerfulMode":true,"quietMode":true,"airSwingLR":true,"autoSwingUD":false,"ecoFunction":0,"temperatureUnit":0,"modeAvlList":{"autoMode":1},"nanoeList":{"visualizationShow":0},"clothesDrying":false,"insideCleaning":false,"fireplace":false,"parameters":{"ecoFunctionData":0,"insideCleaning":0,"fireplace":0,"lastSettingMode":0,"operate":1,"operationMode":2,"temperatureSet":28.5,"fanSpeed":4,"fanAutoMode":2,"airSwingUD":0,"airSwingLR":4,"airDirection":0,"ecoMode":0,"ecoNavi":1,"nanoe":2,"iAuto":1,"insideTemperature":25,"outTemperature":26,"airQuality":0},"deviceNanoe":1,"visualizationAvlFlg":true,"simulationShowFlg":false,"simulationSettingFlg":true,"simulationSettings":{"no":4,"shapeId":0,"positionId":1,"widthId":1,"levelGroup":[120,300,840],"devPositionTypeId":0,"nanoeOnTime":2317}}`

**Comment by sockless-coding** [comment]
I've done some iAutoX changes in v1.1.11

**Comment by thewan056** [comment]
iAutoX switch is now confirmed working. Thanks.

econavi refuses to work. the switch reacts accordingly when use the remote to turn it on or off, the switch reacts on or off respectively. When i switch econavi on using the remote, i can turn it off in HA. But I cannot turn it on in HA when it is off.

However, in my use case, i don't really use it, so for me it is nice to have working but if we can't get it to work then it is ok. im not sure about others.

**Comment by sockless-coding** [comment]
Good to hear that the iAutoX is working.
When it comes to EcoNavi, can you turn it on if you set the mode to cooling and iAutoX to off?
