### ISSUE TITLE
Integration Restart necessary after HA Update

### ISSUE THREAD

**Issue by fossisbaer** [sockless-coding/panasonic_cc#290]
whenever HA is updated (either core or operating system) panasonic_cc integration stops "working" and is not accessible via thermostat-card. After intergration has been reloaded it works until next ha update. All other ha integrations are not affected by updates only panasonic_cc integration.

**Comment by sockless-coding** [comment]
@fossisbaer I've never seen this happen, do you have any logs?

**Comment by fossisbaer** [comment]
hi, got it solved....i was powering OFF my Panasonic AC completly with a Master Switch (with a Shelly Switch to reduce Stand-By power)....of course panasonic_cc integration could not serve any sensors when power OFF....after switching power back ON i had to reload panasonic_cc integration to refresh sensor data again. I made a new automatisation to relaod panasonic_cc integration after power ON with "service: homeassistant.reload_config_entry". Just a timely coincidence with the HA updates as i run them manually at the evening when AC is not running. Anyway thanks for the response that motivated me to look for a solution.
