### ISSUE TITLE
No devices shown in hub

### ISSUE THREAD

**Issue by ElChemizt** [sockless-coding/panasonic_cc#291]
Hi,

My 2 airco devices entities became unavailable after updating HA and Panasonic comfort cloud HACS. 

After deleting the hub with the two devices and adding the hub again, no devices are shown.

What can I do to (help) resolve this issue?

**Comment by sockless-coding** [comment]
@ElChemizt Hi, you need to enable debug logging and provide some more information.
I need the entry that looks like: `[custom_components.panasonic_cc.pcomfortcloud.panasonicsession] GET url: https://accsmart.panasonic.com/device/group, response: ...`
There should also be a `[custom_components.panasonic_cc] Got x devices` just after it

**Comment by ElChemizt** [comment]
@sockless-coding Hi! Thank you for your reply!
I’m a bit new to the error messages, but enabling and disabling debugging didn’t provide me with a download via HA iPhone app. 

But I found these in the  home-assistan log:

`This error originated from a custom integration.

Logger: custom_components.panasonic_cc.pcomfortcloud.helpers
Source: custom_components/panasonic_cc/pcomfortcloud/helpers.py:27
integration: Panasonic Comfort Cloud (documentation, issues)
First occurred: August 16, 2024 at 10:56:25 PM (11 occurrences)
Last logged: 8:17:40 AM

`Error in get_device Expected status code '200' but received '500' Response body: {"code":5005,"message":"Adapter Communication error"}`

And 

`This error originated from a custom integration.

Logger: custom_components.panasonic_cc.coordinator
Source: custom_components/panasonic_cc/coordinator.py:77
integration: Panasonic Comfort Cloud (documentation, issues)
First occurred: August 16, 2024 at 10:56:25 PM (11 occurrences)
Last logged: 8:17:40 AM

Error fetching device data from API: (get_device: Expected status code 200, received: 500: {"code":5005,"message":"Adapter Communication error"}
Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/coordinator.py", line 77, in _fetch_device_data
    self._device = await self._api_client.get_device(self._panasonic_device_info)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 121, in get_device
    json_response = await self.execute_get(self._get_device_status_url(device_info.guid), "get_device", 200)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/panasonicsession.py", line 144, in execute_get
    await check_response(response, function_description, expected_status_code)
  File "/config/custom_components/panasonic_cc/pcomfortcloud/helpers.py", line 32, in check_response
    raise exceptions.ResponseError(
custom_components.panasonic_cc.pcomfortcloud.exceptions.ResponseError: (get_device: Expected status code 200, received: 500: {"code":5005,"message":"Adapter Communication error"}`

does this provide useful information?
`m

**Comment by sockless-coding** [comment]
The 5005 error "Adapter Communication error" is usually caused by the AC having an unstable internet connection.

**Comment by ElChemizt** [comment]
Thank you for that clarification. 
Than I expect this to be a message of the unit that has been found. 
Still the other unit is not available in HA. 

Both units work without issue in the Panasonic comfort cloud app. 

Anything else that I can do?

**Comment by ElChemizt** [comment]
Thank you for your support! 
I have reset the WiFi network and cut the power to the airco. 
After powering on the airco again and reloading the integration both devices where found. 

This issue is resolved.
