### ISSUE TITLE
Fan speed

### ISSUE THREAD

**Issue by jensolsson** [sockless-coding/panasonic_cc#297]
Works great but i cannot find a way to control the fan speed? My ac have 5different fan speeds incan select using the remote.

**Comment by jensolsson** [comment]
I found the fan speed when pressing the ... button, but fan speed does not seem to have any effect on my AC. I have a Panasonic CS-HZ25UKE

**Comment by sockless-coding** [comment]
I have a CS-HZ25UKE as well and changing the Fan Speed works fine... do you get an error message / log entry?
