### ISSUE TITLE
Sensors no longer available

### ISSUE THREAD

**Issue by sxmpa** [sockless-coding/panasonic_cc#299]
The sensors of my ac devices are no longer available since the last update. Changing temperature & modes are possible but no more sensor-information like inside/outside temperature etc.

**Comment by Jellybabz** [comment]
I have the same problem

**Comment by Auka84** [comment]
I just noticed I have the same issue

I have all of those error message in the log

> Cette erreur provient d'une intégration personnalisée
> 
> Enregistreur: custom_components.panasonic_cc.pcomfortcloud.helpers
> Source: custom_components/panasonic_cc/pcomfortcloud/helpers.py:20
> intégration: Panasonic Comfort Cloud (documentation, problèmes)
> S'est produit pour la première fois: 13:46:27 (8 occurrences)
> Dernier enregistrement: 13:51:19
> 
> Error in get_todays_energy Expected status code '200' but received '504' Payload: {'deviceGuid': 'CS-MZ16ZKE+E080201555', 'dataMode': 2, 'date': '20240831', 'osTimezone': '+02:00'} Response body: {"message": "Endpoint request timed out"}
> Error in get_todays_energy Expected status code '200' but received '504' Payload: {'deviceGuid': 'CS-Z50ZKEW+E065003882', 'dataMode': 2, 'date': '20240831', 'osTimezone': '+02:00'} Response body: {"message": "Endpoint request timed out"}
> Error in get_todays_energy Expected status code '200' but received '504' Payload: {'deviceGuid': 'CS-Z25XKEW+4886840800', 'dataMode': 2, 'date': '20240831', 'osTimezone': '+02:00'} Response body: {"message": "Endpoint request timed out"}
> Error in get_todays_energy Expected status code '200' but received '504' Payload: {'deviceGuid': 'CS-Z20ZKEW+E064609191', 'dataMode': 2, 'date': '20240831', 'osTimezone': '+02:00'} Response body: {"message": "Endpoint request timed out"}
> Error in get_todays_energy Expected status code '200' but received '504' Payload: {'deviceGuid': 'CS-MZ16ZKE+E080201513', 'dataMode': 2, 'date': '20240831', 'osTimezone': '+02:00'} Response body: {"message": "Endpoint request timed out"}



and also this

> Cette erreur provient d'une intégration personnalisée
> 
> Enregistreur: custom_components.panasonic_cc.coordinator
> Source: custom_components/panasonic_cc/coordinator.py:136
> intégration: Panasonic Comfort Cloud (documentation, problèmes)
> S'est produit pour la première fois: 13:46:27 (8 occurrences)
> Dernier enregistrement: 13:51:19
> 
> Error fetching energy data from API: (get_todays_energy: Expected status code 200, received: 504: {"message": "Endpoint request timed out"}
> Traceback (most recent call last):
>   File "/config/custom_components/panasonic_cc/coordinator.py", line 136, in _fetch_device_data
>     self._energy = await self._api_client.async_get_energy(self._panasonic_device_info)
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 134, in async_get_energy
>     todays_item = await self._async_get_todays_energy(device_info)
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 157, in _async_get_todays_energy
>     history = await self.execute_post(self._get_device_history_url(), payload, "get_todays_energy", 200)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/panasonic_cc/pcomfortcloud/panasonicsession.py", line 117, in execute_post
>     await check_response(response, function_description, expected_status_code, payload=json_data)
>   File "/config/custom_components/panasonic_cc/pcomfortcloud/helpers.py", line 32, in check_response
>     raise exceptions.ResponseError(
> custom_components.panasonic_cc.pcomfortcloud.exceptions.ResponseError: (get_todays_energy: Expected status code 200, received: 504: {"message": "Endpoint request timed out"}

**Comment by RonnieRocket2** [comment]
Same issue with lack of sensors here

**Comment by sockless-coding** [comment]
It's the Panasonic Servers, if you try to use the Comfort Cloud App and access energy you should get a E03-0147-5600 error.

**Comment by ttjorvi** [comment]
same problem

**Comment by Auka84** [comment]
> It's the Panasonic Servers, if you try to use the Comfort Cloud App and access energy you should get a E03-0147-5600 error.

I haven't any error in the comfort cloud app. I have all info about the energy :-/

**Comment by BinnenBeest** [comment]
I have the same problem, next the integration is very slow.
The panasonic app works fine.

**Comment by Auka84** [comment]
Since this morning some sensors are back. Strange. 


![IMG_7245](https://github.com/user-attachments/assets/3a1b0e76-d5a9-4166-b201-3d1f4f5dee12)

**Comment by ELANDJEA** [comment]
My connection using this connector was lost since aug 27th.....no sensors are reported anymore.....all unavailable.

The panasonic cloud app is still working

**Comment by sockless-coding** [comment]
Panasonic had server issues, but they should be ok now.
@ELANDJEA if you are still having issues, please provide some logs.

**Comment by ELANDJEA** [comment]
> Panasonic had server issues, but they should be ok now. @ELANDJEA if you are still having issues, please provide some logs.

@sockless-coding , thanks for notifying......it looks like the connection to the wifi was not stable....after resetting the airco and new registration within comfortcloud, it started working again.

**Comment by sockless-coding** [comment]
I'll close this issue for now

**Comment by RonnieRocket2** [comment]
Yes it was the Panasonic servers, thank you.

**Comment by Jellybabz** [comment]
Are servers Down again? All my enegy sensor ar unavalible
