### ISSUE TITLE
Temperature shows 126

### ISSUE THREAD

**Issue by EvertJob** [sockless-coding/panasonic_cc#3]
Hi,

The temperature in Home Assistant shows constantly 126 degree.

How can I fix this?

**Comment by sockless-coding** [comment]
Hi,

126 is the temperature given when it's not available, I though all heat pumps had the inside sensor. I'll add a check so it doesn't show 126 value

**Comment by EvertJob** [comment]
It’s having a inside sensor, but not web enabled I guess. My outside sensor is only working when the AC is turned on. Pretty weird but that’s te story Panasonic gave me.

I’m having a Zigbee temp sensor mounted on the AC but it’s not possible to edit the `current_temperature` With another value :(

**Comment by sockless-coding** [comment]
v1.0.8 should remove the 126­° temperature sensor.
I'm not sure you can replace the current temperature property with a different value, but it shouldn't be active anymore.

**Comment by EvertJob** [comment]
No, it's not possible on the Home Assistant side. I've already checked that on Discord.

**Comment by sockless-coding** [comment]
Hmm, not sure it would work but maybe you can create frankenstein-entity using node-red, where current temp of the climate entity is linked from a different sensor...
Or use something like the https://github.com/nervetattoo/simple-thermostat card to display the temperature sensor.

**Comment by EvertJob** [comment]
The Frankenstein approach is not working. It's not possible to update the `current_temperature` external. Don't know why

**Comment by sockless-coding** [comment]
Well you can always make a fork of this repository and change the property to a static value... :)

**Comment by BVGorp** [comment]
I have an air conditioner with an outside sensor that is only active if the unit is on.
So when i turn off the unit the outside sensor goes to unavailable but not before passing this 126 value to my influxdb/grafana.
This is not great for my temperature graphs.
Isn't it possible if value is 126 drop the value alltogether?

**Comment by sockless-coding** [comment]
@BVGorp Hi I've add a check for the 126 value, and a setting to force the outside sensor to be detected in case the device should be off when HA starts.
