### ISSUE TITLE
Wrong energy readings when there is more than one device

### ISSUE THREAD

**Issue by xyz667** [sockless-coding/panasonic_cc#301]
I have one outdoor unit with two indoor devices.
In the Panasonic Comfort Cloud app there are three energy readings for each device ("Heat", "Cool" and "Other"), where "Other" seems to be the energy used by the other (second) device.
Your integration seems to add all readings for the daily_enegy sensor.
That way both devices are reporting twice the energy actually consumed, as the devices' own entry is added to the "other" energy reading of the second device.

**Comment by sockless-coding** [comment]
@xyz667 Can you enable debug logging and provide an energy log entry, they start with the following:
`DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicsession] POST url: https://accsmart.panasonic.com/deviceHistoryData`

**Comment by xyz667** [comment]
> @xyz667 Can you enable debug logging and provide an energy log entry

@sockless-coding lat me explain the issue with a little more detail, maybe is just a misconception on my side.

As mentioned I have two indoor units, both connected to the same single outdoor unit.
I wanted to show energy readings for both indoor units in the HA energy dashboard, and thus added both daily_energy sensors (one for each indoor unit). daily_energy and not daily_cooling_energy because I want to see total energy consumption of each device, both heating and cooling.
As it turns out both daily_energy readings are the same (only minor differences, maybe rounding related).
Why? Because there‘s the „Other“ category in the Comfort Cloud app, and there is no HA sensor for that. „Other“ seems to be the energy used by the rest of the system (outdoor unit and all other attached indoor units).

See two screenshots for both indoor units of the same day (from Panasonic app):
![IMG_3252](https://github.com/user-attachments/assets/9986eae9-579b-4826-9762-61d90f7bbd07)
![IMG_3251](https://github.com/user-attachments/assets/ede3d7b1-84fd-4a07-a873-c0ed8b7748af)
One device was not in use on that day, still the energy used is (almost) the same, because of „other“ for the inoperative device.

Thinking about it, maybe it does not make sense to track the consumption of each indoor unit, as probably most power is used in the single outdoor unit driving both indoor units combined.
Thats why I have deleted one of the indoor units from the enegry dashboard, and still get total consumption numbers for both indoor units although only the sensor of one of them is included.

It‘s like the separate sensors for outdoor temperature for each indoor unit. They are the same, as temp is measured only once in the single outdoor unit, having separate sensors for each indoor unit is redundant. But I guess I get why you set it up like that, probably this is a design decision forced upon us by the Panasonic cloud. 

So, maybe this issue can be closed.

**Comment by sockless-coding** [comment]
The energy tracking isn't very accurate, I think the heating/cooling is just takes all energy used by the system while in heating/cooling mode... if in another mode "other" will be used.
I'll close the issue for now.

**Comment by Bouke** [comment]
Thanks for the suggestion of disabling all but one sensor, at least that cleans up the energy dashboard.

As we know which indoor units are active, is there a way we can allocate the total consumption to the individual indoor units?

**Comment by sockless-coding** [comment]
@Bouke does the indoor units show up as individual devices in HA? If so, each device should have their own energy sensor.
But if the values are identical on both, Panasonic is only reporting a combined value and it would probably be impossible to get any accurate per device reading from that; since the energy values only gets updated every 15 or so min.
