### ISSUE TITLE
Integration stopped working (Unable to authenticate)

### ISSUE THREAD

**Issue by OskiFTW** [sockless-coding/panasonic_cc#303]
So Panasonic Comfort Cloud - HomeAssistant Component was working great for since i first installed it. I did setup the SMS MFA via Panasonic ID and the integration was working for a month or so. Until it suddenly stopped working.
Steps I tried to fix the issue:

- Updated Home Assistant, HACS and panasonic_cc to latest version
- Restarted Home Assistant
- Tried to reconfigure the integration, inserting my email and password, but got API error or similar after 1-5 seconds of loading each time. But each time i received email from Panasonic ID saying "Thank you very much for using a Panasonic ID. You have logged in to your Panasonic ID."
- Reset my MFA method via Panasonic ID
- Tried above again with same issue
- Re-downloaded latest version from repo
- Restarted Home Assistant
- Adding Panasonic_cc from scratch, this time the loading is more like 2-3 minutes before failing, I still get confirmation email from Panasonic about successful login.

![Skärmbild 2024-09-11 155018](https://github.com/user-attachments/assets/1215eb52-6635-4ef1-bd05-9d4f86a165e5)
![Skärmbild 2024-09-11 155155](https://github.com/user-attachments/assets/94062c33-4e31-4aed-b6ca-e2a47768f37e)

What am I doing wrong here? Panasonic comfort cloud app works without issues...

**Comment by MelvinRC** [comment]
Works again over here...

**Comment by OskiFTW** [comment]
Issue has changed to this now:
![Skärmbild 2024-09-12 200308](https://github.com/user-attachments/assets/1d3c51b8-b265-4d9d-9591-940aeafae42b)
With error:
`2024-09-12 20:00:20.862 WARNING (MainThread) [custom_components.panasonic_cc.pcomfortcloud.apiclient] Could not get groups, trying to re-authenticate
Traceback (most recent call last):
File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 51, in start_session
await self._get_groups()
File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 66, in _get_groups
self._groups = await self.execute_get(
^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/panasonic_cc/pcomfortcloud/panasonicsession.py", line 127, in execute_get
response = await self._client.get(
^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 573, in _request
with timer:
File "/usr/local/lib/python3.12/site-packages/aiohttp/helpers.py", line 713, in __exit__
raise asyncio.TimeoutError from None
TimeoutError`

And second try:
![Skärmbild 2024-09-12 202502](https://github.com/user-attachments/assets/2a39fc7d-3c03-402a-bf29-7bb539dce7d4)
With error:
`2024-09-12 20:19:41.861 WARNING (MainThread) [custom_components.panasonic_cc.pcomfortcloud.apiclient] Could not get groups, trying to re-authenticate
Traceback (most recent call last):
File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 51, in start_session
await self._get_groups()
File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 66, in _get_groups
self._groups = await self.execute_get(
^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/panasonic_cc/pcomfortcloud/panasonicsession.py", line 127, in execute_get
response = await self._client.get(
^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 573, in _request
with timer:
File "/usr/local/lib/python3.12/site-packages/aiohttp/helpers.py", line 713, in __exit__
raise asyncio.TimeoutError from None
TimeoutError`

Loading time before receiving error was approx 9-10minutes

**Comment by sockless-coding** [comment]
@OskiFTW the servers are not responding to your request for some reason. There might be some issues with the authentication servers.
Could you enable debug logging and provide those logs?

**Comment by OskiFTW** [comment]
@sockless-coding Sure find the log attached.
Another issue I noticed while troubleshooting is that I can input any username and password and the integration configuration will spin for 10 minutes.
And to make it even worse, I changed my password with android app, logged out and back in on the android app with the new password.
But using that new password in home assistant gives '401'
[logs.log](https://github.com/user-attachments/files/16998699/logs.log)

**Comment by sockless-coding** [comment]
@OskiFTW I need the debug logs to see the actual request and response from the servers.
You can enable debug logging either on the integration page or in the configuration.yaml

![image](https://github.com/user-attachments/assets/0efec46f-041d-467c-b936-cc70dd95f2db)

configuration.yaml:
```yaml
logger:
  default: info
  logs:
    custom_components.panasonic_cc: debug
```

**Comment by OskiFTW** [comment]
@sockless-coding Thanks, I managed to turn on debug logging for panasonic_cc.
Before I share the log, allow me to ask a stupid question. Is it safe to share the debug log, I see that it contains things like: "Authenticating with username and password", "Retrieving acc client id using access token", "Authentication response" etc?

**Comment by sockless-coding** [comment]
Redact any tokens and deviceGuid

**Comment by OskiFTW** [comment]
@sockless-coding 
[2024-09-14 DEBUG.log](https://github.com/user-attachments/files/17001914/2024-09-14.DEBUG.log)

**Comment by sockless-coding** [comment]
@OskiFTW everything looks fine with the authentication. Can you try calling `ping accsmart.panasonic.com` from HA?
You can also try navigating to `https://accsmart.panasonic.com/device/group` in a browser, it should give you a 403 error page.
I just noticed something, are you using 1.1.1.1 as a DNS server? I can't resolve `accsmart.panasonic.com` using 1.1.1.1 it works with 8.8.8.8

**Comment by OskiFTW** [comment]
Changing DNS to 8.8.8.8 solved the issue. My router was using ISP provided DNS previously.
Was unable to ping accsmart.panasonic.com in HA before DNS switch.
Thank you @sockless-coding.
