### ISSUE TITLE
Not possible to create device

### ISSUE THREAD

**Issue by MichaelNRW** [sockless-coding/panasonic_cc#305]
Hello,
I have been trying to integrate an Aquarea heat pump into Home Assistant for some time.
The login details are correct, checked via the app, access is possible here. I logged out of the app and started the integration, entered user data and then the following message appears:

![Bildschirmfoto vom 2024-09-14 21-43-58](https://github.com/user-attachments/assets/c5a2998c-3096-4464-b1b9-687870e844f7)

Nothing is displayed in the log.

Panasonic Comfort Cloud V 1.1.11

Home Assistant:
Core: 2024.9.1
Supervisor: 2024.09.1
Operating System: 13.1
Frontend: 20240906.0

Greetings
Michael

**Comment by sockless-coding** [comment]
@MichaelNRW Hi, at the time Aquarea devices isn't supported. I do not have Aquarea device, and they use different endpoints and data structures.
To add support, I need some data logs from the CFC app, but it's quite difficult to setup.

**Comment by MichaelNRW** [comment]
Ok, thanks for the information
