### ISSUE TITLE
Spurious spike in Current Power

### ISSUE THREAD

**Issue by ladislashd** [sockless-coding/panasonic_cc#306]
I have been looking at the power usage chart. I can see random spike during the day.
![image](https://github.com/user-attachments/assets/baedd19e-4ce7-4e86-80df-1fbb79cd40f1)
I have 2 other AC that show the same kind of unrealistic value at random time during the day, form example for the last 3 day :
![image](https://github.com/user-attachments/assets/807a5346-9e9c-4b13-b1fe-a52bfd1ca2c1)

Not sure if the integration is causing this or a bug within Home Assistant. 

Thank you for your understanding

**Comment by sockless-coding** [comment]
@ladislashd Hi, the power values are not very reliable, the api does not provide any power information. I calculate the power from the energy values and those values... can be a bit unreliable as well... do you have the energy values that corresponds to a spike... if there is a flat spot before all that energy will be used as a base for the power calculation.
