### ISSUE TITLE
Error in get_token

### ISSUE THREAD

**Issue by XRaTiX** [sockless-coding/panasonic_cc#307]
First time using this,using the latest version 2024.9.0 when trying to login it says "Error creating device"

![image](https://github.com/user-attachments/assets/2e6eeb0e-7d72-4da2-85c3-19425f65a8fe)

Looking in the logs it says the following:

`2024-09-21 19:52:41.681 ERROR (MainThread) [custom_components.panasonic_cc.pcomfortcloud.helpers] Error in get_token
Expected status code '200' but received '400'
Response body: {"error":"invalid_request","error_description":"Missing required parameter: code"}
`

The panasonic account is created with a google account,I don't know if this can be the problem.

**Comment by sockless-coding** [comment]
@XRaTiX Hi, currently the only authentication that works is username/password with SMS as 2FA. And it's also recommended that you set up a dedicated HA account.

**Comment by XRaTiX** [comment]
Thank you so much,I created a dedicated panasonic id with sms 2fa and now it works.

**Comment by alexpb123** [comment]
Hi I am getting the same issue but I have a dedicated panasonic ID
