### ISSUE TITLE
Changing Fanspeed when aircon mode is off turns it on.

### ISSUE THREAD

**Issue by Nornode** [sockless-coding/panasonic_cc#315]
### Checklist

- [X] I have verified that the account and device works in the Comfort Cloud App.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/sockless-coding/panasonic_cc/issues?q=is%3Aissue+label%3A"bug"+)..

### What version of Home Assistant Core?

core-2024.9.2

### Describe the issue

I have an HA automation that only controls my main (livingroom) air-con. 
This one runs conditionally, if we are at home but on a time based trigger. 
It controls the fan speed only, not any other parameter.
In previous version, this was OK, fan speed changed and did not change aircon Mode.
The behaviour can be replicated through changes in the UI too.

Unfortunately, during a summer update, the behaviour has changed.

I want to be able to control the fan speed while not impacting the mode state even if it's off.
Work arounds are welcome if this is the intended behaviour.

**Comment by sockless-coding** [comment]
Don't really see the need, why would you set the fan speed if the device is off.... But it seems the API accepts it. So I've added support for it.
