### ISSUE TITLE
"Data Age" Issue

### ISSUE THREAD

**Issue by skyline-969** [sockless-coding/panasonic_cc#316]
### Checklist

- [X] I have verified that the account and device works in the Comfort Cloud App.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/sockless-coding/panasonic_cc/issues?q=is%3Aissue+label%3A"bug"+)..

### What version of Home Assistant Core?

core-2024.9.3

### Describe the issue

In the Log every couple seconds the "Data Age" of all my devices refresh.
![HA_Issue1](https://github.com/user-attachments/assets/9c532c1f-97de-4ac2-9458-8a58dd85cd48)
![HA_Issue2](https://github.com/user-attachments/assets/deb7f0aa-9ae4-44ad-85dd-ef15b3352f5c)
![HA_Issue3](https://github.com/user-attachments/assets/c0b2e505-bd09-43e4-97f8-5459b700bfb3)

**Comment by sockless-coding** [comment]
I've corrected it the so the sensor doesn't flood the logs.

**Comment by skyline-969** [comment]
I still got the Problem.
Any tips?
Thank you very much :)
![HA_Issue1](https://github.com/user-attachments/assets/bec92415-68d6-4f67-87e5-c4f23ec3bc8c)
![HA_Issue2](https://github.com/user-attachments/assets/fd9f90ff-5729-437d-8f8e-910826a6c981)

**Comment by sockless-coding** [comment]
I haven't released the version containing the fix yet :)

**Comment by skyline-969** [comment]
Sure. My bad... :D

Am 25.09.2024 19:06 schrieb Jimmy Everling ***@***.***>:

I haven't released the version containing the fix yet :)

**Comment by sockless-coding** [comment]
@skyline-969 I've released 2024.9.3
