### ISSUE TITLE
403 Errors

### ISSUE THREAD

**Issue by craigtsmith** [sockless-coding/panasonic_cc#32]
I noticed 403 errors coming from `pcomfortcloud` so did some digging and it seems Panasonic have updated their headers again and `pcomfortcloud` needs to be updated to enable this plugin to start working again!

I've created the PR for the dependency here: https://github.com/lostfields/python-panasonic-comfort-cloud/issues/40 so hopefully it will be merged soon and AC will once again been working! lol

**Comment by sockless-coding** [comment]
@craigtsmith I've prepared the manifest for when lostfields updates the package, he is usually quite fast.

**Comment by craigtsmith** [comment]
Awesome! Anything I can do to help let me know :)

**Comment by jonootto** [comment]
Hi, is this related to getting the following error?:
```
Unable to install package pcomfortcloud==0.0.21: ERROR: Could not find a version that satisfies the requirement pcomfortcloud==0.0.21 (from versions: 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.14, 0.0.15, 0.0.16, 0.0.17, 0.0.18, 0.0.19, 0.0.20) ERROR: No matching distribution found for pcomfortcloud==0.0.21 WARNING: You are using pip version 20.2.4; however, version 21.0.1 is available. You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
```

**Comment by jonootto** [comment]
I've set the version back to before c5cc618665fc9777747997d3a9d515f0046be719 and it's working again, this may have been a seperate issue that @craigtsmith was having?

**Comment by sockless-coding** [comment]
@jonootto I had prepared for a new version of the lib, but it was not necessary at this point... The problem was issues on Panasonics end, their API has been a bit iffy.
But I have restored the pcomfortcloud to 0.0.20

**Comment by craigtsmith** [comment]
Hey all, so I may have jumped the gun in assuming the issue was with the underlying `python-panasonic-comfort-cloud` library. After removing + reinstalling `panasonic_cc` via HACS the issue went away! Apologies all, will close this issue now.
