### ISSUE TITLE
Rotation speed bug

### ISSUE THREAD

**Issue by mkz212** [sockless-coding/panasonic_cc#323]
### Checklist

- [X] I have verified that the account and device works in the Comfort Cloud App.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/sockless-coding/panasonic_cc/issues?q=is%3Aissue+label%3A"bug"+)..

### What version of Home Assistant Core?

core-2024.10.2

### Describe the issue

Hi.

I just moved from Homebridge to Home Assistant and installed this plugin. Everything works as it should, except for setting the speed. In HomeKit it shows as a fan but I can only set 0%, 50% and 100%. But no matter what I set it doesnt change enything in my AC. Changing the speed or enabling quiet mode from the Comfort Cloud app or Home Assistant doesn't change the fan slider in HomeKit. It would be good if you could use the slider to turn on the Quiet and Powerful mode, e.g. a value from 1 to 9% - quiet mode.

My AC: CS-Z50VKEW

**Comment by sockless-coding** [comment]
Sound more like a HomeKit issue... If changing settings in Comfort Cloud app doesn't affect it, it's not talking to the API.

**Comment by mkz212** [comment]
> Sound more like a HomeKit issue... If changing settings in Comfort Cloud app doesn't affect it, it's not talking to the API.

Control from Comfort Cloud works, with Home Assistant too. With HomeKit, everything works except the speed slider. For other AC (other brand) sliders for speed works. I tried restarting Home Assistant and Home hub but still same.

By the way: could you add a quiet mode switch (like Nanoe)?

**Comment by sockless-coding** [comment]
@mkz212 it's available as a preset, having a switch wouldn't really make sense since there are multiple presets, and they can't be active at the same time.

**Comment by sockless-coding** [comment]
This integration has nothing to do with HomeKit
