### ISSUE TITLE
Power and Energy Sensors not available 

### ISSUE THREAD

**Issue by adb854** [sockless-coding/panasonic_cc#329]
### Checklist

- [X] I have verified that the account and device works in the Comfort Cloud App.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/sockless-coding/panasonic_cc/issues?q=is%3Aissue+label%3A"bug"+)..

### What version of Home Assistant Core?

core-2024.10.4

### Describe the issue

Clima model: Etherea
Power and Energy Sensors are not available

![image](https://github.com/user-attachments/assets/96eaaa90-6af1-4f4e-9c58-7298898225df)

**Comment by sockless-coding** [comment]
@adb854 Hi, there is a setting to enable energy sensors have you enabled that en restarted HA?
![image](https://github.com/user-attachments/assets/1a11eeeb-ff96-4d27-bc1d-33a1406e17e9)
