### ISSUE TITLE
6 is no a valid AirSwingLR

### ISSUE THREAD

**Issue by com-xuonghuynh** [sockless-coding/panasonic_cc#33]
It's suddenly stop working few days ago with this error and I don't know how to fix it. Please help. My AC don't have Swing LR. Only UD
![image](https://user-images.githubusercontent.com/41953297/118220459-f6e8fd80-b4a5-11eb-99be-1c076e9037bf.png)

**Comment by sockless-coding** [comment]
Fixed in v1.0.49
