### ISSUE TITLE
Logging in using Panasonic ID / Password.

### ISSUE THREAD

**Issue by jame0swhite** [sockless-coding/panasonic_cc#333]
### Checklist

- [X] I have verified that the account and device works in the Comfort Cloud App.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/sockless-coding/panasonic_cc/issues?q=is%3Aissue+label%3A"bug"+)..

### What version of Home Assistant Core?

core-2024.10.2

### Describe the issue

I have been using this integration for some time now but noticed it had failed to start today.
I have been prompted for my login details (which I can login to the app with no problem) and recieve the error "unexpected error creating device".
I have double checked that i am registered for MFA, I am prompted for a verification code when checking my details in my account but not when logging into the app (if at all relevant).

![1](https://github.com/user-attachments/assets/26a42c51-baa0-4de6-a4a4-5cab0f91b910)
![2](https://github.com/user-attachments/assets/a039c3d4-d198-40c1-b248-9938760b2347)

**Comment by noonscoomo** [comment]
same for me

**Comment by Olifant1990** [comment]
Maybe the same problem as reported here https://github.com/sockless-coding/panasonic_cc/issues/331

**Comment by canto33** [comment]
Bonjour j'ai le même problème

**Comment by jame0swhite** [comment]
> Maybe the same problem as reported here #331

ah yes, thank you - i did look for other issues but nothing stood out!

**Comment by wolfjank** [comment]
Same for me

**Comment by notio-ca** [comment]
DUPLICATE please see Issues https://github.com/sockless-coding/panasonic_cc/issues/331

Everyone is having this issue, please no more same for me, we are spamming the developer
Thanks

**Comment by stefanovic45** [comment]
Same here...

**Comment by slavlad** [comment]
Same for me

**Comment by Branko069** [comment]
Same here

**Comment by Timjena** [comment]
same here

**Comment by NilsOscar** [comment]
Same here:
"unexpected error creating device"

**Comment by Billiegirl** [comment]
Thanks to the devs for their work on this 🎂

**Comment by sockless-coding** [comment]
Fixed in version 2024.11.0

**Comment by lawrencedudley** [comment]
Thanks so much!
