### ISSUE TITLE
Problem with integration Panasonic Confort Cloud

### ISSUE THREAD

**Issue by joslmar** [sockless-coding/panasonic_cc#334]
### Checklist

- [X] I have verified that the account and device works in the Comfort Cloud App.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/sockless-coding/panasonic_cc/issues?q=is%3Aissue+label%3A"bug"+)..

### What version of Home Assistant Core?

Panasonic Confort Cloud

### Describe the issue

Good afternoon, for several days the Panasonic Confort Cloud integration in Home Assistant has not worked for me, I have uninstalled the integration and reinstalled it but I get the following error message:

![Captura](https://github.com/user-attachments/assets/2505c1b7-24fe-4f14-bbd0-27bba411c283)

Does anyone know how to solve it? Before it worked perfectly for me.

Best regards,

### Error/Debug Logs

```text
When I enter my username and password it does not detect the devices and the mobile app does work correctly
```

**Comment by Jellybabz** [comment]
I think is has something to do with the authentication code... When i loged in to the app it did ask for the authentication code

**Comment by joslmar** [comment]
Hello, 

Thanks for answering!

What should I do to solve that? When I enter the app through an Android phone, it does not ask me for any authentication code, I just enter my username and password and access my devices.


Best regards,

**Comment by marc2016** [comment]
Look at Thor issue https://github.com/sockless-coding/panasonic_cc/issues/333
This is a general problem:-(

**Comment by GSVGreyAreaUK** [comment]
@sockless-coding Your support is greatly appreciated. I upgraded HA and reinstalled the integration to find what everyone else is experiencing.

**Comment by joslmar** [comment]
Thanks for your answer. 

So should we wait until the developers fix this problem?


Best regards,

**Comment by wiabts** [comment]
Same here, credentials are not accepted although they work online

**Comment by Trodah** [comment]
Same here. I discovered the issue after upgrading ha Core.

**Comment by janplanta** [comment]
**Guys, I think it has been established that this is an API problem caused by Panasonic. The devs need to work on it and no new reinstall on your side will fix it.
Let's cut the developers some slack to get the code adaption to the new API done. Until then, the plugin won't work.**

**Comment by malosaaa** [comment]
For me it just works normal.
I just added my Panasonic cloud with last HA update, and it works normal

Regards

**Comment by Trodah** [comment]
😃👍

**Comment by Branko069** [comment]
#soccles, i have a HA_2024.11 same problem i try tu connect to CC, error

**Comment by Branko069** [comment]
Great Job !! It works after re-install CC :-)

**Comment by joslmar** [comment]
Good afternoon,

After the last Home Assistant update, I reinstalled the integration and it works again.

Thank you very much for the excellent support!

Best regards,

**Comment by malosaaa** [comment]
Thanks for fixing it!! 

 excellent support!

**Comment by vaibhavratnaparkhi** [comment]
Gives me the error 'no devices'. 

Is this something to do with 2FA?

I tried resetting it once 
![Screenshot_2024-11-08-16-35-44-70_c3a231c25ed346e59462e84656a70e50](https://github.com/user-attachments/assets/735e038a-5cac-41a6-9234-ea364441a8f0)

**Comment by sockless-coding** [comment]
@vaibhavratnaparkhi do you happen to have a Aquarea device? If so there is another integration for that https://github.com/cjaliaga/home-assistant-aquarea

**Comment by deffenti** [comment]
Hi @sockless-coding,

Every time I update HA core I have to uninstall and reinstall the integration. It was no big deal, as it always ended up working.

Since the last update I have been getting "Unknown error occurred". I have been assuming that it is an API issue and that it would somehow get fixed in the next integration update. Is it just me or are you having the same problem?

I thank you in advance.
