### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by k1ng440** [sockless-coding/panasonic_cc#35]
suddenly stopped working with 403 code. the mobile app still works fine. 

```
2021-06-08 09:21:57 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry  for panasonic_cc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/panasonic_cc/__init__.py", line 79, in async_setup_entry
    devices = await hass.async_add_executor_job(api.get_devices)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/pcomfortcloud/session.py", line 172, in get_devices
    self.login()
  File "/usr/local/lib/python3.8/site-packages/pcomfortcloud/session.py", line 99, in login
    self._create_token()
  File "/usr/local/lib/python3.8/site-packages/pcomfortcloud/session.py", line 132, in _create_token
    raise ResponseError(response.status_code, response.text)
pcomfortcloud.session.ResponseError: Invalid response, status code: 403 - Data: <html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
</body>
</html>
```

**Comment by jamiewalters** [comment]
Have the same issue. Logs started mentioning it around 3 hours ago..

**Comment by sockless-coding** [comment]
I've noticed the same issue, my guess is that Panasonic changed something on their end. 
I'm looking in to it. But we might have to wait for lostfields to update the library.

**Comment by k1ng440** [comment]
replace the manifest.json and restart the home assistant
```
{
    "domain": "panasonic_cc",
    "name": "Panasonic Comfort Cloud",
    "version": "1.0.28",
    "config_flow": true,
    "documentation": "https://github.com/sockless-coding/panasonic_cc/",
    "dependencies": [],
    "codeowners": ["sockless-coding"],
    "requirements": ["git+https://github.com/k1ng440/python-panasonic-comfort-cloud.git@patch-1#pcomfortcloud==0.0.21"]
}
```

**Comment by EvertJob** [comment]
Normally this happende to me then Panasonic updates there user agrement (than you need yo login via the app, agree an exit) and it's fixed but this time it doesn't help.

**Comment by k1ng440** [comment]
panasonic checking user agent, without `User-Agent: G-RAC` all requests fails

**Comment by EvertJob** [comment]
> replace the manifest.json and restart the home assistant
> 
> ```
> {
>     "domain": "panasonic_cc",
>     "name": "Panasonic Comfort Cloud",
>     "version": "1.0.28",
>     "config_flow": true,
>     "documentation": "https://github.com/sockless-coding/panasonic_cc/",
>     "dependencies": [],
>     "codeowners": ["sockless-coding"],
>     "requirements": ["git+https://github.com/k1ng440/python-panasonic-comfort-cloud.git@patch-1#pcomfortcloud==0.0.21"]
> }
> ```
> 
> edit: if restarting doesn't work. remove the integration and redo from config -> integrations

This works for me! You can find manifest.json under`custom_components/panasonic_cc/manifest.json`

**Comment by filipvdb** [comment]
> > replace the manifest.json and restart the home assistant
> > ```
> > {
> >     "domain": "panasonic_cc",
> >     "name": "Panasonic Comfort Cloud",
> >     "version": "1.0.28",
> >     "config_flow": true,
> >     "documentation": "https://github.com/sockless-coding/panasonic_cc/",
> >     "dependencies": [],
> >     "codeowners": ["sockless-coding"],
> >     "requirements": ["git+https://github.com/k1ng440/python-panasonic-comfort-cloud.git@patch-1#pcomfortcloud==0.0.21"]
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > edit: if restarting doesn't work. remove the integration and redo from config -> integrations
> 
> This works for me! You can find manifest.json under`custom_components/panasonic_cc/manifest.json`

This works for me too! Thanks!

**Comment by sygys** [comment]
After changing the manifest and removing the integration it is no longer available in config - integrations

**Comment by k1ng440** [comment]
> After changing the manifest and removing the integration it is no longer available in config - integrations

validate the JSON.

**Comment by sygys** [comment]
how di i validate. sorry im noob to this

**Comment by k1ng440** [comment]
> how di i validate. sorry im noob to this

copy paste whole file to this https://jsonlint.com/

**Comment by sygys** [comment]
it tells me its valid

**Comment by sygys** [comment]
but for some reason the old manifest isnt working anymore too. I removed the integration and try to reinstall it but its not showing up anymore in integrations

**Comment by sygys** [comment]
It was the damn cache in the browser

**Comment by maartenhendrix** [comment]
After trying to remove the json and removing the integration and installing it again i'm not able to login anymore: 
`This error originated from a custom integration.

Logger: custom_components.panasonic_cc.config_flow
Source: custom_components/panasonic_cc/config_flow.py:60
Integration: Panasonic Comfort Cloud (documentation)
First occurred: 11:50:45 AM (1 occurrences)
Last logged: 11:50:45 AM

Unexpected error creating device
Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/config_flow.py", line 60, in _create_device
    devices = await self.hass.async_add_executor_job(api.get_devices)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/pcomfortcloud/session.py", line 172, in get_devices
    self.login()
  File "/usr/local/lib/python3.8/site-packages/pcomfortcloud/session.py", line 99, in login
    self._create_token()
  File "/usr/local/lib/python3.8/site-packages/pcomfortcloud/session.py", line 132, in _create_token
    raise ResponseError(response.status_code, response.text)
pcomfortcloud.session.ResponseError: Invalid response, status code: 403 - Data: <html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
</body>
</html>

`
Does anybody have a suggestion?

**Comment by maartenhendrix** [comment]
> Read above.. edit the manifest like above and then readd the airco in the integrations

that fixed it.
Thank you

**Comment by sockless-coding** [comment]
I've released v1.0.30 it should fix the issue.

**Comment by adebree** [comment]
Updating the integration via HACS to `v1.0.30` and restarting HA fixed it for me. Thx :)

**Comment by verstrepeng** [comment]
I had the same issue. The update of the integration via HACS fixed it.
Many thanks !
