### ISSUE TITLE
States attribute "is_on" always seems to be true, how to detect if AC is really cooling?

### ISSUE THREAD

**Issue by michelcve** [sockless-coding/panasonic_cc#43]
I'm trying to detect it my AC is actually cooling, but the states object doesn't seem to have that kind of information.

As far as the attributes go, `hvac_action` is always the preset mode (e.g. cooling), and `is_on` is always "true".

So how can I detect that my AC is actually doing something?

**Comment by sockless-coding** [comment]
Hi @michelcve the only thing you can look at is the (hvac) state. 
The only information we get from the device is the mode it is in (off, heat, cool, heat_cool, dry, fan_only). 
It doesn't provide any information if it's actually doing anything, if you have the energy sensor you might be able to use that to detect if it's actually doing anything.
