### ISSUE TITLE
Eco preset / quiet mode swapped

### ISSUE THREAD

**Issue by flybrys** [sockless-coding/panasonic_cc#45]
My unit (CS-RZ25WKRW) has a quiet mode for fan speed as well as an eco function

Setting the eco mode in the panasonic app turns on the eco light however setting it in this integration turns on quiet mode for the fan. I don't seem to have any other options to turn on Eco mode.
Is this an known issue or something that can be added?
I'm using the CZ-TACG1 adaptor if it is related to that.

**Comment by sockless-coding** [comment]
Hi @brywithawhy, I think I might be able to expose the eco preset mode. 
One thing you could try is calling `climate.set_preset_mode` with `eco` and see if it does anything.

**Comment by brywithawhy** [comment]
Hi @sockless-coding 
Calling the service sets quiet mode on the unit, but eco is reported in the integration. Same as doing it via the lovelace card

**Comment by Kugelfang666** [comment]
I have a similar issue:

my units CS-X35ZKEW-H feature a "quiet mode". However in order to engage it via this integration I have to set preset to "Eco mode"

**Comment by sockless-coding** [comment]
This is an old bug/sin... fixing it would introduce a breaking change... the HA built-in PRESET_ECO was used for Quiet from day 1

**Comment by Kugelfang666** [comment]
Ok i see, personally I would be fine with a breaking change but I totally get it that it might not be worth it for many

**Comment by sockless-coding** [comment]
@Kugelfang666 there should now be a switch to toggle the eco navi feature

**Comment by Kugelfang666** [comment]
Thanks for putting effort into this. I just updated to 1.0.51 but I don’t see that button, am I looking at the right spot?

![IMG_0543](https://github.com/sockless-coding/panasonic_cc/assets/3289654/77a74ed3-bdbe-4633-9c73-c4de06b3e8d1)

**Comment by sockless-coding** [comment]
It should be a separate switch
![image](https://github.com/sockless-coding/panasonic_cc/assets/25462432/cebd3fd7-7432-42fb-948b-f996286ff40b)

**Comment by flybrys** [comment]
> I have a similar issue:
> 
> my units CS-X35ZKEW-H feature a "quiet mode". However in order to engage it via this integration I have to set preset to "Eco mode"

It's been a while since I raised this and can't quite remember what the result was, but I ended up using an esp32 instead of the cz-tacg device to control it all without the comfort cloud and the functionality matches that of the remote control

https://github.com/DomiStyle/esphome-panasonic-ac
If you're interested

**Comment by Kugelfang666** [comment]
> It should be a separate switch ![image](https://private-user-images.githubusercontent.com/25462432/344322289-cebd3fd7-7432-42fb-948b-f996286ff40b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2NDgyOTIsIm5iZiI6MTcxOTY0Nzk5MiwicGF0aCI6Ii8yNTQ2MjQzMi8zNDQzMjIyODktY2ViZDNmZDctNzQzMi00MmZiLTk0OGItZjk5NjI4NmZmNDBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDA3NTk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0NzNhNDcwZTllN2YyNzY2M2E1ZWFmMWYxM2ZlYjhkNjViMmVhYjQwMjg2OTAwMWYzZWZlMzMyN2ZjNDM2YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k32IRp-QVEIhD179gxWoVXKQDozXSNCIfHLgDDngKEQ)

this setting did not show up for any of my devices after updating

**Comment by sockless-coding** [comment]
I've added a new configuration option (in the next release) that should be default True for new installations and False for existing ones.
![image](https://github.com/sockless-coding/panasonic_cc/assets/25462432/2c9c7340-238f-44c0-a297-6cc804394f38)
That switches to the panasonic naming of presets:
![image](https://github.com/sockless-coding/panasonic_cc/assets/25462432/85f069eb-e5d8-4fce-ab6f-f3a34f74bb38)

**Comment by Kugelfang666** [comment]
I can confirm this is now working for me! Thanks a lot for putting the effort into this, much apprechiated!
