### ISSUE TITLE
Current Power drops to 0 every hour

### ISSUE THREAD

**Issue by purcell-lab** [sockless-coding/panasonic_cc#46]
https://github.com/sockless-coding/panasonic_cc/blob/5746f9ccf8d33bcbc0f1d5bc4fab6c4a5d74bad8/custom_components/panasonic_cc/panasonic.py#L132

I was wondering if we could revisit the included calculation for 'current power', as my power seems to update each hour at minute 33 to the correct value for the hour and then resets to zero at 5 minutes past the hour, so half of each hour is zero:
![image](https://user-images.githubusercontent.com/79175134/127244108-3bd8264b-1c4e-40b4-8d52-c1e508f6a143.png)

I think it would be better to see something like this as the standard output:

![image](https://user-images.githubusercontent.com/79175134/127244549-2b26364c-ba8c-4dfc-88c1-68f78bbbace8.png)

Based on the output from pcomfortcloud, fixed value for each hour:

`$ pcomfortcloud $user $passwd history 1 Day 20210728
id                       : xxxxxxxxxxxx
parameters
    currencyUnit         : $
    energyConsumption    : 12.600000000000001
    estimatedCost        : 0.0
    historyDataList      :
        dataNumber       : 0
        consumption      : 0.1
        cost             : 0.0
        averageSettingTemp: 17.0
        averageInsideTemp: 16.5
        averageOutsideTemp: 6.25

        dataNumber       : 1
        consumption      : 1.1
        cost             : 0.0
        averageSettingTemp: 17.0
        averageInsideTemp: 17.0
        averageOutsideTemp: 6.5

        dataNumber       : 2
        consumption      : 1.0
        cost             : 0.0
        averageSettingTemp: 17.0
        averageInsideTemp: 17.0
        averageOutsideTemp: 7.75

        dataNumber       : 3
        consumption      : 0.9
        cost             : 0.0
        averageSettingTemp: 17.0
        averageInsideTemp: 17.0
        averageOutsideTemp: 7.5

        dataNumber       : 4
        consumption      : 0.9
        cost             : 0.0
        averageSettingTemp: 17.0
        averageInsideTemp: 17.0
        averageOutsideTemp: 9.75

        dataNumber       : 5
        consumption      : 0.9
        cost             : 0.0
        averageSettingTemp: 17.0
        averageInsideTemp: 16.75
        averageOutsideTemp: 10.25

        dataNumber       : 6
        consumption      : 0.9
        cost             : 0.0
        averageSettingTemp: 18.5
        averageInsideTemp: 18.25
        averageOutsideTemp: 10.0

        dataNumber       : 7
        consumption      : 2.4
        cost             : 0.0
        averageSettingTemp: 18.5
        averageInsideTemp: 17.75
        averageOutsideTemp: 10.0

        dataNumber       : 8
        consumption      : 1.1
        cost             : 0.0
        averageSettingTemp: 19.25
        averageInsideTemp: 18.75
        averageOutsideTemp: 10.75

        dataNumber       : 9
        consumption      : 3.3
        cost             : 0.0
        averageSettingTemp: 19.5
        averageInsideTemp: 18.75
        averageOutsideTemp: 10.0

        dataNumber       : 10
        consumption      : 0.0
        cost             : 0.0
        averageSettingTemp: 19.5
        averageInsideTemp: 19.0
        averageOutsideTemp: 9.0

        dataNumber       : 11
        consumption      : -255
        cost             : -255
        averageSettingTemp: -255
        averageInsideTemp: -255
        averageOutsideTemp: -255

        dataNumber       : 12
        consumption      : -255
        cost             : -255
        averageSettingTemp: -255
        averageInsideTemp: -255
        averageOutsideTemp: -255`

**Comment by sockless-coding** [comment]
Hmm, guessing Panasonic has different update intervals for their devices when it comes to energy readings mine updates every 15min

![image](https://user-images.githubusercontent.com/25462432/127769149-23b40af9-8fb4-4b34-bbfa-54e6c78222cb.png)
