### ISSUE TITLE
Problem with login

### ISSUE THREAD

**Issue by maciekb** [sockless-coding/panasonic_cc#5]
Hi,

Yesterday everything was ok, but today integration doesn't work. I've tried to remove integration from Home Assistant and create it again, but error in log file is the same:

> 2020-05-29 13:06:16 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for panasonic_cc doing I/O at custom_components/panasonic_cc/panasonic.py, line 49: self._api.login()
> 2020-05-29 13:06:18 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for panasonic_cc doing I/O at custom_components/panasonic_cc/panasonic.py, line 50: data = self._api.get_device(self.id)
> 2020-05-29 13:06:19 WARNING (MainThread) [custom_components.panasonic_cc] Failed to setup device: Salon

**Comment by sockless-coding** [comment]
Hi,

I would guess there was an error with the login/token or you have an pending eula waiting on that account... Panasonic seem to forget that you agreed to them every now and again.
But I've fixed the IO in event loop warning, though it shouldn't break the setup.

**Comment by maciekb** [comment]
Thanks for fixing the IO event loop warning. Unfortunately, I can't figure out why login and integration fails. I have not pending EULA to accept, mobile application login and works just fine. Integrations directly with Alexa or Google Assistant also works just fine.

**Comment by sockless-coding** [comment]
Are you logged in to the same account somewhere else? I found it more stable to have a dedicated Panasonic account for HA.
Also I added some more error info on setup, hopefully it will shed some light on the issue...

**Comment by maciekb** [comment]
This is the message that appears in the log after updating the integration to the latest version:
2020-05-31 17:48:29 WARNING (MainThread) [custom_components.panasonic_cc] Failed to setup device: Salon (5 is not a valid AirSwingLR)

**Comment by sockless-coding** [comment]
Ah, then it's the Left/Right swing mode that's causing the problem. 
Can you check in the app what it's set to? So I can issue a patch to the panasonic lib for that setting.
Setting it to something else should solve your problem.

**Comment by maciekb** [comment]
Error is when Air Swing is set to second position from left:
![IMAGE 2020-06-01 00:48:40](https://user-images.githubusercontent.com/18700/83364443-a3b79100-a3a1-11ea-8613-42a33251a2e5.jpg)

With setting like below, integration is working ok:
![IMAGE 2020-06-01 00:50:13](https://user-images.githubusercontent.com/18700/83364480-db263d80-a3a1-11ea-8103-70bed3d13729.jpg)

**Comment by sockless-coding** [comment]
I've issued a pull request to https://github.com/lostfields/python-panasonic-comfort-cloud who maintains the Panasonic lib. So we have to wait for that to go through.

**Comment by maciekb** [comment]
Thanks!
