### ISSUE TITLE
Local support

### ISSUE THREAD

**Issue by sygys** [sockless-coding/panasonic_cc#50]
Me and a few people have successfully got our Panasonic AC local and away from cloud comfort.

It works faster, it's more reliable, it's local and it has the same climate integration and features you would expect.

And thanks to espthings for designing the circuit board with esp32 and logic converter it can be connected to the AC plug and play. No more AC going offline due to a version mismatch or an API changing!

Yesterday I finished designing the case for it. (Still need to get some blue filement though)

I would highly recommend checking it out. Its more then worth it!

![20210812_010304](https://user-images.githubusercontent.com/73538763/129145496-4d7f1571-4d12-4ae4-ab09-5be8dab7c241.jpg)

![20210812_001321](https://user-images.githubusercontent.com/73538763/129145557-a98c8812-db2f-4763-ae30-b744189b24e0.jpg)

**Comment by daggy72** [comment]
Great to hear!
I'm fed up with the unreliability of the PCC app lately and now it seems they are blocking my IP address (from my home WiFi I can't access PCC App, switching to 4G I can).

 So I am starting soldering today! I have 8 units in my home.

**Comment by ugoogalizer** [comment]
Definitely that's exciting and interesting news. I'd love to move local and not be reliant on the cloud. Where can we check out your work please?

**Comment by ugoogalizer** [comment]
That certainly is interesting. I would very much liek to be able to control the thermostat without reliance on the cloud.  Where can we check it out / find out more please?

**Comment by sygys** [comment]
https://github.com/DomiStyle/esphome-panasonic-ac/tree/dev-cztacg1

**Comment by ugoogalizer** [comment]
Awesome work, thank you!

**Comment by beMoD** [comment]
Thank you but i don't have access to a printer. Also if I understand it correctly the module will fit into the original case :-)

**Comment by kongjudas** [comment]
Who can I contact to get a couple of those, please? I have two A/C’s and none of them are stable in HA. I really need it to keep the WAF at a satisfying level.

**Comment by sygys** [comment]
since i have been using these modules not once had problems. The integration on this page is nice but it is more a temporary fix. Everytime panasonic changes anything to the app or the cloud the AC will fall of the grid again.

This is the link to the guy who makes them. He has only one left. You can make them yourself. I did so using hardware for a few bucks. https://www.espthings.io/index.php/2021/08/03/esp32-based-panasonic-airconditioning-wifi-interface/

This is the link to make them yourself: https://github.com/DomiStyle/esphome-panasonic-ac

**Comment by codyc1515** [comment]
I think the issue can be closed now as it's clear where to get local support.
