### ISSUE TITLE
Problem getting current power usage

### ISSUE THREAD

**Issue by Th3M1k3y** [sockless-coding/panasonic_cc#51]
Has something changed again?

I am getting this under Logs

```Logger: homeassistant.helpers.entity
Source: helpers/entity.py:657
First occurred: 16:08:52 (1 occurrences)
Last logged: 16:08:52

Update of sensor.spisestue_daily_energy is taking over 10 seconds
```

```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:692
Integration: Sensor (documentation, issues)
First occurred: 16:13:43 (1 occurrences)
Last logged: 16:13:43

Updating panasonic_cc sensor took longer than the scheduled update interval 0:00:30
```

I can still control the heatpump.

**Comment by Th3M1k3y** [comment]
```This error originated from a custom integration.

Logger: homeassistant.helpers.entity
Source: custom_components/panasonic_cc/panasonic.py:128
Integration: Panasonic Comfort Cloud (documentation)
First occurred: 16:54:31 (1 occurrences)
Last logged: 16:54:31

Update for sensor.spisestue_daily_energy fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 446, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 662, in async_device_update
    await task
  File "/config/custom_components/panasonic_cc/sensor.py", line 140, in async_update
    await self._api.update_energy()
  File "/config/custom_components/panasonic_cc/panasonic.py", line 68, in update_energy
    await self.do_update_energy()
  File "/config/custom_components/panasonic_cc/panasonic.py", line 128, in do_update_energy
    c_energy = data['parameters']['energyConsumption']
KeyError: 'energyConsumption'
```

**Comment by sockless-coding** [comment]
@Th3M1k3y this issue seems to be on Panasonic's end. The api is very slow at the moment :\
I am getting the same error messages...
But I'm currently rewriting the component and the Panasonic Comfort Cloud api client.

**Comment by Th3M1k3y** [comment]
I just tested with my phone and their app.... Yea, it is very slow. Not sure why I didn't think of trying that before...

Will the rewrite allow the daily energy entity to be used in the Energy tab?

**Comment by sockless-coding** [comment]
Yes, I will fix the energy sensor and maybe add a cumulated energy sensor

**Comment by raczgy** [comment]
Hi There, I have to admin that something not as good with energy sensors as expected. actually if I turn energy sensor on on the configuration page then the entire integration became very instable. I mean, the entities are not available for long time if at all and if this is not the last integration to start than it delays other components to start within Hassio. 
with the new Energy monitor in Home assistant it would be awesome to see the consumption for each air conditioner device.
I would appreciate if you could spend some time to fix this as I think it would have a great value.

Thank you!
G
