### ISSUE TITLE
Falls out and needs several reboots to activate again

### ISSUE THREAD

**Issue by kongjudas** [sockless-coding/panasonic_cc#54]
In the last few weeks, the integration doesn't connect to the Comfort Cloud and leaves my heat pump not found. After several reboots it seems to find it randomly.

**Comment by sockless-coding** [comment]
Hi @kongjudas, unfortunately this is a problem with the Panasonic Servers, not much I can do about it.

**Comment by kongjudas** [comment]
Thank you. I'm trying to make a automation routine that reloads the integration if "unknown". Too bad, I just bought another CC unit. I should have known better after all this server/ API trouble.

**Comment by rogerpdg** [comment]
> 
> 
> Hi! Aren't there any updates on this issue?I I'm also experiencing this kind of issue unfortunately. I have several AC units in my home and I lose access to them randomly but only like one at a time, it's never all of them.


In my case, as soon as I disable daily energy sensor and reboot , all seems to work, maybe the problem is about energy sensor.

**Comment by sockless-coding** [comment]
The main issue is the request to fetch the energy reading, some time it can take more than 30sec to get the reply from the Panasonic Servers. That causes the HA integration to fail since the update took too long, and it's a synchronous call.

**Comment by rogerpdg** [comment]
I looked into Panasonic cc app and when I enter into statics page and it works fast, the integration seems to work fine. But when it takes some time to load the page, the integration does not work with power statics on. 

Thank you for the reply

**Comment by rgcouto** [comment]
> > Hi! Aren't there any updates on this issue?I I'm also experiencing this kind of issue unfortunately. I have several AC units in my home and I lose access to them randomly but only like one at a time, it's never all of them.
> 
> In my case, as soon as I disable daily energy sensor and reboot , all seems to work, maybe the problem is about energy sensor.

I now have the energy sensor disabled for some days and, in fact, I've stopped experiencing troubles with the integration. However, I'm still going with the migration to the on-prem solution so that I can turn off the panasonic integration. You never know when they'll decide to cut it off somehow.

**Comment by erikaugl** [comment]
I'm also having issues on one of my indoor units when the energy tracking is activated. The indoor unit with a integrated com module work fine all the time, but the indoor unit with a com dongle is not able to connect when energy tracking is activated.
