### ISSUE TITLE
Only 4 Entities Added

### ISSUE THREAD

**Issue by cojaxx** [sockless-coding/panasonic_cc#55]
Hello,
Have just installed the integration and only 4 entities have been added
1 - On/Off status
2 - Inside Temp
3 - Nanoe
4 - Outside Temp

The unit I have is a 
Outdoor U-71PZ3R5 / Indoor  S-71PE3R
Control Unit: Panasonic RTC6

Works fine through the native iOS app. I assume there have been some API changes and it doesn't "Just work" anymore?

Anything I can do to fix it myself?

Regards,
Peter

**Comment by robcoward** [comment]
Read the README. If you want the 2 sensors for the power usage, you need to tick the checkbox in the integration configuration. If you want to see the power usage show up in the new Energy screens, see the comments in https://github.com/sockless-coding/panasonic_cc/issues/49

**Comment by cojaxx** [comment]
Ahh I wasn't looking in the right section! All works well! thankyou!
