### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by mmmmm009** [sockless-coding/panasonic_cc#57]
I have the latest HA.
Successfully installed Panasonic Comfort Cloud via HACS.
I don't see Panasonic Comfort Cloud in new Integration in HA (Config -> Integrations -> add new).
(I also tried with/without this code in configuration.yaml
climate:
  - platform: panasonic_ac
    username: xxxx
    password: xxxx
)

**Comment by BinnenBeest** [comment]
I also installed the integration via HACS but it doesn’t work. Do not get the integration neither a screen to login.

**Comment by eddik1970** [comment]
I could not find Panasonic Comfort Cloud after installing hacs and using Brave (Chrome clone). Testing with Firefox it showed up immediately.
