### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by VetonAbdiu** [sockless-coding/panasonic_cc#59]
Error setting up entry for panasonic_ccTraceback (most recent call last): File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup result = await component.async_setup_entry(hass, self) # type: ignore File "/config/custom_components/panasonic_cc/__init__.py", line 79, in async_setup_entry devices = await hass.async_add_executor_job(api.get_devices) File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run result = self.fn(*self.args, **self.kwargs) File "/usr/local/lib/python3.9/site-packages/pcomfortcloud/session.py", line 172, in get_devices self.login() File "/usr/local/lib/python3.9/site-packages/pcomfortcloud/session.py", line 99, in login self._create_token() File "/usr/local/lib/python3.9/site-packages/pcomfortcloud/session.py", line 132, in _create_token raise ResponseError(response.status_code, response.text) pcomfortcloud.session.ResponseError: Invalid response, status code: 504 - Data: <html> <head><title>504 Gateway Time-out</title></head> <body> <center><h1>504 Gateway Time-out</h1></center> </body> </html> 

Its panasonic server right ?

**Comment by agrauballe** [comment]
Yes servers were down for maintenance yesterday. Up and running again
