### ISSUE TITLE
Failed to setup device: Bedroom AC (5 is not a valid AirSwingLR)

### ISSUE THREAD

**Issue by com-xuonghuynh** [sockless-coding/panasonic_cc#6]
I got this issue on hassio Log: 

Logger: custom_components.panasonic_cc
Source: custom_components/panasonic_cc/__init__.py:73
Integration: Panasonic Comfort Cloud (documentation)
First occurred: 12:40:37 AM (1 occurrences)
Last logged: 12:40:37 AM

Failed to setup device: Bedroom AC (5 is not a valid AirSwingLR)

**Comment by sockless-coding** [comment]
Hi,

It's the same issue as https://github.com/sockless-coding/panasonic_cc/issues/5 if you change left/right swing mode from the second left position it will work.
I've issued a pull request with a fix to the panasonic lib.

**Comment by com-xuonghuynh** [comment]
@sockless-coding thank you. My AC don't have function for L/R swing so I can't put it to that position. Will wait it fix in panasonic lib
