### ISSUE TITLE
No data from cloud. No faults in logfile

### ISSUE THREAD

**Issue by Klabatzie** [sockless-coding/panasonic_cc#63]
Hello, I dont get any data from the smart cloud from my air to water heatpump WH-SDC0709J3E5.
No issue's in the logfiles

entities are available but stay at 0
data is showing normal in the smart cloud app.
![image](https://user-images.githubusercontent.com/69648313/147858140-7b24b40c-7c42-44d1-af4b-6c7d58f100c4.png)

**Comment by MarcinKnD** [comment]
I think that not gonna work. I cna't find any plugin that works with aquarea heat pump. Od You find any working please provide a link

**Comment by djoenez** [comment]
Unfortunately, i have the same issue. with almost the same aquarea heat pump.. :(
