### ISSUE TITLE
Can't see integration in HA - instaled via HASC

### ISSUE THREAD

**Issue by sabatpoznan** [sockless-coding/panasonic_cc#67]
I can't see Panasonic Cloud Componen in integration menu in HA, I have installed/unsinstaled this component several times already.

**Comment by socialhugo** [comment]
Me too. I installed the panasonic component in the integrations menu of HACS. Did a restart and it seems to run find. Then I try to add the integration in home assistant. But I can't find it. 
Thanks for creating this app though! Hope you can help us

**Comment by sabatpoznan** [comment]
I just did this it was a lot 

https://github.com/lsochanowski/GoHeishaMon

**Comment by socialhugo** [comment]
I found the problem. After installing and did all the things as described above ... I remove the cache from my browser and restarted the browser. And then it worked.

**Comment by codyc1515** [comment]
Great to hear it is solved. Could you please close out the issue?
