### ISSUE TITLE
Does not work with Air To Water Aquarea heat pums

### ISSUE THREAD

**Issue by fatmacheto** [sockless-coding/panasonic_cc#68]
![image](https://user-images.githubusercontent.com/25221505/153083022-276b9bfb-d7a1-4a75-8191-ba02c2f14cb7.png)

All I can see is imported after the add on is as on the screen shot but  nothing works and the device has much more parameters that this.

If needed I can provide access to my aquarea heatpump

**Comment by owcazz** [comment]
I have the same situation.

**Comment by zamzon** [comment]
Hi
Any news on this topic.
I have the same issue with my A2W

**Comment by villar3** [comment]
hi , i have the same issue with the last version. do you need some log to investigate ?

**Comment by sockless-coding** [comment]
Guess they've added some sort of support for Aquarea devices in the CC api.
But if I'm to add support for it, I need some logs.
Can start with the logs from HA.
But I might need packet logs from the Comfort Cloud App.

**Comment by eliashe92** [comment]
> Guess they've added some sort of support for Aquarea devices in the CC api. But if I'm to add support for it, I need some logs. Can start with the logs from HA. But I might need packet logs from the Comfort Cloud App.

Hi It would be much appreciated to get support for Aquarea device (air to water heat pump)
How can get the logs for you?

**Comment by villar3** [comment]
i find this log when i start the component

`Logger: homeassistant.components.sensor
Source: custom_components/panasonic_cc/sensor.py:142 
Integration: Capteur ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22)) 
First occurred: 21:07:47 (2 occurrences) 
Last logged: 21:07:47

Error adding entities for domain sensor with platform panasonic_cc
Error while setting up panasonic_cc platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 692, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 789, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 583, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 551, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/panasonic_cc/sensor.py", line 142, in state
    return round(self._api.daily_energy,2)
TypeError: type NoneType doesn't define __round__ method`

**Comment by fp-lnawrat** [comment]
I would love to get support for air to water pumps 🙏

**Comment by sockless-coding** [comment]
This issue has been inactive for a while, so we’re closing it for now. If you believe this issue is still relevant, please feel free to reopen it or create a new one.
