### ISSUE TITLE
daily energi stops after some time

### ISSUE THREAD

**Issue by telvgehc** [sockless-coding/panasonic_cc#69]
After some time daily energy stops wokring and home assistant needs to be restarted for it to start counting again.

**Comment by torsteinelv** [comment]
If home assistant is restarted it works for some hours before stoping again.

**Comment by codyc1515** [comment]
Are you still facing this issue?

**Comment by sockless-coding** [comment]
This issue has been inactive for a while, so we’re closing it for now. If you believe this issue is still relevant, please feel free to reopen it or create a new one.
