### ISSUE TITLE
After installing I got "Bad request" 400 in Log

### ISSUE THREAD

**Issue by narnaliai** [sockless-coding/panasonic_cc#7]
Hello,

```
Log Details (WARNING)
Logger: custom_components.panasonic_cc
Source: custom_components/panasonic_cc/__init__.py:73
Integration: Panasonic Comfort Cloud (documentation)
First occurred: 8:21:09 PM (1 occurrences)
Last logged: 8:21:09 PM

Failed to setup device: A2W (Invalid response, status code: 400 - Data: {"message":"Bad request","code":4008})
```

Can you help me ?

**Comment by sockless-coding** [comment]
Hi,

I'm guessing you have an aquarea smart cloud device (https://aquarea-smart.panasonic.com/) and not a comfort cloud device.
Unfortunately they don't use the same API but you can login in to the CC with ASC credentials for some reason.

**Comment by narnaliai** [comment]
Thank You,

You are right, my device from aquarea smart cloud.

Maybe someone have good experience with Smart Cloud devices ?

**Comment by sockless-coding** [comment]
I've looked at the api and it looks quite simple but I do not have an aquarea device myself so cant really test it...

**Comment by juzel69** [comment]
Hello

I have the same problem with my aquarea smart cloud device. You wrote that you looked at the api. I've got such a device. But where can I find the api documentation?

**Comment by sockless-coding** [comment]
Hi @juzel69,
I don't think I found any direct documentation I looked at the JS on page (their web ui) and it was pretty straight forward iirc.
Also, there's a js module of MM https://github.com/martinburheimtingstad/MMM-AquareaSmartCloud
Or you could go the IFTTT route https://ifttt.com/aquarea_smart_cloud
