### ISSUE TITLE
Fan Speed in Homekit

### ISSUE THREAD

**Issue by HKGEric** [sockless-coding/panasonic_cc#72]
Fan Speed only 50% or 100%.
How can i modify the setting to meet low, lowmid, mid, highmid and high?

**Comment by codyc1515** [comment]
HomeKit does not avail us such options. We must choose a percent between 1 and 100. How this unofficial integration chooses to do that is ultimately up to the developer.

**Comment by codyc1515** [comment]
Please close the issue.
