### ISSUE TITLE
Blank card in interface

### ISSUE THREAD

**Issue by kennethhaspeel** [sockless-coding/panasonic_cc#75]
I installed the integration yesterday. Login worked en the two units were added. But when I add to interface, it just shows a blank thermostat card.
![screenshot](https://i.imgur.com/jdwUog6.png)
It does seem to control the devices. I can click on heat/cool/.... In the thermostat card nothing changes but the airco is turned on. But not very convenient if i don't know if i set the temperature to 16° or 26°

**Comment by butterdn** [comment]
Try this
https://community.home-assistant.io/t/panasonic-comfort-cloud/229090/83?u=buttervn
