### ISSUE TITLE
Cannot get integration to show

### ISSUE THREAD

**Issue by yehpo** [sockless-coding/panasonic_cc#8]
Hi,
Not sure what I'm doing wrong, but I can't seem to get the integration working at all. I've installed it via HACS but now I can't see anything under integrations or entities.

**Comment by sockless-coding** [comment]
Hi,
If it's installed you could be able to add it from the + at the bottom right of the integration page.

**Comment by yehpo** [comment]
Hi, thanks for your reply. I've got that now, but no entity was created for my associated aircon unit.
