### ISSUE TITLE
Unexpected Error Creating Device

### ISSUE THREAD

**Issue by Elanges** [sockless-coding/panasonic_cc#81]
My Panasonic Aircond works fine, until the few days back it show error on homeassistant, then i try to reconfigure again it comes such error. can guide what goes wrong?
![image](https://user-images.githubusercontent.com/41864632/179699598-9f0b0ea0-5b26-4fdf-aad6-9cf694d57f56.png)

**Comment by sockless-coding** [comment]
@Elanges what version are you running? 
Since last week's API update, you need v1.0.32

**Comment by sockless-coding** [comment]
Did you install it using HACS or manually?

**Comment by Elanges** [comment]
using HACS

**Comment by sockless-coding** [comment]
Then just go to HACS and see if it shows any updates for Panasonic Comfort Cloud

**Comment by Elanges** [comment]
ok will try and see thanks.

**Comment by Moustik2002** [comment]
Hi @sockless-coding 
Same issue there in v1.0.35 while trying to fill Panasonic ID and password.

Any change through Panasonic API ?

**Comment by codyc1515** [comment]
I believe this should be solved now.
