### ISSUE TITLE
1.0.34 Unable to prepare setup

### ISSUE THREAD

**Issue by juz22** [sockless-coding/panasonic_cc#84]
I was using 1.0.31 until it stopped working a few days ago, and just updated directly to 1.0.34 however now get the following error:

```
Logger: homeassistant.setup

Source: setup.py:298 
First occurred: 12:54:35 (2 occurrences) 
Last logged: 13:00:05

Unable to prepare setup for platform panasonic_cc.climate: Platform not found (cannot import name 'HVACAction' from 'homeassistant.components.climate' (/usr/src/homeassistant/homeassistant/components/climate/__init__.py)).
```

I use the integration via HACS, but have tried manually deleting my custom_components/panasonic_cc directory and re-downloading to no avail.

My HA version is 2022.3.3 and is installed in docker on a Synology, which doesn't appear to give me direct access to the homeassistant/components/climate directory.

**Comment by sockless-coding** [comment]
@juz22 you need to update HA to at least 2022.5, they made some changes to the climate system in that version.

**Comment by juz22** [comment]
Thank you, that worked. I generally try to avoid updating HA unless absolutely necessary as the breaking changes sometimes take me days to remedy. But fortunately updating to 2022.7.6 has fixed the Panasonic CC and not introduced any significant problems...
