### ISSUE TITLE
Feature request "Heat operation" operating mode

### ISSUE THREAD

**Issue by erikengl** [sockless-coding/panasonic_cc#85]
In the Panasonic app and on the remote I have an option for an operating mode that allows me to set the temperature down to 8 degrees Celsius. When using normal heat mode I can only lower it to a minimum of 16 degrees.

I have the Panasonic heat pump at our cabin. Setting the temperature down to 8 degrees is very useful in the winter when we are not there, but want to keep the inside warm enough so that no pipes are freezing.

I have been trying to find out what this operating mode is called, by Panasonic, but I think it is "Heat operation".

**Comment by Canneton** [comment]
Actually this mode is called "RFP" (Room Freeze Protection) it has two options (8 and 10 degrees Celsius). The following pconfortcloud package commands allow to set it: constants.Power.On + constants.OperationMode.Heat + constants.FanSpeed.High + (temperature=8.0 OR temperature=10.0). It would be nice to have this mode accessible from HASS through the panasonic_cc package.

**Comment by karlrank** [comment]
Some devices also have a freely adjustable range for this "8-15C" mode, for example, my "NZ25YKE". 
What worked for me in my HASS setup was to just change the min_temp [here](https://github.com/sockless-coding/panasonic_cc/blob/master/custom_components/panasonic_cc/climate.py#L226) to 8.

I don't see anything useful in pcomfortcloud to base the minimum temperature on, only possible candidate I see when I dump the raw data for my device is `summerHouse`, my value is `2` but I can't find any more information about how it functions.

Maybe there should be a configuration parameter to set the minimum supported temperature? Or just set the default lowest temperature to 8?
Would either those changes be accepted if I made a PR @sockless-coding ?

**Comment by sockless-coding** [comment]
Already been addressed in newer versions
