### ISSUE TITLE
Switch NanoeX for"deviceNanoe=2" and EcoFunction feature (switch)

### ISSUE THREAD

**Issue by butterdn** [sockless-coding/panasonic_cc#86]
My aircon have feature deviceNanoe=2, so, to turn on NanoeX, turn-on value is 4.
And device have feature "ecoFunction=1", then "ecoFunctionData" is parameter to turn it on/off. And I think below are values of ecoFunctionData
class ecoFunctionData(Enum):
    Unavailable = 0
    Off = 1
    On = 2
It look like this for my device
![image](https://user-images.githubusercontent.com/95039638/184310347-18c07eb1-c1bb-4dcc-ae8b-e54e2ccf7a63.png)

`dryTempMin               : -1
modeAvlList
    autoMode             : 1
    fanMode              : 1
airSwingLR               : True
nanoe                    : True
autoMode                 : False
autoSwingUD              : True
ecoNavi                  : False
heatTempMax              : -1
temperatureUnit          : 0
iAutoX                   : True
coolTempMin              : -1
autoTempMin              : -1
quietMode                : True
powerfulMode             : False
timestamp                : 1660290341146
fanMode                  : False
coolMode                 : True
summerHouse              : 0
coolTempMax              : -1
permission               : 3
dryMode                  : True
nanoeList
    visualizationShow    : 0
nanoeStandAlone          : True
heatMode                 : False
fanSpeedMode             : -1
dryTempMax               : -1
autoTempMax              : -1
fanDirectionMode         : -1
ecoFunction              : 1
heatTempMin              : -1
pairedFlg                : False
parameters
    ecoFunctionData      : 1
    airSwingLR           : 1
    nanoe                : 4
    lastSettingMode      : 0
    ecoNavi              : 0
    ecoMode              : 0
    operationMode        : 1
    fanAutoMode          : 1
    errorStatus          : -255
    temperatureSet       : 28.5
    fanSpeed             : 3
    iAuto                : 1
    airQuality           : 0
    insideTemperature    : 27
    outTemperature       : 34
    operate              : 0
    airDirection         : 0
    actualNanoe          : 1
    airSwingUD           : 5
deviceNanoe              : 2`

**Comment by Ricks88** [comment]
Hello,

Can you please tell me how you created a Eco switch for the panasonic?

**Comment by butterdn** [comment]
I'm not familiar with hassio dev, I just use File editor to copy/paste and modified some code base on @sockless-coding .
Steps which I did like this:
A. With pcomfordcloud package:
1. Add this to "constants.py":
```
  class ecoFunctionData(Enum):
    Unavailable = 0
    Off = 1
    On = 2
```
2. With "session.py":
add to _def set_device(self, id, **kwargs)_:
```
  if key == 'ecoFunctionData':
    parameters['ecoFunctionData'] = value
```
add to _def _read_parameters(self, parameters = {}):_
```
  if 'ecoFunctionData' in parameters:
    value['ecoFunctionData'] = constants.ecoFunctionData(parameters['ecoFunctionData'])
```
B. Back to switch.py of PCC of @sockless-coding :
1. Create new "class PanasonicEcoFuncSwitch(ToggleEntity):". Please refer to original Nanoe class and modify code accordingly (name, id ...)
```
    async def async_turn_on(self, **kwargs):
        """Turn on nanoe."""
        await self._api.set_eco_mode(self._api.constants.ecoFunctionData.On)

    async def async_turn_off(self, **kwargs):
        """Turn off nanoe."""
        await self._api.set_eco_mode(self._api.constants.ecoFunctionData.Off)
```
2. Register new Eco switch entity. My modification as below:
```
def setup_platform(hass, config, add_entities, discovery_info=None):
    devices = []
    for device in hass.data[PANASONIC_DEVICES]:
        devices.append(PanasonicNanoeSwitch(device))
        devices.append(PanasonicEcoFuncSwitch(device))
    add_entities(devices)

async def async_setup_platform(hass, config, async_add_entities, discovery_info=None):
    pass

async def async_setup_entry(hass, entry, async_add_entities):
    devices = []
    for device in hass.data[PANASONIC_DEVICES]:
        devices.append(PanasonicNanoeSwitch(device))
        devices.append(PanasonicEcoFuncSwitch(device))
    async_add_entities(devices)
```

3. Add below for turn on/off eco switch in "panasonic.py":
```
    async def set_eco_mode(self, eco_mode):
        new_values = { "ecoFunctionData": eco_mode.value }
        await self.hass.async_add_executor_job(
            self.set_device,
            new_values
        )
        await self.do_update()
```

Hope you could apply for your version.

**Comment by Ricks88** [comment]
Wow haha, i do not understand it that far yet :P

I thought you just created an lovelance button/switch for the ECO.
Like Nanoe has its switch by default. 

Thought i just could create a new "switch" entity in Home Assistant :P

**Comment by sockless-coding** [comment]
v1.1.0 has switches for the different eco modes
