### ISSUE TITLE
Always shows "Inactive"

### ISSUE THREAD

**Issue by Ricks88** [sockless-coding/panasonic_cc#87]
Hello,

My Panasonic alway's shows status Inactive:
![inact](https://user-images.githubusercontent.com/91467918/184369038-1a298402-771c-4bad-80fe-b8016e5959a6.png)

Should it show "Cool, Heat.." etc instead?

**Comment by sockless-coding** [comment]
@Ricks88 the Panasonic API does not provide the information on the current status, so right now the component is comparing the current and target temperature to guess the state.
