### ISSUE TITLE
CS-Z25XKEW multisplit external temp. problem

### ISSUE THREAD

**Issue by tomkolp** [sockless-coding/panasonic_cc#93]
The outside temperature sensor is not working.
![image](https://user-images.githubusercontent.com/39633242/198845270-ef48c5f4-355c-4cfe-a148-73792363c7ce.png)
![image](https://user-images.githubusercontent.com/39633242/198845333-75617355-312e-4f19-a562-85049fcf4780.png)

**Comment by darkfile** [comment]
Hi, I have the same issue since last week...maybe they've changed the API again?

**Comment by tomkolp** [comment]
I noticed it works for me today.  I don't know exactly when it works.
![image](https://user-images.githubusercontent.com/39633242/202840455-aca3e4d6-fb21-4d45-be3a-9b10a187ad77.png)

**Comment by tomkolp** [comment]
It's not working again today

**Comment by codyc1515** [comment]
Working?

**Comment by sockless-coding** [comment]
This issue has been inactive for a while, so we’re closing it for now. If you believe this issue is still relevant, please feel free to reopen it or create a new one.
