### ISSUE TITLE
Installation hangs, parts of the files downloaded

### ISSUE THREAD

**Issue by clandtma** [sockless-coding/panasonic_cc#95]
Hi, trying to install v. 1.0.35 via HACS.
Installation hangs, wheel at the bottom continues to spin (left for at least 10 min, nothing happens).
![image](https://user-images.githubusercontent.com/117401001/203847103-83528f5c-77a6-4d31-a714-a09539fa3545.png)
Apparently parts of the files are downloaded
![image](https://user-images.githubusercontent.com/117401001/203847174-db3d293e-a4d9-45f7-8c22-61278659a267.png)
Log files state that a few files are not downloaded
![image](https://user-images.githubusercontent.com/117401001/203847412-ae994a43-8a57-439b-9253-e27c8533b061.png)
Home Assistant 2022.11.4
Supervisor 2022.11.2
Operating System 9.3
Frontend 20221108.0 - latest
Any ideas? Have tried to reinstall HACS (with needed reboots), but no luck. Same problem.
Thanks,
Christoffer

**Comment by clandtma** [comment]
Downloaded the integration manually from github, restarted and tried adding it. It shows up in Integrations but when logging in it gets stuck and nothing happens. Any suggestions what I might be doing wrong?
![image](https://user-images.githubusercontent.com/117401001/203848758-64e1deda-613d-43a1-b142-ca25d8f61552.png)

**Comment by clandtma** [comment]
Hi, a small update. While working on other matters, i updated the DNS-server of HA to 8.8.8.8. After that I managed to log in and it now works. I however tested again (with DNS updated) to remove HACS and reinstall Panasonic Comfort Cloud using HACS but it still did not work. Same files missing again. In other words, I have the integration working, but had to download it manually from Github.

**Comment by codyc1515** [comment]
Are you still facing issues?

**Comment by sockless-coding** [comment]
This issue has been inactive for a while, so we’re closing it for now. If you believe this issue is still relevant, please feel free to reopen it or create a new one.
