### ISSUE TITLE
Missing climate entity

### ISSUE THREAD

**Issue by law1618** [sockless-coding/panasonic_cc#97]
I restored the system from the HA backup and found that this integration was not working. 
Then, I deleted the integration, reinstalled the addon and then added the integration back to HA. 
Everything seemed working as I got two more entities which are nanoe switch and the temperature sensor. However, the most important entity - climate is missing and I have no way to find it back. Can someone please add me any advice?

**Comment by law1618** [comment]
It worked if I downgraded to v1.0.32

**Comment by codyc1515** [comment]
No problem. Please close the issue.
