### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by alexinfopro** [sockless-coding/panasonic_cc#99]
Hi

I've just set up my air conditioners using the mobile app, and have added the integration in HACS.

When adding the integration in HA, I get this error:

"Login ID or password is incorrect,or account is locked"

I can use the app successfully with these credentials. It's not clear how I can verify my credentials separately from the app.

One thing to note is that I've used a "+" character in the email address, I'm not sure if this is causing the issue?

myname.w+panasonic@gmail.com

Log below

This error originated from a custom integration.

Logger: custom_components.panasonic_cc.config_flow
Source: custom_components/panasonic_cc/pcomfortcloud/session.py:158
Integration: Panasonic Comfort Cloud (documentation)
First occurred: 18:37:22 (4 occurrences)
Last logged: 19:50:23

Unexpected error creating device
Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/config_flow.py", line 60, in _create_device
    devices = await self.hass.async_add_executor_job(api.get_devices)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 201, in get_devices
    self.login()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 105, in login
    self._create_token()
  File "/config/custom_components/panasonic_cc/pcomfortcloud/session.py", line 158, in _create_token
    raise ResponseError(response.status_code, response.text)
custom_components.panasonic_cc.pcomfortcloud.session.ResponseError: Invalid response, status code: 401 - Data: {"message":"Login ID or password is incorrect,or account is locked","code":4101}

**Comment by codyc1515** [comment]
Please check your credentials and try again. Failing that, you may need to wait 24 hours.

**Comment by sockless-coding** [comment]
This issue has been inactive for a while, so we’re closing it for now. If you believe this issue is still relevant, please feel free to reopen it or create a new one.
